create or replace PROCEDURE "PHA_NS_BM55_ND31" (P_MA_DBHC IN NVARCHAR2,P_LOAI_BAOCAO IN VARCHAR2, P_CONGTHUC VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE, P_CAP VARCHAR2, DONVI_TIEN number, cur OUT SYS_REFCURSOR) as
  QUERY_STR  CLOB; 
   INSERT_STR  CLOB; 
   INSERT_STR1  CLOB;
   QUERY_STR_CHI CLOB;
   QUERY_STR_DUTOAN CLOB;
   P_CT VARCHAR2(32767);   
   P_SQL_INSERT VARCHAR2(32767); 
   TEMP VARCHAR2(32767);
   P_SQL_CREATE_TABLE_TH  VARCHAR2(32767);  
    N_COUNT NUMBER(17,4):=0;
    P_SELECT_DBHC VARCHAR2(32767);

   --CHI DAU TU PHAT TRIEN
   CT_CDT_QP VARCHAR2(32767);   CT_CDT_AN VARCHAR2(32767);   CT_CDT_KH VARCHAR2(32767);   CT_CDT_HDKT VARCHAR2(32767); CT_CDT_HDKT_GT VARCHAR2(32767); CT_CDT_HDKT_NN VARCHAR2(32767);
   CT_CDT_QLNN VARCHAR2(32767);   CT_CDT_BVMT VARCHAR2(32767);   CT_CDT_BDXH VARCHAR2(32767);   CT_CDT_VH VARCHAR2(32767);
   CT_CDT_KHCN VARCHAR2(32767);   CT_CDT_GD VARCHAR2(32767);   CT_CDT_YT VARCHAR2(32767);   CT_CDT_TDTT VARCHAR2(32767);
   CT_CDT_PT VARCHAR2(32767);
   --DU TOAN DAU TU PHAT TRIEN
   CT_DT_CDT_QP VARCHAR2(32767);   CT_DT_CDT_AN VARCHAR2(32767);   CT_DT_CDT_KH VARCHAR2(32767);   CT_DT_CDT_HDKT VARCHAR2(32767);
   CT_DT_CDT_QLNN VARCHAR2(32767);   CT_DT_CDT_BVMT VARCHAR2(32767);   CT_DT_CDT_BDXH VARCHAR2(32767);   CT_DT_CDT_VH VARCHAR2(32767);
   CT_DT_CDT_KHCN VARCHAR2(32767);   CT_DT_CDT_GD VARCHAR2(32767);   CT_DT_CDT_YT VARCHAR2(32767);   CT_DT_CDT_TDTT VARCHAR2(32767);
   CT_DT_CDT_PT VARCHAR2(32767); CT_DT_CDT VARCHAR2(32767);CT_DT_CDT_01 VARCHAR2(32767);CT_DT_CDT_02 VARCHAR2(32767);CT_DT_CDT_03 VARCHAR2(32767);CT_DT_CDT_06 VARCHAR2(32767);
   BEGIN
    IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
        select STC_PA_SYS.FNC_CONVERT_FORMULA_HCSN(P_CONGTHUC) INTO P_CT from dual;       
        P_CT:= ' AND ' || P_CT;
    END IF;

    --Gán công thức
    -------Chi đầu tư    
    IF(UPPER(P_LOAI_BAOCAO) = 'DH') THEN 
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_QP from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_QP' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_AN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_AN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_KH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_KH' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_HDKT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_HDKT' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_HDKT_GT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_HDKT_GT' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_HDKT_NN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_HDKT_NN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_QLNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_QLNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_BVMT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_BVMT' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_BDXH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_BDXH' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_VH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_VH' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_KHCN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_KHCN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_GD from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_GD' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_YT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_YT' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_TDTT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_TDTT' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_CDT_PT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_PT' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy');
         
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_QP from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_YT';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_AN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_AN';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_KH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_KH';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_HDKT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_HDKT';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_QLNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_QLNN';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_BVMT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_BVMT';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_BDXH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_BDXH';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_VH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_VH';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_KHCN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_KHCN';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_GD from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_GD';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_YT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_YT';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_TDTT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_TDTT';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_PT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='DT_CDT_PT';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI_K_CTMTQG' AND MA_COT='DT_CDT';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_02 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI_K_CTMTQG' AND MA_COT='DT_CDT_02';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_01 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI_K_CTMTQG' AND MA_COT='DT_CDT_01';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_03 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI_K_CTMTQG' AND MA_COT='DT_CDT_03';
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_CDT_06 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI_K_CTMTQG' AND MA_COT='DT_CDT_06';
    END IF;
    IF(UPPER(P_LOAI_BAOCAO) = 'QT') THEN 
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_QP from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_QP';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_AN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_AN';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_KH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_KH';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_HDKT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_HDKT';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_HDKT_GT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_HDKT_GT';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_HDKT_NN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_HDKT_NN';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_QLNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_QLNN';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_BVMT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_BVMT';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_BDXH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_BDXH';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_VH from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_VH';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_KHCN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_KHCN';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_GD from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_GD';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_YT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_YT';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_TDTT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_TDTT';
         select REPLACE(CONGTHUC_WHERE, '''', '''') INTO CT_CDT_PT from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHITIEU_CHI' AND MA_COT='CDT_PT';
    END IF;
    
    P_SQL_CREATE_TABLE_TH := 'CREATE TABLE BM54_ND31(
        LOAI_CHITIEU NUMBER,MA_TKTN NVARCHAR2(100), MA_DIABAN NVARCHAR2(100),TEN_DIABAN NVARCHAR2(2000),MA_CAP NVARCHAR2(100),MA_CAPMLNS NVARCHAR2(100),MA_CHUONG NVARCHAR2(100),TEN_CHUONG NVARCHAR2(2000),MA_NGANHKT NVARCHAR2(100),MA_LOAI NVARCHAR2(100),
        MA_TIEUMUC NVARCHAR2(100), MA_MUC NVARCHAR2(100), MA_TIEUNHOM NVARCHAR2(100),MA_NHOM NVARCHAR2(100),MA_CTMTQG NVARCHAR2(100),MA_KBNN NVARCHAR2(100), NGAY_HIEU_LUC DATE, NGAY_KET_SO DATE,LOAI_DU_TOAN NVARCHAR2(100),
        MA_NGUON_NSNN NVARCHAR2(100),MA_DVQHNS NVARCHAR2(100),TEN_DVQHNS NVARCHAR2(2000), MA_NVC NVARCHAR2(100), GIA_TRI_HACH_TOAN NUMBER)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ';         

     QUERY_STR_CHI := 'SELECT 2,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,TO_DATE(to_char(NGAY_HIEU_LUC,''ddMMyyyy''), ''ddMMyyyy''),TO_DATE (to_char(NGAY_KET_SO,''ddMMyyyy''), ''ddMMyyyy''),ATTRIBUTE8
        ,SUM (GIA_TRI_HACH_TOAN) FROM PHA_HACHTOAN_CHI VC 
         GROUP BY  MA_TKTN,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,ATTRIBUTE8';   
        INSERT_STR := 'INSERT INTO BM54_ND31(LOAI_CHITIEU,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,LOAI_DU_TOAN,GIA_TRI_HACH_TOAN)('||QUERY_STR_CHI||')';
  
   QUERY_STR_DUTOAN := 'SELECT 3,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,TO_DATE(to_char(NGAY_HIEU_LUC,''ddMMyyyy''), ''ddMMyyyy''),TO_DATE (to_char(NGAY_KET_SO,''ddMMyyyy''), ''ddMMyyyy''),ATTRIBUTE8
        ,SUM (GIA_TRI_HACH_TOAN) FROM PHA_DUTOAN VC 
         GROUP BY  MA_TKTN,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,ATTRIBUTE8';   
        INSERT_STR1 := 'INSERT INTO BM54_ND31(LOAI_CHITIEU,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,LOAI_DU_TOAN,GIA_TRI_HACH_TOAN)('||QUERY_STR_DUTOAN||')';
  BEGIN
        SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = 'BM54_ND31';
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
    END;
  IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
    BEGIN
        EXECUTE IMMEDIATE P_SQL_CREATE_TABLE_TH;  
        EXECUTE IMMEDIATE INSERT_STR; 
        EXECUTE IMMEDIATE INSERT_STR1;  
    END;
    END IF;
--    IF(N_COUNT > 0) THEN
--    BEGIN
--        EXECUTE IMMEDIATE 'TRUNCATE TABLE BM54_ND31';
--        EXECUTE IMMEDIATE INSERT_STR; 
--        EXECUTE IMMEDIATE INSERT_STR1;    
--    END;
--    END IF;
    
    CASE 
        WHEN P_CAP='2' THEN TEMP:=' AND A.MA_CHUONG BETWEEN ''400'' AND ''999''';
        WHEN P_CAP='3' THEN TEMP:=' AND A.MA_CHUONG BETWEEN ''600'' AND ''999''';
        WHEN P_CAP='4' THEN TEMP:=' AND A.MA_CHUONG BETWEEN ''800'' AND ''999''';
        ELSE TEMP:='';
    END CASE;
    
        P_SELECT_DBHC:= '  A.MA_DIABAN IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||''') OR MA_DBHC_CHA IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||'''))';
        
        IF(P_SELECT_DBHC IS NOT NULL) THEN
        P_CT:=P_CT || P_SELECT_DBHC;
        ELSE
        P_CT:=P_CT;
        END IF;
           QUERY_STR:='SELECT HT.MA_CHUONG, HT.TEN_CHUONG, HT.MA_DVQHNS, HT.TEN_DVQHNS
                                , NVL(HT.CDT_QP,0) as CDT_QP, NVL(HT.CDT_AN,0) as CDT_AN, NVL(HT.CDT_KH,0) as CDT_KH, NVL(HT.CDT_HDKT,0) as CDT_HDKT, NVL(HT.CDT_HDKT_GT,0) as CDT_HDKT_GT, NVL(HT.CDT_HDKT_NN,0) as CDT_HDKT_NN, NVL(HT.CDT_QLNN,0) as CDT_QLNN
                                , NVL(HT.CDT_BVMT,0) as CDT_BVMT, NVL(HT.CDT_BDXH,0) as CDT_BDXH, NVL(HT.CDT_VH,0) as CDT_VH, NVL(HT.CDT_KHCN,0) as CDT_KHCN
                                , NVL(HT.CDT_GD,0) as CDT_GD, NVL(HT.CDT_YT,0) as CDT_YT, NVL(HT.CDT_TDTT,0) as CDT_TDTT, NVL(HT.CDT_PT,0) as CDT_PT
                                , NVL(HT.DT_CDT_QP,0) as DT_CDT_QP, NVL(HT.DT_CDT_AN,0) as DT_CDT_AN, NVL(HT.DT_CDT_KH,0) as DT_CDT_KH, NVL(HT.DT_CDT_HDKT,0) as DT_CDT_HDKT, NVL(HT.DT_CDT_QLNN,0) as DT_CDT_QLNN
                                , NVL(HT.DT_CDT_BVMT,0) as DT_CDT_BVMT, NVL(HT.DT_CDT_BDXH,0) as DT_CDT_BDXH, NVL(HT.DT_CDT_VH,0) as DT_CDT_VH, NVL(HT.DT_CDT_KHCN,0) as DT_CDT_KHCN
                                , NVL(HT.DT_CDT_GD,0) as DT_CDT_GD, NVL(HT.DT_CDT_YT,0) as DT_CDT_YT, NVL(HT.DT_CDT_TDTT,0) as DT_CDT_TDTT, NVL(HT.DT_CDT_PT,0) as DT_CDT_PT
                                , NVL(HT.DT_CDT,0) as DT_CDT, NVL(HT.DT_CDT_01,0) as DT_CDT_01, NVL(HT.DT_CDT_02,0) as DT_CDT_02, NVL(HT.DT_CDT_03,0) as DT_CDT_03, NVL(HT.DT_CDT_06,0) as DT_CDT_06
                        FROM
                        ( SELECT QT.MA_CHUONG, QT.TEN_CHUONG, QT.MA_DVQHNS, QT.TEN_DVQHNS
                                , NVL(QT.CDT_QP,0) as CDT_QP, NVL(QT.CDT_AN,0) as CDT_AN, NVL(QT.CDT_KH,0) as CDT_KH, NVL(QT.CDT_HDKT,0) as CDT_HDKT, NVL(QT.CDT_HDKT_GT,0) as CDT_HDKT_GT
                                , NVL(QT.CDT_HDKT_NN,0) as CDT_HDKT_NN, NVL(QT.CDT_QLNN,0) as CDT_QLNN
                                , NVL(QT.CDT_BVMT,0) as CDT_BVMT, NVL(QT.CDT_BDXH,0) as CDT_BDXH, NVL(QT.CDT_VH,0) as CDT_VH, NVL(QT.CDT_KHCN,0) as CDT_KHCN
                                , NVL(QT.CDT_GD,0) as CDT_GD, NVL(QT.CDT_YT,0) as CDT_YT, NVL(QT.CDT_TDTT,0) as CDT_TDTT, NVL(QT.CDT_PT,0) as CDT_PT
                                , NVL(DT.DT_CDT_QP,0) as DT_CDT_QP, NVL(DT.DT_CDT_AN,0) as DT_CDT_AN, NVL(DT.DT_CDT_KH,0) as DT_CDT_KH, NVL(DT.DT_CDT_HDKT,0) as DT_CDT_HDKT
                                , NVL(DT.DT_CDT_QLNN,0) as DT_CDT_QLNN, NVL(DT.DT_CDT_BVMT,0) as DT_CDT_BVMT, NVL(DT.DT_CDT_BDXH,0) as DT_CDT_BDXH, NVL(DT.DT_CDT_VH,0) as DT_CDT_VH
                                , NVL(DT.DT_CDT_KHCN,0) as DT_CDT_KHCN, NVL(DT.DT_CDT_GD,0) as DT_CDT_GD, NVL(DT.DT_CDT_YT,0) as DT_CDT_YT, NVL(DT.DT_CDT_TDTT,0) as DT_CDT_TDTT
                                , NVL(DT.DT_CDT_PT,0) as DT_CDT_PT, NVL(DT.DT_CDT,0) as DT_CDT, NVL(DT.DT_CDT_01,0) as DT_CDT_01
                                , NVL(DT.DT_CDT_02,0) as DT_CDT_02, NVL(DT.DT_CDT_03,0) as DT_CDT_03, NVL(DT.DT_CDT_06,0) as DT_CDT_06
                                FROM
                        (SELECT A.MA_CHUONG AS MA_CHUONG, A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_QP ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_QP
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_AN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_AN
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_KH ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_KH
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_HDKT ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_HDKT
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_HDKT_GT ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_HDKT_GT
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_HDKT_NN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_HDKT_NN
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_QLNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_QLNN
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_BVMT ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_BVMT
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_BDXH ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_BDXH
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_VH ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_VH
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_KHCN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_KHCN
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_GD ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_GD
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_YT ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_YT
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_TDTT ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_TDTT
                                ,NVL(SUM (CASE WHEN ('|| CT_CDT_PT ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CDT_PT     
                         FROM BM54_ND31 A
                        WHERE A.NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')
                        AND A.NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')     
                        and A.NGAY_KET_SO <=TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                        and A.NGAY_KET_SO >=TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                             AND NOT A.MA_CHUONG LIKE ''000''
                            AND NOT A.MA_CAP like ''1'' ' || TEMP || P_CT ||' GROUP BY A.MA_CHUONG,A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS) QT  LEFT JOIN        
                          (SELECT A.MA_CHUONG AS MA_CHUONG, A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS      
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_QP ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_QP
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_AN ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_AN
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_KH ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_KH
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_HDKT ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_HDKT
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_QLNN ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_QLNN
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_BVMT ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_BVMT
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_BDXH ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_BDXH
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_VH ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_VH
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_KHCN ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_KHCN
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_GD ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_GD
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_YT ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_YT
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_TDTT ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_TDTT
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_PT ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_PT  
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_01 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_01
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_02 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_02
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_03 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_03
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_CDT_06 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_CDT_06
                                
                        FROM BM54_ND31 A
                        WHERE A.NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')
                        AND A.NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')     
                        and A.NGAY_KET_SO <=TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                        and A.NGAY_KET_SO >=TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                             AND NOT A.MA_CHUONG LIKE ''000''
                            AND NOT A.MA_CAP like ''1'' 
                         GROUP BY A.MA_CHUONG,A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS) DT ON QT.MA_CHUONG = DT.MA_CHUONG AND QT.MA_DVQHNS = DT.MA_DVQHNS
                            GROUP BY QT.MA_CHUONG, QT.TEN_CHUONG, QT.MA_DVQHNS, QT.TEN_DVQHNS
                                , QT.CDT_QP,QT.CDT_AN, QT.CDT_KH, QT.CDT_HDKT, QT.CDT_HDKT_GT
                                , QT.CDT_HDKT_NN, QT.CDT_QLNN, QT.CDT_BVMT, QT.CDT_BDXH, QT.CDT_VH, QT.CDT_KHCN
                                , QT.CDT_GD, QT.CDT_YT, QT.CDT_TDTT, QT.CDT_PT
                                , DT.DT_CDT_QP, DT.DT_CDT_AN, DT.DT_CDT_KH, DT.DT_CDT_HDKT
                                , DT.DT_CDT_QLNN, DT.DT_CDT_BVMT, DT.DT_CDT_BDXH, DT.DT_CDT_VH
                                , DT.DT_CDT_KHCN, DT.DT_CDT_GD, DT.DT_CDT_YT, DT.DT_CDT_TDTT
                                , DT.DT_CDT_PT, DT.DT_CDT, DT.DT_CDT_01
                                , DT.DT_CDT_02, DT.DT_CDT_03, DT.DT_CDT_06
                        ) HT 

                        WHERE 1=1 AND (HT.CDT_QP <> 0 OR HT.CDT_AN <> 0 OR HT.CDT_KH <> 0 OR HT.CDT_HDKT <> 0 OR HT.CDT_HDKT_GT<> 0 OR HT.CDT_HDKT_NN <> 0
                            OR HT.CDT_QLNN <> 0 OR HT.CDT_BVMT <> 0 OR HT.CDT_BDXH <> 0 OR HT.CDT_VH <>0 OR HT.CDT_KHCN <> 0 OR HT.CDT_GD <> 0 OR HT.CDT_YT <> 0 OR HT.CDT_TDTT <>0 OR HT.CDT_PT <> 0
                            OR HT.DT_CDT <> 0 OR HT.DT_CDT_01 <> 0 OR HT.DT_CDT_02 <> 0 OR HT.DT_CDT_03 <> 0 OR HT.DT_CDT_06 <> 0) ORDER BY HT.MA_CHUONG';
--   DBMS_OUTPUT.put_line (QUERY_STR); 
BEGIN
EXECUTE IMMEDIATE QUERY_STR;
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      --DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
END;    
END PHA_NS_BM55_ND31;