create or replace PROCEDURE "PHA_DTXD_MAU_01" (P_CONGTHUC VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE, DONVI_TIEN number, cur OUT SYS_REFCURSOR) 
AS
   P_CT VARCHAR2(32767);   
   P_SQL_INSERT NVARCHAR2(32767);
   QUERY_STR VARCHAR2(32767);
   QUERY_STR1 VARCHAR2(32767);
   QUERY_STR2 VARCHAR2(32767);
   QUERY_STR3 VARCHAR2(32767);
   QUERY_STR4 VARCHAR2(32767);
   QUERY_STR5 VARCHAR2(32767);
   QUERY_STR6 VARCHAR2(32767);
   QUERY_STR7 VARCHAR2(32767);
   NAM_TRUOC VARCHAR2(200);
   NAM_HIENTAI VARCHAR2(200);
   NAM_SAU VARCHAR2(200);
   BEGIN
        NAM_HIENTAI := TO_CHAR(TUNGAY_HL,'yyyy');
        NAM_TRUOC := REPLACE(TO_CHAR(TO_NUMBER(NAM_HIENTAI, '9999') - 1,'9999'),chr(32),'');
        NAM_SAU := REPLACE(TO_CHAR(TO_NUMBER(NAM_HIENTAI, '9999') + 1,'9999'),chr(32),'');
QUERY_STR:=' SELECT MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS,TEN_DVQHNS,SUM(DUTAMUNG_NT) AS DUTAMUNG_NT, SUM(HOANUNG) AS HOANUNG, SUM(KHVDT) AS KHVDT, SUM(TTKL) AS TTKL , SUM(VTUCTH) AS VTUCTH, SUM(KHVCSNS) AS KHVCSNS, SUM(KHVHB) AS KHVHB FROM (SELECT COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS FROM
        (SELECT COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS FROM
        (SELECT COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS FROM
        (SELECT COT567.MA_DVQHNS, COT567.MA_NGUON_NSNN, COT567.MA_CHUONG, COT567.DUTAMUNG_NT, COT567.HOANUNG, COT567.KHVDT, COT9.TTKL,COT567.TEN_DVQHNS FROM
        (SELECT COT56.MA_DVQHNS, COT56.MA_NGUON_NSNN, COT56.MA_CHUONG, COT56.DUTAMUNG_NT, COT56.HOANUNG, COT7.KHVDT,COT56.TEN_DVQHNS FROM
        (SELECT COT5.MA_DVQHNS, COT5.MA_NGUON_NSNN, COT5.MA_CHUONG, COT5.DUTAMUNG_NT, COT6.HOANUNG,COT5.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR),0) AS DUTAMUNG_NT, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT5
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT6 ON COT5.MA_DVQHNS = COT6.MA_DVQHNS AND COT5.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT5.MA_CHUONG = COT6.MA_CHUONG
        GROUP BY COT5.MA_DVQHNS, COT5.MA_NGUON_NSNN, COT5.MA_CHUONG, COT5.DUTAMUNG_NT, COT6.HOANUNG, COT5.TEN_DVQHNS) COT56
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN ,(NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHVDT, DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR-ACCOUNTED_CR) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 IN (''02'')
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 
        ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN, DK1.TEN_DVQHNS) COT7 ON COT56.MA_DVQHNS = COT7.MA_DVQHNS AND COT56.MA_NGUON_NSNN = COT7.MA_NGUON_NSNN AND COT56.MA_CHUONG = COT7.MA_CHUONG
        GROUP BY COT56.MA_DVQHNS, COT56.MA_NGUON_NSNN, COT56.MA_CHUONG, COT56.DUTAMUNG_NT, COT56.HOANUNG, COT7.KHVDT, COT56.TEN_DVQHNS) COT567
        
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS TTKL, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT9 
        ON COT567.MA_DVQHNS = COT9.MA_DVQHNS AND COT567.MA_NGUON_NSNN = COT9.MA_NGUON_NSNN AND COT567.MA_CHUONG = COT9.MA_CHUONG
        GROUP BY COT567.MA_DVQHNS, COT567.MA_NGUON_NSNN, COT567.MA_CHUONG, COT567.DUTAMUNG_NT, COT567.HOANUNG, COT567.KHVDT, COT9.TTKL, COT567.TEN_DVQHNS) COT5679
        
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR-ACCOUNTED_DR),0) AS VTUCTH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_SAU||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''|| '3112'||NAM_SAU||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT10
        ON COT5679.MA_DVQHNS = COT10.MA_DVQHNS AND COT5679.MA_NGUON_NSNN = COT10.MA_NGUON_NSNN AND COT5679.MA_CHUONG = COT10.MA_CHUONG 
        GROUP BY COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS) COT567910
        
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVCSNS, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS ) COT12 
        ON COT567910.MA_DVQHNS = COT12.MA_DVQHNS AND COT567910.MA_NGUON_NSNN = COT12.MA_NGUON_NSNN AND COT567910.MA_CHUONG = COT12.MA_CHUONG
        GROUP BY COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS) COT56791012
        
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVHB, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''9631'' AND ATTRIBUTE8 LIKE ''10''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT13
        ON COT56791012.MA_DVQHNS = COT13.MA_DVQHNS AND COT56791012.MA_NGUON_NSNN = COT13.MA_NGUON_NSNN AND COT56791012.MA_CHUONG = COT13.MA_CHUONG
        GROUP BY COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS
        ';
        QUERY_STR1:='
         UNION SELECT COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS FROM
        (SELECT COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS FROM
        (SELECT COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS FROM
        (SELECT COT567.MA_DVQHNS, COT567.MA_NGUON_NSNN, COT567.MA_CHUONG, COT567.DUTAMUNG_NT, COT567.HOANUNG, COT567.KHVDT, COT9.TTKL, COT567.TEN_DVQHNS FROM
        (SELECT COT56.MA_DVQHNS, COT56.MA_NGUON_NSNN, COT56.MA_CHUONG, COT56.DUTAMUNG_NT, COT56.HOANUNG, COT7.KHVDT, COT56.TEN_DVQHNS FROM
        (SELECT COT6.MA_DVQHNS, COT6.MA_NGUON_NSNN, COT6.MA_CHUONG, COT5.DUTAMUNG_NT, COT6.HOANUNG, COT6.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_CR),0) AS DUTAMUNG_NT, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS) COT5
        RIGHT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT6 ON COT5.MA_DVQHNS = COT6.MA_DVQHNS AND COT5.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT5.MA_CHUONG = COT6.MA_CHUONG
        GROUP BY COT6.MA_DVQHNS, COT6.MA_NGUON_NSNN, COT6.MA_CHUONG, COT5.DUTAMUNG_NT, COT6.HOANUNG, COT6.TEN_DVQHNS) COT56
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN ,(NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHVDT, DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR-ACCOUNTED_CR) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 IN (''02'')
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 
        ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN, DK1.TEN_DVQHNS) COT7 ON COT56.MA_DVQHNS = COT7.MA_DVQHNS AND COT56.MA_NGUON_NSNN = COT7.MA_NGUON_NSNN AND COT56.MA_CHUONG = COT7.MA_CHUONG
        GROUP BY COT56.MA_DVQHNS, COT56.MA_NGUON_NSNN, COT56.MA_CHUONG, COT56.DUTAMUNG_NT, COT56.HOANUNG, COT7.KHVDT, COT56.TEN_DVQHNS) COT567
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS TTKL, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT9 
        ON COT567.MA_DVQHNS = COT9.MA_DVQHNS AND COT567.MA_NGUON_NSNN = COT9.MA_NGUON_NSNN AND COT567.MA_CHUONG = COT9.MA_CHUONG
        GROUP BY COT567.MA_DVQHNS, COT567.MA_NGUON_NSNN, COT567.MA_CHUONG, COT567.DUTAMUNG_NT, COT567.HOANUNG, COT567.KHVDT, COT9.TTKL, COT567.TEN_DVQHNS) COT5679
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR-ACCOUNTED_DR),0) AS VTUCTH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_SAU||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''|| '3112'||NAM_SAU||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT10
        ON COT5679.MA_DVQHNS = COT10.MA_DVQHNS AND COT5679.MA_NGUON_NSNN = COT10.MA_NGUON_NSNN AND COT5679.MA_CHUONG = COT10.MA_CHUONG 
        GROUP BY COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS) COT567910
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVCSNS, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS ) COT12 
        ON COT567910.MA_DVQHNS = COT12.MA_DVQHNS AND COT567910.MA_NGUON_NSNN = COT12.MA_NGUON_NSNN AND COT567910.MA_CHUONG = COT12.MA_CHUONG
        GROUP BY COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS) COT56791012
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVHB, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''9631'' AND ATTRIBUTE8 LIKE ''10''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT13
        ON COT56791012.MA_DVQHNS = COT13.MA_DVQHNS AND COT56791012.MA_NGUON_NSNN = COT13.MA_NGUON_NSNN AND COT56791012.MA_CHUONG = COT13.MA_CHUONG
        GROUP BY COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS
         UNION
         SELECT COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS FROM
        (SELECT COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS FROM
        (SELECT COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS FROM
        (SELECT COT567.MA_DVQHNS, COT567.MA_NGUON_NSNN, COT567.MA_CHUONG, COT567.DUTAMUNG_NT, COT567.HOANUNG, COT567.KHVDT, COT9.TTKL, COT567.TEN_DVQHNS FROM
        (SELECT COT57.MA_DVQHNS, COT57.MA_NGUON_NSNN, COT57.MA_CHUONG,COT57.KHVDT,COT57.DUTAMUNG_NT, COT6.HOANUNG, COT57.TEN_DVQHNS FROM
        (SELECT COT7.MA_DVQHNS, COT7.MA_NGUON_NSNN, COT7.MA_CHUONG, COT5.DUTAMUNG_NT, COT7.KHVDT, COT7.TEN_DVQHNS FROM
        (SELECT DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN ,(NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHVDT, DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR-ACCOUNTED_CR) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 IN (''02'')
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 
        ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN, DK1.TEN_DVQHNS) COT7 LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_CR),0) AS DUTAMUNG_NT, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS) COT5 ON COT7.MA_DVQHNS = COT5.MA_DVQHNS AND COT7.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT7.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT7.MA_DVQHNS, COT7.MA_NGUON_NSNN, COT7.MA_CHUONG, COT5.DUTAMUNG_NT, COT7.KHVDT, COT7.TEN_DVQHNS) COT57
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT6 ON COT57.MA_DVQHNS = COT6.MA_DVQHNS AND COT57.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT57.MA_CHUONG = COT6.MA_CHUONG
        GROUP BY COT57.MA_DVQHNS, COT57.MA_NGUON_NSNN, COT57.MA_CHUONG,COT57.KHVDT,COT57.DUTAMUNG_NT, COT6.HOANUNG, COT57.TEN_DVQHNS) COT567
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS TTKL, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT9 
        ON COT567.MA_DVQHNS = COT9.MA_DVQHNS AND COT567.MA_NGUON_NSNN = COT9.MA_NGUON_NSNN AND COT567.MA_CHUONG = COT9.MA_CHUONG
        GROUP BY COT567.MA_DVQHNS, COT567.MA_NGUON_NSNN, COT567.MA_CHUONG, COT567.DUTAMUNG_NT, COT567.HOANUNG, COT567.KHVDT, COT9.TTKL, COT567.TEN_DVQHNS) COT5679
        
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR-ACCOUNTED_DR),0) AS VTUCTH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_SAU||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''|| '3112'||NAM_SAU||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT10
        ON COT5679.MA_DVQHNS = COT10.MA_DVQHNS AND COT5679.MA_NGUON_NSNN = COT10.MA_NGUON_NSNN AND COT5679.MA_CHUONG = COT10.MA_CHUONG 
        GROUP BY COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS) COT567910
        
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVCSNS, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS ) COT12 
        ON COT567910.MA_DVQHNS = COT12.MA_DVQHNS AND COT567910.MA_NGUON_NSNN = COT12.MA_NGUON_NSNN AND COT567910.MA_CHUONG = COT12.MA_CHUONG
        GROUP BY COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS) COT56791012
        
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVHB, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''9631'' AND ATTRIBUTE8 LIKE ''10''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT13
        ON COT56791012.MA_DVQHNS = COT13.MA_DVQHNS AND COT56791012.MA_NGUON_NSNN = COT13.MA_NGUON_NSNN AND COT56791012.MA_CHUONG = COT13.MA_CHUONG
        GROUP BY COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS';
        QUERY_STR2:='
        UNION
        SELECT COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS FROM
        (SELECT COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS FROM
        (SELECT COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS FROM
        (SELECT COT569.MA_DVQHNS, COT569.MA_NGUON_NSNN, COT569.MA_CHUONG, COT569.DUTAMUNG_NT, COT569.HOANUNG, COT7.KHVDT,COT569.TTKL, COT569.TEN_DVQHNS FROM
        (SELECT COT59.MA_DVQHNS, COT59.MA_NGUON_NSNN, COT59.MA_CHUONG, COT59.DUTAMUNG_NT, COT6.HOANUNG, COT59.TTKL, COT59.TEN_DVQHNS FROM
        (SELECT COT9.MA_DVQHNS, COT9.MA_NGUON_NSNN, COT9.MA_CHUONG, COT5.DUTAMUNG_NT, COT9.TTKL, COT9.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS TTKL, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT9 
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_CR),0) AS DUTAMUNG_NT, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS) COT5 ON COT9.MA_DVQHNS = COT5.MA_DVQHNS AND COT9.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT9.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT9.MA_DVQHNS, COT9.MA_NGUON_NSNN, COT9.MA_CHUONG, COT5.DUTAMUNG_NT, COT9.TTKL, COT9.TEN_DVQHNS) COT59
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT6 ON COT59.MA_DVQHNS = COT6.MA_DVQHNS AND COT59.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT59.MA_CHUONG = COT6.MA_CHUONG
        GROUP BY COT59.MA_DVQHNS, COT59.MA_NGUON_NSNN, COT59.MA_CHUONG, COT59.DUTAMUNG_NT, COT6.HOANUNG, COT59.TTKL, COT59.TEN_DVQHNS) COT569
        
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN ,(NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHVDT, DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR-ACCOUNTED_CR) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 IN (''02'')
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 
        ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN, DK1.TEN_DVQHNS) COT7 ON COT569.MA_DVQHNS = COT7.MA_DVQHNS AND COT569.MA_NGUON_NSNN = COT7.MA_NGUON_NSNN AND COT569.MA_CHUONG = COT7.MA_CHUONG
        GROUP BY COT569.MA_DVQHNS, COT569.MA_NGUON_NSNN, COT569.MA_CHUONG, COT569.DUTAMUNG_NT, COT569.HOANUNG, COT7.KHVDT,COT569.TTKL, COT569.TEN_DVQHNS) COT5679
        
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR-ACCOUNTED_DR),0) AS VTUCTH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_SAU||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''|| '3112'||NAM_SAU||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT10
        ON COT5679.MA_DVQHNS = COT10.MA_DVQHNS AND COT5679.MA_NGUON_NSNN = COT10.MA_NGUON_NSNN AND COT5679.MA_CHUONG = COT10.MA_CHUONG 
        GROUP BY COT5679.MA_DVQHNS, COT5679.MA_NGUON_NSNN, COT5679.MA_CHUONG, COT5679.DUTAMUNG_NT, COT5679.HOANUNG, COT5679.KHVDT, COT5679.TTKL, COT10.VTUCTH, COT5679.TEN_DVQHNS) COT567910
        
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVCSNS, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS ) COT12 
        ON COT567910.MA_DVQHNS = COT12.MA_DVQHNS AND COT567910.MA_NGUON_NSNN = COT12.MA_NGUON_NSNN AND COT567910.MA_CHUONG = COT12.MA_CHUONG
        GROUP BY COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS) COT56791012
        
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVHB, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''9631'' AND ATTRIBUTE8 LIKE ''10''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT13
        ON COT56791012.MA_DVQHNS = COT13.MA_DVQHNS AND COT56791012.MA_NGUON_NSNN = COT13.MA_NGUON_NSNN AND COT56791012.MA_CHUONG = COT13.MA_CHUONG
        GROUP BY COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS';
        QUERY_STR3:='
        UNION
        SELECT COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS FROM
        (SELECT COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS FROM
        (SELECT COT56710.MA_DVQHNS, COT56710.MA_NGUON_NSNN, COT56710.MA_CHUONG, COT56710.DUTAMUNG_NT, COT56710.HOANUNG, COT56710.VTUCTH, COT56710.KHVDT, COT9.TTKL, COT56710.TEN_DVQHNS FROM
        (SELECT COT5610.MA_DVQHNS, COT5610.MA_NGUON_NSNN, COT5610.MA_CHUONG, COT5610.DUTAMUNG_NT, COT5610.VTUCTH, COT5610.TEN_DVQHNS,COT5610.HOANUNG, COT7.KHVDT FROM
        (SELECT COT510.MA_DVQHNS, COT510.MA_NGUON_NSNN, COT510.MA_CHUONG, COT510.DUTAMUNG_NT, COT510.VTUCTH, COT510.TEN_DVQHNS,COT6.HOANUNG FROM
        (SELECT COT10.MA_DVQHNS, COT10.MA_NGUON_NSNN, COT10.MA_CHUONG, COT5.DUTAMUNG_NT, COT10.VTUCTH, COT10.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR-ACCOUNTED_DR),0) AS VTUCTH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_SAU||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''|| '3112'||NAM_SAU||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT10
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_CR),0) AS DUTAMUNG_NT, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS) COT5 ON COT10.MA_DVQHNS = COT5.MA_DVQHNS AND COT10.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT10.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT10.MA_DVQHNS, COT10.MA_NGUON_NSNN, COT10.MA_CHUONG, COT5.DUTAMUNG_NT, COT10.VTUCTH, COT10.TEN_DVQHNS) COT510
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT6 ON COT510.MA_DVQHNS = COT6.MA_DVQHNS AND COT510.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT510.MA_CHUONG = COT6.MA_CHUONG
        GROUP BY COT510.MA_DVQHNS, COT510.MA_NGUON_NSNN, COT510.MA_CHUONG, COT510.DUTAMUNG_NT, COT510.VTUCTH, COT510.TEN_DVQHNS,COT6.HOANUNG) COT5610
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN ,(NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHVDT, DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR-ACCOUNTED_CR) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 IN (''02'')
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 
        ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN, DK1.TEN_DVQHNS) COT7 ON COT5610.MA_DVQHNS = COT7.MA_DVQHNS AND COT5610.MA_NGUON_NSNN = COT7.MA_NGUON_NSNN AND COT5610.MA_CHUONG = COT7.MA_CHUONG
        GROUP BY COT5610.MA_DVQHNS, COT5610.MA_NGUON_NSNN, COT5610.MA_CHUONG, COT5610.DUTAMUNG_NT, COT5610.VTUCTH, COT5610.TEN_DVQHNS,COT5610.HOANUNG, COT7.KHVDT) COT56710
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS TTKL, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT9 
        ON COT56710.MA_DVQHNS = COT9.MA_DVQHNS AND COT56710.MA_NGUON_NSNN = COT9.MA_NGUON_NSNN AND COT56710.MA_CHUONG = COT9.MA_CHUONG
        GROUP BY COT56710.MA_DVQHNS, COT56710.MA_NGUON_NSNN, COT56710.MA_CHUONG, COT56710.DUTAMUNG_NT, COT56710.HOANUNG, COT56710.VTUCTH, COT56710.KHVDT, COT9.TTKL, COT56710.TEN_DVQHNS) COT567910
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVCSNS, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT12 
        ON COT567910.MA_DVQHNS = COT12.MA_DVQHNS AND COT567910.MA_NGUON_NSNN = COT12.MA_NGUON_NSNN AND COT567910.MA_CHUONG = COT12.MA_CHUONG
        GROUP BY COT567910.MA_DVQHNS, COT567910.MA_NGUON_NSNN, COT567910.MA_CHUONG, COT567910.DUTAMUNG_NT, COT567910.HOANUNG, COT567910.KHVDT, COT567910.TTKL, COT567910.VTUCTH, COT12.KHVCSNS, COT567910.TEN_DVQHNS) COT56791012
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVHB, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''9631'' AND ATTRIBUTE8 LIKE ''10''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT13
        ON COT56791012.MA_DVQHNS = COT13.MA_DVQHNS AND COT56791012.MA_NGUON_NSNN = COT13.MA_NGUON_NSNN AND COT56791012.MA_CHUONG = COT13.MA_CHUONG
        GROUP BY COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS';
        QUERY_STR4:='
        UNION
       SELECT COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS FROM
        (SELECT COT567912.MA_DVQHNS, COT567912.MA_NGUON_NSNN, COT567912.MA_CHUONG, COT567912.DUTAMUNG_NT, COT567912.HOANUNG, COT567912.KHVDT, COT567912.TTKL,COT567912.KHVCSNS, COT10.VTUCTH, COT567912.TEN_DVQHNS FROM
        (SELECT COT56712.MA_DVQHNS, COT56712.MA_NGUON_NSNN, COT56712.MA_CHUONG, COT56712.DUTAMUNG_NT, COT56712.HOANUNG, COT56712.KHVDT,COT56712.KHVCSNS, COT9.TTKL, COT56712.TEN_DVQHNS FROM
        (SELECT COT5612.MA_DVQHNS, COT5612.MA_NGUON_NSNN, COT5612.MA_CHUONG, COT5612.DUTAMUNG_NT, COT5612.HOANUNG,COT5612.KHVCSNS, COT7.KHVDT, COT5612.TEN_DVQHNS FROM
        (SELECT COT512.MA_DVQHNS, COT512.MA_NGUON_NSNN, COT512.MA_CHUONG, COT512.DUTAMUNG_NT,COT512.KHVCSNS, COT6.HOANUNG, COT512.TEN_DVQHNS FROM
        (SELECT COT12.MA_DVQHNS, COT12.MA_NGUON_NSNN, COT12.MA_CHUONG, COT5.DUTAMUNG_NT, COT12.KHVCSNS, COT12.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVCSNS, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT12 
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_CR),0) AS DUTAMUNG_NT, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS) COT5 ON COT12.MA_DVQHNS = COT5.MA_DVQHNS AND COT12.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT12.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT12.MA_DVQHNS, COT12.MA_NGUON_NSNN, COT12.MA_CHUONG, COT5.DUTAMUNG_NT, COT12.KHVCSNS, COT12.TEN_DVQHNS) COT512
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT6 ON COT512.MA_DVQHNS = COT6.MA_DVQHNS AND COT512.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT512.MA_CHUONG = COT6.MA_CHUONG
        GROUP BY COT512.MA_DVQHNS, COT512.MA_NGUON_NSNN, COT512.MA_CHUONG, COT512.DUTAMUNG_NT,COT512.KHVCSNS, COT6.HOANUNG, COT512.TEN_DVQHNS) COT5612
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN ,(NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHVDT, DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR-ACCOUNTED_CR) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 IN (''02'')
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 
        ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN, DK1.TEN_DVQHNS) COT7 ON COT5612.MA_DVQHNS = COT7.MA_DVQHNS AND COT5612.MA_NGUON_NSNN = COT7.MA_NGUON_NSNN AND COT5612.MA_CHUONG = COT7.MA_CHUONG
        GROUP BY COT5612.MA_DVQHNS, COT5612.MA_NGUON_NSNN, COT5612.MA_CHUONG, COT5612.DUTAMUNG_NT, COT5612.HOANUNG,COT5612.KHVCSNS, COT7.KHVDT, COT5612.TEN_DVQHNS) COT56712
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS TTKL, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT9 
        ON COT56712.MA_DVQHNS = COT9.MA_DVQHNS AND COT56712.MA_NGUON_NSNN = COT9.MA_NGUON_NSNN AND COT56712.MA_CHUONG = COT9.MA_CHUONG
        GROUP BY COT56712.MA_DVQHNS, COT56712.MA_NGUON_NSNN, COT56712.MA_CHUONG, COT56712.DUTAMUNG_NT, COT56712.HOANUNG, COT56712.KHVDT,COT56712.KHVCSNS, COT9.TTKL, COT56712.TEN_DVQHNS) COT567912
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR-ACCOUNTED_DR),0) AS VTUCTH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_SAU||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''|| '3112'||NAM_SAU||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT10
        ON COT567912.MA_DVQHNS = COT10.MA_DVQHNS AND COT567912.MA_NGUON_NSNN = COT10.MA_NGUON_NSNN AND COT567912.MA_CHUONG = COT10.MA_CHUONG 
        GROUP BY COT567912.MA_DVQHNS, COT567912.MA_NGUON_NSNN, COT567912.MA_CHUONG, COT567912.DUTAMUNG_NT, COT567912.HOANUNG, COT567912.KHVDT, COT567912.TTKL,COT567912.KHVCSNS, COT10.VTUCTH, COT567912.TEN_DVQHNS) COT56791012
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVHB, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''9631'' AND ATTRIBUTE8 LIKE ''10''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT13
        ON COT56791012.MA_DVQHNS = COT13.MA_DVQHNS AND COT56791012.MA_NGUON_NSNN = COT13.MA_NGUON_NSNN AND COT56791012.MA_CHUONG = COT13.MA_CHUONG
        GROUP BY COT56791012.MA_DVQHNS, COT56791012.MA_NGUON_NSNN, COT56791012.MA_CHUONG, COT56791012.DUTAMUNG_NT, COT56791012.HOANUNG, COT56791012.KHVDT, COT56791012.TTKL, COT56791012.VTUCTH, COT56791012.KHVCSNS, COT13.KHVHB, COT56791012.TEN_DVQHNS';
        QUERY_STR5:='
        UNION
        SELECT COT56791013.MA_DVQHNS, COT56791013.MA_NGUON_NSNN, COT56791013.MA_CHUONG, COT56791013.DUTAMUNG_NT, COT56791013.HOANUNG, COT56791013.KHVHB, COT56791013.KHVDT, COT56791013.TTKL, COT56791013.VTUCTH, COT12.KHVCSNS, COT56791013.TEN_DVQHNS FROM
        (SELECT COT567913.MA_DVQHNS, COT567913.MA_NGUON_NSNN, COT567913.MA_CHUONG, COT567913.DUTAMUNG_NT, COT567913.HOANUNG, COT567913.KHVHB, COT567913.KHVDT, COT567913.TTKL, COT10.VTUCTH, COT567913.TEN_DVQHNS FROM
        (SELECT COT56713.MA_DVQHNS, COT56713.MA_NGUON_NSNN, COT56713.MA_CHUONG, COT56713.DUTAMUNG_NT, COT56713.HOANUNG, COT56713.KHVHB, COT56713.KHVDT, COT9.TTKL, COT56713.TEN_DVQHNS FROM
        (SELECT COT5613.MA_DVQHNS, COT5613.MA_NGUON_NSNN, COT5613.MA_CHUONG, COT5613.DUTAMUNG_NT, COT5613.HOANUNG, COT5613.KHVHB, COT7.KHVDT, COT5613.TEN_DVQHNS FROM
        (SELECT COT513.MA_DVQHNS, COT513.MA_NGUON_NSNN, COT513.MA_CHUONG, COT513.DUTAMUNG_NT, COT6.HOANUNG, COT513.KHVHB, COT513.TEN_DVQHNS FROM
        (SELECT COT13.MA_DVQHNS, COT13.MA_NGUON_NSNN, COT13.MA_CHUONG, COT5.DUTAMUNG_NT, COT13.KHVHB, COT13.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVHB, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''9631'' AND ATTRIBUTE8 LIKE ''10''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT13
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_CR),0) AS DUTAMUNG_NT, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS) COT5 ON COT13.MA_DVQHNS = COT5.MA_DVQHNS AND COT13.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT13.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT13.MA_DVQHNS, COT13.MA_NGUON_NSNN, COT13.MA_CHUONG, COT5.DUTAMUNG_NT, COT13.KHVHB, COT13.TEN_DVQHNS) COT513
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS,MA_NGUON_NSNN,MA_CHUONG,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT6 ON COT513.MA_DVQHNS = COT6.MA_DVQHNS AND COT513.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT513.MA_CHUONG = COT6.MA_CHUONG
        GROUP BY COT513.MA_DVQHNS, COT513.MA_NGUON_NSNN, COT513.MA_CHUONG, COT513.DUTAMUNG_NT, COT6.HOANUNG, COT513.KHVHB, COT513.TEN_DVQHNS) COT5613
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN ,(NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHVDT, DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR-ACCOUNTED_CR) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,SUM(ACCOUNTED_DR) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 IN (''02'')
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 
        ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_CHUONG, DK1.MA_NGUON_NSNN, DK1.TEN_DVQHNS) COT7 ON COT5613.MA_DVQHNS = COT7.MA_DVQHNS AND COT5613.MA_NGUON_NSNN = COT7.MA_NGUON_NSNN AND COT5613.MA_CHUONG = COT7.MA_CHUONG
        GROUP BY COT5613.MA_DVQHNS, COT5613.MA_NGUON_NSNN, COT5613.MA_CHUONG, COT5613.DUTAMUNG_NT, COT5613.HOANUNG, COT5613.KHVHB, COT7.KHVDT, COT5613.TEN_DVQHNS) COT56713
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS TTKL, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT9 
        ON COT56713.MA_DVQHNS = COT9.MA_DVQHNS AND COT56713.MA_NGUON_NSNN = COT9.MA_NGUON_NSNN AND COT56713.MA_CHUONG = COT9.MA_CHUONG
        GROUP BY COT56713.MA_DVQHNS, COT56713.MA_NGUON_NSNN, COT56713.MA_CHUONG, COT56713.DUTAMUNG_NT, COT56713.HOANUNG, COT56713.KHVHB, COT56713.KHVDT, COT9.TTKL, COT56713.TEN_DVQHNS) COT567913
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_CR-ACCOUNTED_DR),0) AS VTUCTH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_SAU||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''|| '3112'||NAM_SAU||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT10
        ON COT567913.MA_DVQHNS = COT10.MA_DVQHNS AND COT567913.MA_NGUON_NSNN = COT10.MA_NGUON_NSNN AND COT567913.MA_CHUONG = COT10.MA_CHUONG 
        GROUP BY COT567913.MA_DVQHNS, COT567913.MA_NGUON_NSNN, COT567913.MA_CHUONG, COT567913.DUTAMUNG_NT, COT567913.HOANUNG, COT567913.KHVHB, COT567913.KHVDT, COT567913.TTKL, COT10.VTUCTH, COT567913.TEN_DVQHNS) COT56791013
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN , NVL(SUM(ACCOUNTED_DR),0) AS KHVCSNS, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT12 
        ON COT56791013.MA_DVQHNS = COT12.MA_DVQHNS AND COT56791013.MA_NGUON_NSNN = COT12.MA_NGUON_NSNN AND COT56791013.MA_CHUONG = COT12.MA_CHUONG
        GROUP BY COT56791013.MA_DVQHNS, COT56791013.MA_NGUON_NSNN, COT56791013.MA_CHUONG, COT56791013.DUTAMUNG_NT, COT56791013.HOANUNG, COT56791013.KHVHB, COT56791013.KHVDT, COT56791013.TTKL, COT56791013.VTUCTH, COT12.KHVCSNS, COT56791013.TEN_DVQHNS) 
        WHERE MA_DVQHNS LIKE ''7%'' AND MA_CHUONG BETWEEN ''405'' AND ''599''
        GROUP BY MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS
        ';
        
        DBMS_OUTPUT.ENABLE (buffer_size => NULL);
      DBMS_OUTPUT.put_line (QUERY_STR5 );
BEGIN


OPEN cur FOR QUERY_STR||QUERY_STR1||QUERY_STR2||QUERY_STR3||QUERY_STR4||QUERY_STR5;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
    DBMS_OUTPUT.ENABLE (buffer_size => NULL);
      DBMS_OUTPUT.put_line (SQLERRM); 
END;    
END PHA_DTXD_MAU_01;