create or replace PROCEDURE PHA_HCSN_MAU_08 (P_CONGTHUC VARCHAR2,NAM_HL VARCHAR2,DONVI_TIEN number, cur OUT SYS_REFCURSOR) AS 
    QUERY_STR  VARCHAR2(32767); 
    P_SQL_INSERT VARCHAR2(32767);
    MA_TIEUMUC VARCHAR2(1000);
    MA_MUC1 VARCHAR2(1000);
    MA_MUC2 VARCHAR2(1000);
    MA_TIEUMUC1 VARCHAR2(1000);
    P_CT VARCHAR2(32767);
BEGIN
    MA_TIEUMUC := '''6001'',''6002'',''6003'',''6099'',''6049'',''6051''';
    MA_MUC1:= '''6100''';
    MA_MUC2:= '''6300''';
    MA_TIEUMUC1:='''6104'',''6105'',''6106''';
    IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
        select STC_PA_SYS.FNC_CONVERT_FORMULA_HCSN (P_CONGTHUC) INTO P_CT from dual;
        P_SQL_INSERT:= ' '||P_SQL_INSERT ||' AND '||P_CT;
        END IF;
    --(NVL((SELECT NVL(SUM(GIA_TRI_HACH_TOAN),0) FROM PHA_HACHTOAN_CHI WHERE MA_CHUONG = A.MA_CHUONG AND MA_DVQHNS = A.MA_DVQHNS AND MA_TIEUMUC IN ('|| MA_TIEUMUC ||')),0)/NVL('|| DONVI_TIEN ||',1)) AS LUONG_THEO_NGACH_BAC,
    --(NVL((SELECT NVL(SUM(GIA_TRI_HACH_TOAN),0) FROM PHA_HACHTOAN_CHI WHERE MA_CHUONG = A.MA_CHUONG AND MA_DVQHNS = A.MA_DVQHNS AND MA_MUC LIKE (''6100'') AND NOT MA_TIEUMUC = ''6104'' AND NOT MA_TIEUMUC = ''6105'' AND NOT MA_TIEUMUC = ''6106''),0)/NVL('|| DONVI_TIEN ||',1)) AS KHOAN_PC,
    --(NVL((SELECT NVL(SUM(GIA_TRI_HACH_TOAN),0) FROM PHA_HACHTOAN_CHI WHERE MA_CHUONG = A.MA_CHUONG AND MA_DVQHNS = A.MA_DVQHNS AND MA_MUC LIKE (''6300'')),0)/NVL('|| DONVI_TIEN ||',1)) AS KHOAN_DONG_GOP 
    QUERY_STR:='SELECT  A.MA_CHUONG  AS MA_CHUONG,
                        A.MA_DVQHNS  AS MA_DVQHNS,
                        B.TEN_DVQHNS AS TEN_DVQHNS,
                        SUM (CASE WHEN (A.MA_TIEUMUC IN ('||MA_TIEUMUC||')) THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS LUONG_THEO_NGACH_BAC,
                        SUM (CASE WHEN (A.MA_MUC ='||MA_MUC1||' AND NOT A.MA_TIEUMUC IN ('||MA_TIEUMUC1||')) THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS KHOAN_PC,
                        SUM (CASE WHEN (A.MA_MUC ='||MA_MUC2||') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS KHOAN_DONG_GOP
                FROM PHA_HACHTOAN_CHI A INNER JOIN SYS_DVQHNS B ON A.MA_DVQHNS = B.MA_DVQHNS
                WHERE A.MA_CHUONG BETWEEN ''402'' AND ''599'' AND A.MA_DVQHNS like ''1%'' 
                      AND A.NGAY_HIEU_LUC >= TO_DATE ('''|| '0101' || NAM_HL  ||''', ''ddMMyyyy'')
                      AND A.NGAY_HIEU_LUC <= TO_DATE ('''|| '3112' || NAM_HL  ||''', ''ddMMyyyy'') '||P_SQL_INSERT||'  
                      GROUP BY A.MA_CHUONG,A.MA_DVQHNS, B.TEN_DVQHNS 
                      ORDER BY A.MA_CHUONG';
DBMS_OUTPUT.put_line ('<your message>' || QUERY_STR);                      
BEGIN
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END;
END PHA_HCSN_MAU_08;