create or replace procedure PHA_HCSN_MAU_03(NAM_HL VARCHAR2, DONVI_TIEN number, cur OUT SYS_REFCURSOR) as
   QUERY_STR  VARCHAR2(32767); 

   MA_TKTN_TC_DT_GIAO VARCHAR2(50);
   MA_TKTN_KTC_DT_GIAO VARCHAR2(50);
   MA_TKTN_TC_THUCHIEN_DT VARCHAR2(50);
   MA_TKTN_KTC_THUCHIEN_DT VARCHAR2(50);     

   MA_NGUON_NSNN_12 VARCHAR2(50);
   MA_NGUON_NSNN_13 VARCHAR2(50);
   MA_NGUON_NSNN_14 VARCHAR2(50);
   MA_NGUON_NSNN_16 VARCHAR2(50);
   MA_NGUON_NSNN_21 VARCHAR2(50);       

    BEGIN
        MA_TKTN_TC_DT_GIAO := '''9523''';
        MA_TKTN_KTC_DT_GIAO := '''9527''';        
        MA_TKTN_TC_THUCHIEN_DT := '''8113''';
        MA_TKTN_KTC_THUCHIEN_DT := '''8123''';

        MA_NGUON_NSNN_12 := '12';
        MA_NGUON_NSNN_13 := '13';
        MA_NGUON_NSNN_14 := '14';
        MA_NGUON_NSNN_16 := '16';
        MA_NGUON_NSNN_21 := '21';        

       QUERY_STR:='select  A.MA_CHUONG AS MA_CHUONG,A.MA_DVQHNS AS MA_DVQHNS, B.TEN_DVQHNS AS TEN_DVQHNS,A.MA_NVC, A.MA_LOAI, A.MA_NGANHKT as MA_KHOAN,
                                                
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_DT_GIAO ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_13 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_DT_GIAO_TC13,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_DT_GIAO ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_14 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_DT_GIAO_TC14,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_DT_GIAO ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_16 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_DT_GIAO_TC16,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_DT_GIAO ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_21 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_DT_GIAO_TC21,
            
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_KTC_DT_GIAO ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_12 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_DT_GIAO_KTC12,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_KTC_DT_GIAO ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_14 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_DT_GIAO_KTC14,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_KTC_DT_GIAO ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_16 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_DT_GIAO_KTC16,
                        
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_THUCHIEN_DT ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_13 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_THUCHIEN_DT_TC13,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_THUCHIEN_DT ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_14 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_THUCHIEN_DT_TC14,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_THUCHIEN_DT ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_16 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_THUCHIEN_DT_TC16,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_TC_THUCHIEN_DT ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_21 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_THUCHIEN_DT_TC21,
            
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_KTC_THUCHIEN_DT ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_12 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_THUCHIEN_DT_KTC12,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_KTC_THUCHIEN_DT ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_14 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_THUCHIEN_DT_KTC14,
            SUM (CASE WHEN (A.MA_TKTN in ('|| MA_TKTN_KTC_THUCHIEN_DT ||') AND A.MA_NGUON_NSNN = '''|| MA_NGUON_NSNN_16 ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_THUCHIEN_DT_KTC16

            FROM PHA_DUTOAN A inner join SYS_DVQHNS B on B.MA_DVQHNS = A.MA_DVQHNS
            WHERE A.MA_NVC is not null AND A.MA_DVQHNS like ''1%''
            AND A.NGAY_HIEU_LUC >= TO_DATE ('''|| '0101' || NAM_HL  ||''', ''ddMMyyyy'')
            AND A.NGAY_HIEU_LUC <= TO_DATE ('''|| '3112' || NAM_HL  ||''', ''ddMMyyyy'')
            group by A.MA_CHUONG,A.MA_DVQHNS, B.TEN_DVQHNS,A.MA_NVC, A.MA_LOAI, A.MA_NGANHKT
            order by A.MA_CHUONG';

   DBMS_OUTPUT.put_line (QUERY_STR);
BEGIN
 -- EXECUTE IMMEDIATE QUERY_STR;
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END;    
END PHA_HCSN_MAU_03;
 