create or replace procedure PHA_HCSN_MAU_01(NAM_HL VARCHAR2, DONVI_TIEN number, cur OUT SYS_REFCURSOR) as
   QUERY_STR  VARCHAR2(32767); 
   MA_TKTN_UB_GIAO VARCHAR2(50);
   MA_CAPMLNS_UB_GIAO VARCHAR2(50);
   MA_TKTN_PHANBO VARCHAR2(50);
   MA_CAPMLNS_PHANBO VARCHAR2(50);
   MA_LDT VARCHAR2(50);

    BEGIN
        MA_TKTN_UB_GIAO := '''9213''';
        MA_CAPMLNS_UB_GIAO := '1';
        MA_TKTN_PHANBO := '''9523'',''9527''';
        MA_CAPMLNS_PHANBO := '4';
        MA_LDT := '01';

      -- SOTIEN_UB_GIAO: lấy MA_LDT = 01; MA_TKTN = 9213; MA_CAPMLNS = 1
      -- SOTIEN_PHANBO: lấy MA_LDT = 01; MA_TKTN = 9523, 9527; MA_CAPMLNS=4
       QUERY_STR:='select  A.MA_CHUONG AS MA_CHUONG,A.MA_DVQHNS AS MA_DVQHNS, B.TEN_DVQHNS AS TEN_DVQHNS,A.MA_NVC,
                   
            SUM (CASE WHEN (A.MA_TKTN IN('|| MA_TKTN_UB_GIAO ||') AND A.ATTRIBUTE8 ='||MA_LDT||' AND A.MA_CAPMLNS='''|| MA_CAPMLNS_UB_GIAO ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_UB_GIAO,
            SUM (CASE WHEN (A.MA_TKTN IN('|| MA_TKTN_PHANBO ||') AND A.ATTRIBUTE8 ='||MA_LDT||' AND A.MA_CAPMLNS='''|| MA_CAPMLNS_PHANBO ||''') THEN GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS SOTIEN_PHANBO
            
            from PHA_DUTOAN A left join SYS_DVQHNS B on A.MA_DVQHNS = B.MA_DVQHNS 
            where 1=1 and A.MA_NVC is not null
            AND A.NGAY_HIEU_LUC >= TO_DATE ('''|| '0101' || NAM_HL  ||''', ''ddMMyyyy'')
            AND A.NGAY_HIEU_LUC <= TO_DATE ('''|| '3112' || NAM_HL  ||''', ''ddMMyyyy'')
            group by A.MA_CHUONG,A.MA_DVQHNS, B.TEN_DVQHNS,A.MA_NGANHKT,A.MA_NVC
            order by A.MA_CHUONG,A.MA_DVQHNS, B.TEN_DVQHNS,A.MA_NGANHKT,A.MA_NVC';

   DBMS_OUTPUT.put_line (QUERY_STR);
BEGIN
    EXECUTE IMMEDIATE QUERY_STR;
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END;    
END PHA_HCSN_MAU_01;
 