create or replace PROCEDURE "PHA_THDT_CHI_DTPT" (P_CONGTHUC VARCHAR2, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE,TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, DONVI_TIEN number, cur OUT SYS_REFCURSOR) as
   QUERY_STR  VARCHAR2(32767); 
   P_CT VARCHAR2(32767);   
   P_SQL_INSERT VARCHAR2(32767);

   MA_TKTN VARCHAR2(50);

   ATTRIBUTE8_1 VARCHAR2(50);
   ATTRIBUTE8_2 VARCHAR2(50);
   ATTRIBUTE8_3 VARCHAR2(50);
   ATTRIBUTE8_6 VARCHAR2(50);

   MA_NGUON_NSNN_41 VARCHAR2(50);
   MA_NGUON_NSNN_42 VARCHAR2(50);
   MA_NGUON_NSNN_43 VARCHAR2(50);
   MA_NGUON_NSNN_49 VARCHAR2(50);
   MA_NGUON_NSNN_53 VARCHAR2(50);

    BEGIN
        MA_TKTN := '''9552''';
        
        ATTRIBUTE8_1 := '''01''';
        ATTRIBUTE8_2 := '''02''';
        ATTRIBUTE8_3 := '''03''';
        ATTRIBUTE8_6 := '''06''';

        MA_NGUON_NSNN_41 := '41';
        MA_NGUON_NSNN_42 := '42';
        MA_NGUON_NSNN_43 := '43';
        MA_NGUON_NSNN_49 := '49';
        MA_NGUON_NSNN_53 := '53';

    IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
        select STC_PA_SYS.FNC_CONVERT_FORMULA_HCSN(P_CONGTHUC) INTO P_CT from dual;
        P_SQL_INSERT:= ' '||P_SQL_INSERT ||' and '||P_CT;
        END IF;


   QUERY_STR:='select  A.MA_CHUONG AS MA_CHUONG, A.TEN_CHUONG as TEN_CHUONG ,A.MA_DVQHNS AS MA_DVQHNS, A.TEN_DVQHNS AS TEN_DVQHNS,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_41||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_6||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_NAMTRUOC_41,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_42||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_6||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_NAMTRUOC_42,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_43||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_6||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_NAMTRUOC_43,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_49||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_6||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_NAMTRUOC_49,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_53||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_6||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_NAMTRUOC_53,
            
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_41||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_1||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DAUNAM_41,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_42||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_1||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DAUNAM_42,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_43||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_1||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DAUNAM_43,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_49||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_1||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DAUNAM_49,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_53||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_1||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DAUNAM_53,

            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_41||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_2||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_BOSUNG_41,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_42||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_2||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_BOSUNG_42,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_43||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_2||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_BOSUNG_43,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_49||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_2||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_BOSUNG_49,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_53||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_2||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_BOSUNG_53,

            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_41||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_3||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DIEUCHINH_41,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_42||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_3||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DIEUCHINH_42,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_43||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_3||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DIEUCHINH_43,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_49||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_3||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DIEUCHINH_49,
            SUM (CASE WHEN (A.MA_TKTN='||MA_TKTN||' AND A.MA_NGUON_NSNN='||MA_NGUON_NSNN_53||' AND A.ATTRIBUTE8 like '||ATTRIBUTE8_3||' ) THEN (A.ACCOUNTED_DR - A.ACCOUNTED_CR)/NVL('|| DONVI_TIEN ||',1) ELSE 0 END) AS DT_DIEUCHINH_53

            from PHA_DUTOAN A
            where A.NGAY_HIEU_LUC >= TO_DATE ('''|| to_char(TUNGAY_HL,'ddMMyyyy') ||''', ''ddMMyyyy'')
            AND A.NGAY_HIEU_LUC <= TO_DATE ('''|| to_char(DENNGAY_HL,'ddMMyyyy') ||''', ''ddMMyyyy'')
            AND A.NGAY_KET_SO >= TO_DATE ('''|| to_char(TUNGAY_KS,'ddMMyyyy') ||''', ''ddMMyyyy'')
            AND A.NGAY_KET_SO <= TO_DATE ('''|| to_char(DENNGAY_KS,'ddMMyyyy') ||''', ''ddMMyyyy'')
            '||P_SQL_INSERT||'
            group by A.MA_CHUONG,A.TEN_CHUONG,A.MA_DVQHNS, A.TEN_DVQHNS
            order by A.MA_CHUONG';

   DBMS_OUTPUT.put_line (QUERY_STR);
BEGIN
EXECUTE IMMEDIATE QUERY_STR;
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END;    
END PHA_THDT_CHI_DTPT;