create or replace PROCEDURE PHC_PRC_SONGANSACH(P_CONGTHUC IN VARCHAR,P_TUNGAYHL IN DATE, P_DENNGAYHL IN DATE, P_USERNAME IN VARCHAR,P_TAIKHOAN IN VARCHAR,P_USELIKE IN NUMBER,CURSOR_RESULT OUT SYS_REFCURSOR)
IS
	-- Store chạy cho các báo cáo: Sổ quỹ tiền mặt(S02A_X),Sổ nhật ký thu chi quỹ tiền mặt(S02B_X),Sổ phải thu(S08_X), Sổ phải trả(S09_X), Sổ tiền gửi kho bạc(S03_X)
    P_TU_THANG VARCHAR2(2) := TO_NUMBER(TO_CHAR(TO_DATE(P_TUNGAYHL,'DD/MM/YY'),'MM'));
    P_DEN_THANG VARCHAR2(2) := TO_NUMBER(TO_CHAR(TO_DATE(P_DENNGAYHL,'DD/MM/YY'),'MM'));   
BEGIN 
    DECLARE
        QUERRY_INSERT VARCHAR2(5000);
        QUERRY_UPDATE_SODU VARCHAR2(5000);
        QUERRY_UPDATE_TON VARCHAR2(3000);
        TEMP_SO_CHUNGTU VARCHAR2(50);
        TEMP_SO_CHUNGTU_DETAIL VARCHAR2(50);
        TEMP_SODU_DAUKY_NO NUMBER;
        TEMP_THANG NUMBER;
        TEMP_TON NUMBER;
        TEMP_SOTIEN NUMBER;
        TEMP_LOAI VARCHAR2(2);
        TEMP_COUNT NUMBER;
        TEMP_SUM NUMBER;
        COUNT_NUMBER NUMBER;
        P_CT VARCHAR2(5000);
    BEGIN
        EXECUTE IMMEDIATE 'DELETE PHC_TEMP_SOCAI WHERE USER_NAME = '''||P_USERNAME||'''';
        IF(P_CONGTHUC IS NULL) THEN P_CT:= '1=1 AND ';
            ELSE P_CT := P_CONGTHUC;
        END IF;
        IF P_USELIKE = 1 THEN -- sử dựng like 
        FOR LIST_CHUNGTU IN (SELECT TAIKHOAN,SO_CHUNGTU_DETAIL,LOAI,MA_CHUNGTU,SO_CHUNGTU,DIENGIAI,
        DIA_CHI,ONGBA,NGAY_HT,NGAY_CT,MA_CTMT,MA_TINHCHATNGUON,MADOITUONG,MAKHOANMUC,MACHITIET,
        CHUONG,LOAIKHOAN,TIEUMUC,LOAIHINH_CHITITET,LOAIHINH_DOITUONG,
        LOAIHINH_KHOANMUC,SOLUONG,GIA,SOTIEN,TIEN_NSNN,TIENTHOAITHU,TIENTHOAICHI FROM V_PHC_TH_CHUNGTU WHERE TAIKHOAN LIKE ''||P_TAIKHOAN||'%' AND TO_DATE(NGAY_HT,'DD-MM-YY') > TO_DATE(P_TUNGAYHL,'DD-MM-YY') AND TO_DATE(NGAY_HT,'DD-MM-YY') < TO_DATE(P_DENNGAYHL,'DD-MM-YY') ORDER BY NGAY_HT,SO_CHUNGTU)
        LOOP
            QUERRY_INSERT := 'INSERT INTO PHC_TEMP_SOCAI(TAIKHOAN,LOAI,THANG,NGAY_HT,NGAY_CT,SO_CHUNGTU,MA_CHUNGTU, 
            SO_CHUNGTU_DETAIL,DIENGIAI,SOTIEN,DIA_CHI,MA_CTMT,MA_TINHCHATNGUON,MADOITUONG,MAKHOANMUC,MACHITIET,CHUONG,LOAIKHOAN,TIEUMUC
            ,LOAIHINH_DOITUONG,SOLUONG,GIA,TIEN_NSNN,TIENTHOAITHU,TIENTHOAICHI,SODU_DAUKY_NO,SODU_DAUKY_CO,SO_PHATSINH_NO,SO_PHATSINH_CO,
            SODU_CUOIKY_NO,SODU_CUOIKY_CO,LUYKE_NO,LUYKE_CO,TON,USER_NAME) VALUES ('''||LIST_CHUNGTU.TAIKHOAN||''','''||LIST_CHUNGTU.LOAI||''','||TO_NUMBER(TO_CHAR(TO_DATE(LIST_CHUNGTU.NGAY_HT,'DD/MM/YY'),'MM'))||','''||LIST_CHUNGTU.NGAY_HT||''','''||LIST_CHUNGTU.NGAY_CT||''',
            '''||LIST_CHUNGTU.SO_CHUNGTU||''','''||LIST_CHUNGTU.MA_CHUNGTU||''','''||LIST_CHUNGTU.SO_CHUNGTU_DETAIL||''','''||LIST_CHUNGTU.DIENGIAI||''','||NVL(LIST_CHUNGTU.SOTIEN,0)||','''||LIST_CHUNGTU.DIA_CHI||''',
            '''||LIST_CHUNGTU.MA_CTMT||''','''||LIST_CHUNGTU.MA_TINHCHATNGUON||''','''||LIST_CHUNGTU.MADOITUONG||''','''||LIST_CHUNGTU.MAKHOANMUC||''','''||LIST_CHUNGTU.MACHITIET||''','''||LIST_CHUNGTU.CHUONG||''',
            '''||LIST_CHUNGTU.LOAIKHOAN||''','''||LIST_CHUNGTU.TIEUMUC||''','''||LIST_CHUNGTU.LOAIHINH_DOITUONG||''','||NVL(LIST_CHUNGTU.SOLUONG,0)||','||NVL(LIST_CHUNGTU.GIA,0)||','||NVL(LIST_CHUNGTU.TIEN_NSNN,0)||','||NVL(LIST_CHUNGTU.TIENTHOAITHU,0)||','||NVL(LIST_CHUNGTU.TIENTHOAICHI,0)||',0,0,0,0,0,0,0,0,0,'''||P_USERNAME||''')';
            --DBMS_OUTPUT.PUT_LINE('QUERRY_INSERT:' || QUERRY_INSERT);
            EXECUTE IMMEDIATE QUERRY_INSERT;
        END LOOP;
        ELSE 
        FOR LIST_CHUNGTU IN (SELECT TAIKHOAN,SO_CHUNGTU_DETAIL,LOAI,MA_CHUNGTU,SO_CHUNGTU,DIENGIAI,
        DIA_CHI,ONGBA,NGAY_HT,NGAY_CT,MA_CTMT,MA_TINHCHATNGUON,MADOITUONG,MAKHOANMUC,MACHITIET,
        CHUONG,LOAIKHOAN,TIEUMUC,LOAIHINH_CHITITET,LOAIHINH_DOITUONG,
        LOAIHINH_KHOANMUC,SOLUONG,GIA,SOTIEN,TIEN_NSNN,TIENTHOAITHU,TIENTHOAICHI FROM V_PHC_TH_CHUNGTU WHERE TAIKHOAN = ''||P_TAIKHOAN||'' AND TO_DATE(NGAY_HT,'DD-MM-YY') > TO_DATE(P_TUNGAYHL,'DD-MM-YY') AND TO_DATE(NGAY_HT,'DD-MM-YY') < TO_DATE(P_DENNGAYHL,'DD-MM-YY') ORDER BY NGAY_HT,SO_CHUNGTU)
        LOOP
            QUERRY_INSERT := 'INSERT INTO PHC_TEMP_SOCAI(TAIKHOAN,LOAI,THANG,NGAY_HT,NGAY_CT,SO_CHUNGTU,MA_CHUNGTU, 
            SO_CHUNGTU_DETAIL,DIENGIAI,SOTIEN,DIA_CHI,MA_CTMT,MA_TINHCHATNGUON,MADOITUONG,MAKHOANMUC,MACHITIET,CHUONG,LOAIKHOAN,TIEUMUC
            ,LOAIHINH_DOITUONG,SOLUONG,GIA,TIEN_NSNN,TIENTHOAITHU,TIENTHOAICHI,SODU_DAUKY_NO,SODU_DAUKY_CO,SO_PHATSINH_NO,SO_PHATSINH_CO,
            SODU_CUOIKY_NO,SODU_CUOIKY_CO,LUYKE_NO,LUYKE_CO,TON,USER_NAME) VALUES ('''||LIST_CHUNGTU.TAIKHOAN||''','''||LIST_CHUNGTU.LOAI||''','||TO_NUMBER(TO_CHAR(TO_DATE(LIST_CHUNGTU.NGAY_HT,'DD/MM/YY'),'MM'))||','''||LIST_CHUNGTU.NGAY_HT||''','''||LIST_CHUNGTU.NGAY_CT||''',
            '''||LIST_CHUNGTU.SO_CHUNGTU||''','''||LIST_CHUNGTU.MA_CHUNGTU||''','''||LIST_CHUNGTU.SO_CHUNGTU_DETAIL||''','''||LIST_CHUNGTU.DIENGIAI||''','||NVL(LIST_CHUNGTU.SOTIEN,0)||','''||LIST_CHUNGTU.DIA_CHI||''',
            '''||LIST_CHUNGTU.MA_CTMT||''','''||LIST_CHUNGTU.MA_TINHCHATNGUON||''','''||LIST_CHUNGTU.MADOITUONG||''','''||LIST_CHUNGTU.MAKHOANMUC||''','''||LIST_CHUNGTU.MACHITIET||''','''||LIST_CHUNGTU.CHUONG||''',
            '''||LIST_CHUNGTU.LOAIKHOAN||''','''||LIST_CHUNGTU.TIEUMUC||''','''||LIST_CHUNGTU.LOAIHINH_DOITUONG||''','||NVL(LIST_CHUNGTU.SOLUONG,0)||','||NVL(LIST_CHUNGTU.GIA,0)||','||NVL(LIST_CHUNGTU.TIEN_NSNN,0)||','||NVL(LIST_CHUNGTU.TIENTHOAITHU,0)||','||NVL(LIST_CHUNGTU.TIENTHOAICHI,0)||',0,0,0,0,0,0,0,0,0,'''||P_USERNAME||''')';
            --DBMS_OUTPUT.PUT_LINE('QUERRY_INSERT:' || QUERRY_INSERT);
            EXECUTE IMMEDIATE QUERRY_INSERT;
        END LOOP;
        END IF;
        DECLARE
            CURSOR_TEMP   SYS_REFCURSOR;
            R_DATA PHC_TEMP_SODU%ROWTYPE;
        BEGIN
        SELECT COUNT(*) INTO COUNT_NUMBER FROM PHC_TEMP_SOCAI WHERE USER_NAME = ''||P_USERNAME||'';
        IF(COUNT_NUMBER > 0 ) THEN
        FOR THANG IN (SELECT (P_TU_THANG + LEVEL - 1) AS MONTH FROM DUAL CONNECT BY LEVEL <= P_DEN_THANG - P_TU_THANG +1)
        LOOP
          --DBMS_OUTPUT.PUT_LINE('THANG.MONTH:' || THANG.MONTH);
          CURSOR_TEMP := FCN_GENERAL_SODU_CUOITHANG(''||P_TAIKHOAN||'',THANG.MONTH,''||P_USERNAME||'');
          FETCH CURSOR_TEMP INTO R_DATA;
            EXIT WHEN CURSOR_TEMP%NOTFOUND;
            QUERRY_UPDATE_SODU := 'UPDATE PHC_TEMP_SOCAI SET SODU_DAUKY_NO = '||R_DATA.SODU_DAUKY_NO||' , SODU_DAUKY_CO = '||R_DATA.SODU_DAUKY_CO||' , SO_PHATSINH_NO = '||R_DATA.SO_PHATSINH_NO||' , SO_PHATSINH_CO = '||R_DATA.SO_PHATSINH_CO||' , 
            SODU_CUOIKY_NO = '||R_DATA.SODU_CUOIKY_NO||' ,SODU_CUOIKY_CO = '||R_DATA.SODU_CUOIKY_CO||' ,LUYKE_NO = '||R_DATA.LUYKE_NO||' ,LUYKE_CO = '||R_DATA.LUYKE_CO||' WHERE THANG = '||THANG.MONTH||' AND USER_NAME = '''||P_USERNAME||''' AND ROWNUM = 1';
            EXECUTE IMMEDIATE QUERRY_UPDATE_SODU;
            TEMP_TON := 0;
            TEMP_SOTIEN := 0;
            SELECT COUNT(*) INTO TEMP_COUNT FROM PHC_TEMP_SOCAI WHERE THANG = ''||THANG.MONTH||'' AND USER_NAME = ''||P_USERNAME||'' AND ROWNUM = 1;
            IF TEMP_COUNT > 0 THEN
                SELECT SODU_DAUKY_NO,SOTIEN,LOAI,SO_CHUNGTU_DETAIL INTO TEMP_SODU_DAUKY_NO,TEMP_SOTIEN,TEMP_LOAI,TEMP_SO_CHUNGTU_DETAIL FROM PHC_TEMP_SOCAI WHERE THANG = ''||THANG.MONTH||'' AND USER_NAME = ''||P_USERNAME||'' AND ROWNUM = 1;
                IF TEMP_LOAI = 'N' THEN TEMP_TON := TEMP_SODU_DAUKY_NO + TEMP_SOTIEN; 
                ELSIF TEMP_LOAI = 'C' THEN TEMP_TON := TEMP_SODU_DAUKY_NO - TEMP_SOTIEN; 
                END IF;
                --DBMS_OUTPUT.put_line ('TEMP_TON:  ' || TEMP_TON);
                QUERRY_UPDATE_TON := 'UPDATE PHC_TEMP_SOCAI SET TON = '||TEMP_TON||' WHERE THANG = '||THANG.MONTH||' AND USER_NAME = '''||P_USERNAME||''' AND SO_CHUNGTU_DETAIL = '''||TEMP_SO_CHUNGTU_DETAIL||'''' ;
                EXECUTE IMMEDIATE QUERRY_UPDATE_TON;
            END IF;

            FOR RECORD_TEMP IN (SELECT * FROM PHC_TEMP_SOCAI WHERE THANG = THANG.MONTH AND USER_NAME = ''||P_USERNAME||'' AND SO_CHUNGTU_DETAIL <> ''||TEMP_SO_CHUNGTU_DETAIL||'')
            LOOP
                  IF RECORD_TEMP.LOAI = 'N' THEN 
                    TEMP_TON := TEMP_TON + RECORD_TEMP.SOTIEN;
                    --DBMS_OUTPUT.put_line ('TEMP_TON REPLACE:  ' || TEMP_TON);
                    QUERRY_UPDATE_TON := 'UPDATE PHC_TEMP_SOCAI SET TON = '||TEMP_TON||' WHERE THANG = '||THANG.MONTH||' AND USER_NAME = '''||P_USERNAME||''' AND SO_CHUNGTU_DETAIL = '''||RECORD_TEMP.SO_CHUNGTU_DETAIL||'''' ;
                    EXECUTE IMMEDIATE QUERRY_UPDATE_TON;
                  ELSIF RECORD_TEMP.LOAI = 'C' THEN
                    TEMP_TON := TEMP_TON - RECORD_TEMP.SOTIEN;
                    --DBMS_OUTPUT.put_line ('TEMP_TON REPLACE:  ' || TEMP_TON);
                    QUERRY_UPDATE_TON := 'UPDATE PHC_TEMP_SOCAI SET TON = '||TEMP_TON||' WHERE THANG = '||THANG.MONTH||' AND USER_NAME = '''||P_USERNAME||''' AND SO_CHUNGTU_DETAIL = '''||RECORD_TEMP.SO_CHUNGTU_DETAIL||'''' ;
                    EXECUTE IMMEDIATE QUERRY_UPDATE_TON;
                  END IF;
                END LOOP;
        END LOOP;
        END IF;
        OPEN CURSOR_RESULT FOR 'SELECT * FROM PHC_TEMP_SOCAI WHERE USER_NAME = '''||P_USERNAME||'''' ;
        EXCEPTION
           WHEN NO_DATA_FOUND
           THEN
              DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
           WHEN OTHERS
           THEN
              DBMS_OUTPUT.put_line ('ERROR'  || SQLERRM); 
        END;    
    END;
END PHC_PRC_SONGANSACH;