create or replace PROCEDURE "PHC_B03_X" (P_MA_DBHC IN VARCHAR2,P_TUNGAYHL IN DATE, P_DENNGAYHL IN DATE, cur OUT SYS_REFCURSOR) as
   QUERY_STR  VARCHAR2(32767); 
   INSERT_STR  VARCHAR2(32767); 
   P_CREATE_TABLE VARCHAR2(32767);
   CHECK_EXIST_TABLE NUMBER(1,0);
    IsExistCT NUMBER(18,2);
   TUNGAY_LUYKE VARCHAR2(10);
   P_NAM VARCHAR(4) := TO_CHAR(TO_DATE(P_DENNGAYHL,'DD/MM/YY'),'YYYY');
   CN_CUR SYS_REFCURSOR;
   I_MACHITIEU VARCHAR(20);
   I_LOAICHITIEU NUMBER(1,0);
   I_THANG NUMBER(18,2);
   BEGIN --START...
    --CREATE TEMP TABLE, DELETE ALL DATA FOR NEW SESSION
    P_CREATE_TABLE:= 'CREATE GLOBAL TEMPORARY TABLE "BTSTC"."PHC_B03X" 
   (	
   "SAPXEP" NVARCHAR2(100), 
   "CAP" NUMBER(10,0),
   "LOAICHITIEU" NUMBER(1,0),
   "MACHITIEU" NVARCHAR2(20), 
   "TENCHITIEU" NVARCHAR2(250),
   "DUTOANNAM" NUMBER(18,2),
   "THANG" NUMBER(18,2)
   ) ON COMMIT PRESERVE ROWS';
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ''PHC_B03X''' INTO CHECK_EXIST_TABLE;
    IF CHECK_EXIST_TABLE > 0 THEN DBMS_OUTPUT.PUT_LINE('ON CREATED');
    ELSE
        EXECUTE IMMEDIATE P_CREATE_TABLE;
    END IF;
    EXECUTE IMMEDIATE 'DELETE FROM PHC_B03X';
    INSERT_STR:= 'INSERT INTO PHC_B03X (SAPXEP, CAP, LOAICHITIEU, MACHITIEU, TENCHITIEU, DUTOANNAM, THANG) 
      SELECT DMCTIEU.SAPXEP, DMCTIEU.CAP, DMCTIEU.LOAICHITIEU, DMCTIEU.MACHITIEU, DMCTIEU.TENCHITIEU, SUM(NVL(DTCT.NSX_DAUNAM,0) + NVL(DTCT.NSX_BOSUNG,0) - NVL(DTCT.NSX_DIEUCHINH,0) - NVL(DTCT.NSX_HUY,0)) AS DUTOANNAM,0 AS THANG
        FROM DM_PHC_CHITIEUTHUCHI DMCTIEU
        LEFT JOIN PHC_DT_THUCHI_NDKT DT ON DMCTIEU.CODELOCATION = DT.CODELOCATION  AND DT.NAM = '||P_NAM||' AND DT.LOAICHITIEU = 1
        LEFT JOIN PHC_DT_THUCHI_NDKT_CHITIET DTCT ON DT.MADUTOAN = DTCT.MADUTOAN AND DTCT.MACHITIEU = DMCTIEU.MACHITIEU 
        WHERE DMCTIEU.CODELOCATION = '''||P_MA_DBHC||''' AND DMCTIEU.TRANG_THAI = ''A'' AND DMCTIEU.PHAN_HE = ''C'' AND DMCTIEU.LOAICHITIEU = 1
            AND (DMCTIEU.DENNGAY_HL IS NULL OR DMCTIEU.DENNGAY_HL >= TO_DATE('''||SYSDATE()||''',''DD/MM/YY'')) 
        GROUP BY DMCTIEU.SAPXEP, DMCTIEU.CAP, DMCTIEU.LOAICHITIEU, DMCTIEU.MACHITIEU, DMCTIEU.TENCHITIEU
    UNION ALL
    SELECT DMCTIEU.SAPXEP, DMCTIEU.CAP, DMCTIEU.LOAICHITIEU, DMCTIEU.MACHITIEU, DMCTIEU.TENCHITIEU, SUM(NVL(DTCT.NSX_DAUNAM,0) + NVL(DTCT.NSX_BOSUNG,0) - NVL(DTCT.NSX_DIEUCHINH,0) - NVL(DTCT.NSX_HUY,0)) AS DUTOANNAM,0 AS THANG
        FROM DM_PHC_CHITIEUTHUCHI DMCTIEU
        LEFT JOIN PHC_DT_THUCHI_NDKT DT ON DMCTIEU.CODELOCATION = DT.CODELOCATION  AND DT.NAM = '||P_NAM||' AND DT.LOAICHITIEU = 2
        LEFT JOIN PHC_DT_THUCHI_NDKT_CHITIET DTCT ON DT.MADUTOAN = DTCT.MADUTOAN AND DTCT.MACHITIEU = DMCTIEU.MACHITIEU 
        WHERE DMCTIEU.CODELOCATION = '''||P_MA_DBHC||''' AND DMCTIEU.TRANG_THAI = ''A'' AND DMCTIEU.PHAN_HE = ''C'' AND DMCTIEU.LOAICHITIEU = 2
            AND (DMCTIEU.DENNGAY_HL IS NULL OR DMCTIEU.DENNGAY_HL >= TO_DATE('''||SYSDATE()||''',''DD/MM/YY'')) 
        GROUP BY DMCTIEU.SAPXEP, DMCTIEU.CAP, DMCTIEU.LOAICHITIEU, DMCTIEU.MACHITIEU, DMCTIEU.TENCHITIEU';
    --DBMS_OUTPUT.put_line(INSERT_STR); 
    EXECUTE IMMEDIATE INSERT_STR;
    --Update số liệu tháng, lũy kế 
    QUERY_STR := 'SELECT MACHITIEU, LOAICHITIEU FROM PHC_B03X ORDER BY CAP DESC, MACHITIEU ASC';
    OPEN CN_CUR FOR QUERY_STR;
    LOOP
         FETCH CN_CUR INTO I_MACHITIEU, I_LOAICHITIEU;
         EXIT WHEN CN_CUR%NOTFOUND;
         I_THANG :=0;
         SELECT COUNT(*) INTO IsExistCT FROM DM_PHC_CHITIEUTHUCHI WHERE MACHITIEU = ''||I_MACHITIEU||'' AND PHAN_HE = 'C' AND LOAICHITIEU = I_LOAICHITIEU  
                AND CODELOCATION =''||P_MA_DBHC||'' AND (DENNGAY_HL IS NULL OR DENNGAY_HL >= TO_DATE(TO_CHAR(sysdate, 'MM/DD/YYYY'), 'MM/DD/YYYY')) AND CT_QT_W IS NOT NULL;
         IF IsExistCT = 1 THEN
             BEGIN
                --DBMS_OUTPUT.put_line(I_MACHITIEU||' tinh'); 
                IF I_LOAICHITIEU = 1 THEN
                    I_THANG := NVL(PHC_FCN_TONGHOPCHITIEUTHU( ''||I_MACHITIEU||'',''||P_TUNGAYHL||'',''||P_DENNGAYHL||'',0,''||P_MA_DBHC||''),0);
                ELSE
                    I_THANG := NVL(PHC_FCN_TONGHOPCHITIEUCHI( ''||I_MACHITIEU||'',''||P_TUNGAYHL||'',''||P_DENNGAYHL||'',0,''||P_MA_DBHC||''),0);
                END IF;
             END;
         ELSE
            BEGIN
               -- DBMS_OUTPUT.put_line(I_MACHITIEU|| ' sum'); 
                EXECUTE IMMEDIATE 'SELECT SUM(NVL(A.THANG,0)) FROM PHC_B03X A
                WHERE A.MACHITIEU IN (SELECT B.MACHITIEU FROM DM_PHC_CHITIEUTHUCHI B WHERE B.MACHA = '''||I_MACHITIEU||''' AND B.PHAN_HE = ''C'' AND B.LOAICHITIEU = '||I_LOAICHITIEU||' 
                    AND B.CODELOCATION ='''||P_MA_DBHC||''' AND (B.DENNGAY_HL IS NULL OR B.DENNGAY_HL >= TO_DATE(TO_CHAR(sysdate, ''MM/DD/YYYY''), ''MM/DD/YYYY'')))' INTO I_THANG ;
                IF I_THANG IS NULL THEN I_THANG :=0; END IF;
            END;
        END IF;
        BEGIN
            EXECUTE IMMEDIATE 'UPDATE PHC_B03X
             SET THANG = '||I_THANG||'
            WHERE MACHITIEU = '''||I_MACHITIEU||''' AND LOAICHITIEU = '||I_LOAICHITIEU||'';
            COMMIT;
        END;
    END LOOP;
    CLOSE CN_CUR;
   QUERY_STR:= 'SELECT * FROM PHC_B03X WHERE MACHITIEU IN (''100'', ''300'',''400'',''500'',''510'',''520'',''550'',''650'') ORDER BY MACHITIEU';
BEGIN 
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line(QUERY_STR  || SQLERRM); 
END; --END RETURN VALUE

END PHC_B03_X; --END...