create or replace PROCEDURE "PHC_B06X" (P_MA_DBHC IN VARCHAR2, P_TUNGAYHL IN DATE, P_DENNGAYHL IN DATE, P_LOAIHINH IN VARCHAR2, P_TAI_KHOAN IN VARCHAR2, cur OUT SYS_REFCURSOR) as
   QUERY_STR  VARCHAR2(32767); 
   INSERT_STR  VARCHAR2(32767); 
   CREATE_TABLE VARCHAR2(32767);
   CHECK_EXIST_TABLE NUMBER(1,0);
    IsExistCT NUMBER(18,2);
   TUNGAY_DAUKY VARCHAR2(10);
   CN_CUR SYS_REFCURSOR;
   I_MADANHMUC VARCHAR(20);
   I_CAP NUMBER(18,2);
   I_TONDAUKY NUMBER(18,2);
   I_THU_DAUKY NUMBER(18,2);
   I_CHI_DAUKY NUMBER(18,2);
   I_THU NUMBER(18,2);
   I_CHI NUMBER(18,2);
   BEGIN --START...
    TUNGAY_DAUKY := TO_CHAR ('01/01/'||TO_CHAR(P_TUNGAYHL,'YY')||'');
     --CREATE TEMP TABLE, DELETE ALL DATA FOR NEW SESSION
    CREATE_TABLE:= 'CREATE GLOBAL TEMPORARY TABLE "BTSTC"."PHC_B06_X" 
   (	
   "CAP" NUMBER(1,0),
   "MALOAIHINH" NVARCHAR2(20),
   "MADANHMUC" NVARCHAR2(20), 
   "TENDANHMUC" NVARCHAR2(250),
   "TONDAUKY" NUMBER(18,2) DEFAULT 0,
   "TONGTHU" NUMBER(18,2)  DEFAULT 0,
   "TONGCHI" NUMBER(18,2)  DEFAULT 0,
   "CONLAI" NUMBER(18,2)  DEFAULT 0
   ) ON COMMIT PRESERVE ROWS';
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = ''PHC_B06_X''' INTO CHECK_EXIST_TABLE;
    IF CHECK_EXIST_TABLE > 0 THEN DBMS_OUTPUT.PUT_LINE('ON CREATED');
    ELSE EXECUTE IMMEDIATE CREATE_TABLE;
    END IF;
    EXECUTE IMMEDIATE 'DELETE FROM PHC_B06_X';
    INSERT_STR:= 'INSERT INTO PHC_B06_X (CAP, MALOAIHINH, MADANHMUC, TENDANHMUC) 
      SELECT 1 AS CAP, MALOAIHINH AS MALOAIHINH, MALOAIHINH AS MADANHMUC, TENLOAIHINH AS TENDANHMUC FROM DM_LOAIHINH WHERE MALOAIHINH IN ('||P_LOAIHINH||') 
        UNION ALL
      SELECT 2 AS CAP, MALOAIHINH, MADANHMUC, TENDANHMUC FROM DM_DANHMUC WHERE MALOAIHINH IN ('||P_LOAIHINH||')';
    EXECUTE IMMEDIATE INSERT_STR;
    --Update s? li?u tháng, l?y k? 
    QUERY_STR := 'SELECT MADANHMUC, CAP FROM PHC_B06_X ORDER BY CAP DESC, MADANHMUC ASC';
    OPEN CN_CUR FOR QUERY_STR;
    LOOP
         FETCH CN_CUR INTO I_MADANHMUC, I_CAP;
         EXIT WHEN CN_CUR%NOTFOUND;
         I_THU :=0; I_CHI :=0; I_THU_DAUKY :=0; I_CHI_DAUKY :=0; I_TONDAUKY:=0;
         IF I_CAP = 2 THEN
            EXECUTE IMMEDIATE 'SELECT SUM(NVL(SOTIEN,0)) FROM V_PHC_CHUNGTU WHERE LOAI_TAIKHOAN = ''C'' AND MAHOATDONG = '''||I_MADANHMUC||''' AND TAIKHOAN IN ('||P_TAI_KHOAN||')
                AND NGAY_HT >= TO_DATE('''||TUNGAY_DAUKY||''',''DD/MM/YY'') AND NGAY_HT < TO_DATE('''||P_TUNGAYHL||''',''DD/MM/YY'') AND CODELOCATION = '''||P_MA_DBHC||''' ' INTO I_THU_DAUKY;
            EXECUTE IMMEDIATE 'SELECT SUM(NVL(SOTIEN,0)) FROM V_PHC_CHUNGTU WHERE LOAI_TAIKHOAN = ''N'' AND MAHOATDONG = '''||I_MADANHMUC||''' AND TAIKHOAN IN ('||P_TAI_KHOAN||')
                AND NGAY_HT >= TO_DATE('''||TUNGAY_DAUKY||''',''DD/MM/YY'') AND NGAY_HT < TO_DATE('''||P_TUNGAYHL||''',''DD/MM/YY'') AND CODELOCATION = '''||P_MA_DBHC||''' ' INTO I_CHI_DAUKY;
            EXECUTE IMMEDIATE 'SELECT SUM(NVL(SOTIEN,0)) FROM V_PHC_CHUNGTU WHERE LOAI_TAIKHOAN = ''C'' AND MAHOATDONG = '''||I_MADANHMUC||''' AND TAIKHOAN IN ('||P_TAI_KHOAN||')
                AND NGAY_HT >= TO_DATE('''||P_TUNGAYHL||''',''DD/MM/YY'') AND NGAY_HT <= TO_DATE('''||P_DENNGAYHL||''',''DD/MM/YY'') AND CODELOCATION = '''||P_MA_DBHC||''' ' INTO I_THU;
            EXECUTE IMMEDIATE 'SELECT SUM(NVL(SOTIEN,0)) FROM V_PHC_CHUNGTU WHERE LOAI_TAIKHOAN = ''N'' AND MAHOATDONG = '''||I_MADANHMUC||''' AND TAIKHOAN IN ('||P_TAI_KHOAN||')
                AND NGAY_HT >= TO_DATE('''||P_TUNGAYHL||''',''DD/MM/YY'') AND NGAY_HT <= TO_DATE('''||P_DENNGAYHL||''',''DD/MM/YY'') AND CODELOCATION = '''||P_MA_DBHC||''' ' INTO I_CHI;
            --DBMS_OUTPUT.put_line(I_MADANHMUC||': '||I_THU_DAUKY || ': '||I_CHI_DAUKY || ': '||I_THU || ': '||I_CHI);
            IF I_THU_DAUKY IS NULL THEN I_THU_DAUKY :=0; END IF;
            IF I_CHI_DAUKY IS NULL THEN I_CHI_DAUKY :=0; END IF;
            IF I_THU IS NULL THEN I_THU :=0; END IF;
            IF I_CHI IS NULL THEN I_CHI :=0; END IF;
            EXECUTE IMMEDIATE 'UPDATE PHC_B06_X
                                 SET TONDAUKY = '||I_THU_DAUKY||' - '||I_CHI_DAUKY||',
                                     TONGTHU = '||I_THU||',
                                     TONGCHI = '||I_CHI||',
                                     CONLAI = '||I_THU_DAUKY||' - '||I_CHI_DAUKY||' + '||I_THU||' - '||I_CHI||'
                                WHERE MADANHMUC = '''||I_MADANHMUC||''' ';
         ELSE
           -- DBMS_OUTPUT.put_line(I_MACHITIEU|| ' sum'); 
            EXECUTE IMMEDIATE 'SELECT SUM(NVL(A.TONDAUKY,0)),SUM(NVL(A.TONGTHU,0)),SUM(NVL(A.TONGCHI,0)) FROM PHC_B06_X A WHERE A.MALOAIHINH = '''||I_MADANHMUC||''' ' INTO I_TONDAUKY, I_THU, I_CHI; 
            IF I_TONDAUKY IS NULL THEN I_TONDAUKY :=0; END IF;
            IF I_THU IS NULL THEN I_THU :=0; END IF;
            IF I_CHI IS NULL THEN I_CHI :=0; END IF;
            EXECUTE IMMEDIATE 'UPDATE PHC_B06_X
             SET TONDAUKY = '||I_TONDAUKY||',
                 TONGTHU = '||I_THU||',
                 TONGCHI = '||I_CHI||',
                 CONLAI = '||I_TONDAUKY||' + '||I_THU||' - '||I_CHI||'
            WHERE MADANHMUC = '''||I_MADANHMUC||''' ';
        END IF;
        --DBMS_OUTPUT.put_line('tháng: '||I_THANG||' ; L?y k?: '||I_LUYKE); 
    END LOOP;
    CLOSE CN_CUR;
   QUERY_STR:= 'SELECT * FROM PHC_B06_X ORDER BY DECODE(MALOAIHINH, ''11'', 1, ''25'', 2, ''09'', 3, 4), MADANHMUC ASC';
BEGIN 
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line(QUERY_STR  || SQLERRM); 
END; --END RETURN VALUE
END PHC_B06X; --END...