CREATE OR REPLACE VIEW PHA_CHI_VW (LOAI_NS,MA_TKTN,TEN_TKTN,MA_DVQHNS,TEN_DVQHNS,MA_DIABAN,TEN_DIABAN,MA_CAP,TEN_CAP,
                          MA_CAPNS,TEN_CAPNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,TEN_NGANHKT,MA_LOAI,
                          TEN_LOAI,MA_TIEUMUC,TEN_TIEUMUC,MA_MUC,TEN_MUC,MA_TIEUNHOM,TEN_TIEUNHOM,MA_NHOM,
                          TEN_NHOM,MA_CTMTQG,TEN_CTMTQG,MA_KBNN,TEN_KBNN,MA_NGUON_NSNN,TEN_NGUON_NSNN,NGAY_KET_SO,NGAY_HACH_TOAN,GIA_TRI_HACH_TOAN,
                          LOAI_DU_TOAN)
AS
SELECT STC_PA_SYS.FNC_GET_LOAI_NS(htc.SEGMENT3) AS LOAI_NS,  
htc.SEGMENT2 as MA_TKTN,STC_PA_SYS.FNC_GET_TEN_DM('DM_TKTN','TEN_TKTN','MA_TKTN',htc.SEGMENT2,htc.EFFECTIVE_DATE) AS TEN_TKTN, 
htc.SEGMENT5 AS MA_DVQHNS,'TEN_DVQHNS' AS TEN_DVQHNS, 
htc.SEGMENT6 AS MA_DIABAN,'TEN_DIABAN' AS TEN_DIABAN, 
htc.SEGMENT4 AS MA_CAP, STC_PA_SYS.FNC_GET_DICTIONARY('MA_CAP',htc.SEGMENT4,htc.EFFECTIVE_DATE) AS TEN_CAP,
STC_PA_SYS.FNC_GET_CONVERT_CHUONG2CAP(htc.SEGMENT7) AS MA_CAPNS,STC_PA_SYS.FNC_GET_DICTIONARY('MA_CAP',STC_PA_SYS.FNC_GET_CONVERT_CHUONG2CAP(htc.SEGMENT7),htc.EFFECTIVE_DATE) AS TEN_CAPNS,
htc.SEGMENT7 AS MA_CHUONG, STC_PA_SYS.FNC_GET_TEN_DM('DM_CHUONG','TEN_CHUONG','MA_CHUONG',htc.SEGMENT7,htc.EFFECTIVE_DATE) AS TEN_CHUONG,
htc.SEGMENT8 AS MA_NGANHKT, STC_PA_SYS.FNC_GET_TEN_DM('DM_NGANHKT','TEN_NGANHKT','MA_NGANHKT',htc.SEGMENT8,htc.EFFECTIVE_DATE) AS TEN_NGANHKT, 
STC_PA_SYS.FNC_GET_CONVERT_NKT2LOAI(htc.SEGMENT8) AS MA_LOAI,STC_PA_SYS.FNC_GET_DICTIONARY('MA_LOAI',STC_PA_SYS.FNC_GET_CONVERT_NDKT2MUC(htc.SEGMENT8),htc.EFFECTIVE_DATE) AS TEN_LOAI, 
htc.SEGMENT3 AS MA_TIEUMUC, STC_PA_SYS.FNC_GET_TEN_DM('DM_TIEUMUC','TEN_TIEUMUC','MA_TIEUMUC',htc.SEGMENT3,htc.EFFECTIVE_DATE) AS TEN_TIEUMUC,
STC_PA_SYS.FNC_GET_CONVERT_NDKT2MUC(htc.SEGMENT3) AS MA_MUC,STC_PA_SYS.FNC_GET_TEN_DM('DM_MUC','TEN_MUC','MA_MUC',STC_PA_SYS.FNC_GET_CONVERT_NDKT2MUC(htc.SEGMENT3),htc.EFFECTIVE_DATE) AS TEN_MUC,
STC_PA_SYS.FNC_GET_CONVERT_NDKT2TNHOM(htc.SEGMENT3) AS MA_TIEUNHOM, STC_PA_SYS.FNC_GET_TEN_DM('PHA_DM_TIEUNHOM','TEN_TIEUNHOM','MA_TIEUNHOM',STC_PA_SYS.FNC_GET_CONVERT_NDKT2TNHOM(htc.SEGMENT3),htc.EFFECTIVE_DATE) AS TEN_TIEU_NHOM, 
STC_PA_SYS.FNC_GET_CONVERT_NDKT2NHOM(htc.SEGMENT3) AS MA_NHOM,STC_PA_SYS.FNC_GET_DICTIONARY('MA_NHOM',STC_PA_SYS.FNC_GET_CONVERT_NDKT2NHOM(htc.SEGMENT3),htc.EFFECTIVE_DATE) AS TEN_NHOM, 
htc.SEGMENT9 AS MA_CTMTQG, STC_PA_SYS.FNC_GET_TEN_DM('DM_CTMTQG','TEN_CTMTQG','MA_CTMTQG',htc.SEGMENT9,htc.EFFECTIVE_DATE) AS TEN_CTMTQG, 
htc.SEGMENT10 AS MA_KBNN, STC_PA_SYS.FNC_GET_TEN_DM('DM_KBNN','TEN_KBNN','MA_KBNN',htc.SEGMENT10,htc.EFFECTIVE_DATE) AS TEN_KBNN,htc.SEGMENT11 AS MA_NGUON_NSNN,STC_PA_SYS.FNC_GET_TEN_DM('DM_NGUON_NSNN','TEN_NGUON_NSNN','MA_NGUON_NSNN',htc.SEGMENT11,htc.EFFECTIVE_DATE) AS TEN_NGUON_NSNN, 
htc.POSTED_DATE AS NGAY_KET_SO,htc.EFFECTIVE_DATE AS NGAY_HACH_TOAN,(HTC.ENTERED_DR - HTC.ENTERED_CR) AS GIA_TRI_HACH_TOAN, htc.ATTRIBUTE8 AS LOAI_DU_TOAN
FROM PHA_HACHTOAN_CHI htc;
commit