create or replace PROCEDURE PHA_BCQT_PL06_BM52_V4(P_MABAOCAO IN VARCHAR2,P_TABLENAME IN VARCHAR2, P_USERID IN VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE,P_CONGTHUC IN NVARCHAR2, cur OUT SYS_REFCURSOR) IS
   QUERY_STR  VARCHAR2(32767); 
   SQL_QUERRY_DUTOAN VARCHAR2(32767); 
   P_MA_BAOCAO VARCHAR2(100);
   P_SQL_CREATE_TABLE  VARCHAR2(32767);  
   v_SQL_Clo  VARCHAR2(32767);  
   INSERT_QUERRY  VARCHAR2(32767);  
   INSERT_QUERRY_DUTOAN  VARCHAR2(32767);  
   TABLE_PHA_dt_thu_chi  VARCHAR2(100);  
   TABLE_PHA_DUTOAN VARCHAR2(100);  
   SQL_QUERRY VARCHAR2(32767);
   P_SQL_DELETE VARCHAR2(32767);  
   N_COUNT NUMBER(17,4):=0;
   P_CT VARCHAR2(32767);
   P_SUM VARCHAR2(1000);
   P_WHERE_DATE_HL_TU VARCHAR2(100);  P_WHERE_DATE_HL_DEN VARCHAR2(100);  P_WHERE_DATE_KS_TU VARCHAR2(100);  P_WHERE_DATE_KS_DEN VARCHAR2(100);  
    BEGIN
     -- TAO TABLE DE TONG HOP DU LIEU
        P_MA_BAOCAO:=''''||P_MABAOCAO||'''';   
        IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
            SELECT STC_PA_SYS.FNC_CONVERT_FORMULA (P_CONGTHUC) INTO P_CT FROM dual;
        END IF;        
        P_SQL_CREATE_TABLE := 'CREATE TABLE '||P_TABLENAME||'(
        PHA_TABLE NVARCHAR2(100),MA_TKTN NVARCHAR2(100), MA_DIABAN NVARCHAR2(100), MA_CAP NVARCHAR2(100),MA_CHUONG NVARCHAR2(100),MA_NGANHKT NVARCHAR2(100),MA_LOAI NVARCHAR2(100),
        MA_TIEUMUC NVARCHAR2(100), MA_MUC NVARCHAR2(100), MA_TIEUNHOM NVARCHAR2(100),MA_CTMTQG NVARCHAR2(100),MA_KBNN NVARCHAR2(100), 
        MA_NGUON_NSNN NVARCHAR2(100),MA_DVQHNS NVARCHAR2(100), GIA_TRI_HACH_TOAN NUMBER, USERID NVARCHAR2(150))SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC"';            
  
  /*
  P_SQL_CREATE_TABLE := 'CREATE GLOBAL TEMPORARY TABLE '||P_TABLENAME||'(
        PHA_TABLE NVARCHAR2(100),MA_TKTN NVARCHAR2(100), MA_DIABAN NVARCHAR2(100), MA_CAP NVARCHAR2(100),MA_CHUONG NVARCHAR2(100),MA_NGANHKT NVARCHAR2(100),MA_LOAI NVARCHAR2(100),
        MA_TIEUMUC NVARCHAR2(100), MA_MUC NVARCHAR2(100), MA_TIEUNHOM NVARCHAR2(100),MA_CTMTQG NVARCHAR2(100),MA_KBNN NVARCHAR2(100), 
        MA_NGUON_NSNN NVARCHAR2(100),MA_DVQHNS NVARCHAR2(100), GIA_TRI_HACH_TOAN NUMBER, USERID NVARCHAR2(150))ON COMMIT DELETE ROWS';
   */     
        P_WHERE_DATE_HL_TU:= ' AND NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')';
        P_WHERE_DATE_HL_DEN:= ' AND NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')';        
        P_WHERE_DATE_KS_TU:= ' AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')';
        P_WHERE_DATE_KS_DEN:= ' AND NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')';
        
        -- table PHA_HACHTOAN_CHI
        
        TABLE_PHA_dt_thu_chi:='PHA_HACHTOAN_CHI';
        SQL_QUERRY := 'SELECT '''||TABLE_PHA_dt_thu_chi||'''  ,MA_TKTN , MA_DIABAN, MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC, MA_MUC, MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS
        ,SUM (GIA_TRI_HACH_TOAN),'''||P_USERID||''' FROM '||TABLE_PHA_dt_thu_chi||' VC LEFT JOIN DM_CHITIEU_BAOCAO BC ON VC.MA_DVQHNS=BC.MA_CHITIEU 
        WHERE MA_BAOCAO = ' || P_MA_BAOCAO || ' AND '
        || P_CT || P_WHERE_DATE_HL_TU ||  P_WHERE_DATE_HL_DEN || P_WHERE_DATE_KS_TU ||  P_WHERE_DATE_KS_DEN ||
        'GROUP BY  MA_TKTN , MA_DIABAN, MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC, MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS,'''||P_USERID||'''';     
        INSERT_QUERRY := 'INSERT INTO '||P_TABLENAME||'(PHA_TABLE, MA_TKTN , MA_DIABAN, MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC, MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS,GIA_TRI_HACH_TOAN, USERID)('||SQL_QUERRY||')';
         -- table PHA_DUTOAN
        
        TABLE_PHA_DUTOAN:='PHA_DUTOAN';
        SQL_QUERRY_DUTOAN := 'SELECT '''||TABLE_PHA_DUTOAN||'''  ,MA_TKTN , MA_DIABAN, MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC, MA_MUC, MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS
        ,SUM (GIA_TRI_HACH_TOAN),'''||P_USERID||''' FROM '||TABLE_PHA_DUTOAN||' VC LEFT JOIN DM_CHITIEU_BAOCAO BC ON VC.MA_DVQHNS=BC.MA_CHITIEU 
        WHERE MA_BAOCAO = ' || P_MA_BAOCAO || ' AND '
        || P_CT || P_WHERE_DATE_HL_TU ||  P_WHERE_DATE_HL_DEN || P_WHERE_DATE_KS_TU ||  P_WHERE_DATE_KS_DEN ||
        'GROUP BY  MA_TKTN , MA_DIABAN, MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC, MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS,'''||P_USERID||'''';     
        INSERT_QUERRY_DUTOAN := 'INSERT INTO '||P_TABLENAME||'(PHA_TABLE, MA_TKTN , MA_DIABAN, MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC, MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS,GIA_TRI_HACH_TOAN, USERID)('||SQL_QUERRY_DUTOAN||')';

    -- b3 xu ly cong thuc de nen bao cao
    --- tao table 2 de xu ly so lieu theo cong thuc
   
    P_WHERE_DATE_HL_TU:= '||' || '''' || ' AND NGAY_HIEU_LUC >= TO_DATE ('''''||to_char(TUNGAY_HL,'ddMMyyyy')||''''', ''''ddMMyyyy'''')'' ';
    P_WHERE_DATE_HL_DEN:= '||' || '''' || ' AND NGAY_HIEU_LUC <= TO_DATE ('''''||to_char(DENNGAY_HL,'ddMMyyyy')||''''', ''''ddMMyyyy'''')'' ';
    P_WHERE_DATE_KS_DEN:= '||' || '''' || ' AND NGAY_KET_SO <= TO_DATE ('''''||to_char(DENNGAY_KS,'ddMMyyyy')||''''', ''''ddMMyyyy'''')'' ';
    P_SUM:=''' SELECT SUM(GIA_TRI_HACH_TOAN) FROM '||P_TABLENAME||' WHERE USERID = '|| Chr(39)|| Chr(39) || P_USERID || Chr(39)|| Chr(39) ||' AND '' ||' ;
    

    QUERY_STR:='SELECT MA_BAOCAO,TEN_CHITIEU';
    FOR item IN (SELECT MA_COT,CONGTHUC FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO=P_MABAOCAO )
    LOOP
    v_SQL_Clo:=v_SQL_Clo  || ', ' || 'NVL(RETURN_VALUE_TO_FORMULA('||P_SUM||'(STC_PA_SYS.FNC_CONVERT_FORMULA((SELECT CONGTHUC as CT_CLO FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= '||P_MA_BAOCAO||' AND MA_COT='''|| item.MA_COT||'''))||  '' AND '' || ( STC_PA_SYS.FNC_CONVERT_FORMULA(CONGTHUC)) ' || ')),0) as ' ||item.MA_COT||'';
    END LOOP;
    QUERY_STR:=QUERY_STR || v_SQL_Clo|| ' FROM DM_CHITIEU_BAOCAO WHERE MA_BAOCAO = '||P_MA_BAOCAO||'';
    
    BEGIN
        SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = UPPER(P_TABLENAME);
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
    END;
    IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
    BEGIN
        EXECUTE IMMEDIATE P_SQL_CREATE_TABLE;  
    END;
    END IF;  
    BEGIN
        P_SQL_DELETE:='DELETE FROM '||P_TABLENAME||' WHERE USERID=''' || P_USERID || '''';
      EXECUTE IMMEDIATE P_SQL_DELETE;   
      EXECUTE IMMEDIATE INSERT_QUERRY;  
      EXECUTE IMMEDIATE INSERT_QUERRY_DUTOAN;  
      DBMS_OUTPUT.ENABLE(1000000);
      DBMS_OUTPUT.put_line ('t:=' ||  QUERY_STR );
        --QUERY_STR:='SELECT * FROM ' ||P_TABLENAME;
        OPEN cur FOR QUERY_STR;
        EXCEPTION
         WHEN NO_DATA_FOUND
          THEN
            DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
          WHEN OTHERS
          THEN  DBMS_OUTPUT.put_line ('-'); 
    END;	
END PHA_BCQT_PL06_BM52_V4;