create or replace PROCEDURE       PHA_BCCT_R_C_V3(P_LOAI_DL IN VARCHAR2,P_MABAOCAO IN VARCHAR2,TABLENAME_TH IN VARCHAR2,P_TABLENAME IN VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE,P_CONGTHUC IN NVARCHAR2, cur OUT SYS_REFCURSOR) IS
   QUERY_STR  VARCHAR2(32767);    
   P_MA_BAOCAO VARCHAR2(100);
   P_SQL_CREATE_TABLE_TH  VARCHAR2(32767);  
   P_SQL_CREATE_TABLE  VARCHAR2(32767);  
   v_SQL_Clo  VARCHAR2(32767);  
   v_SQL_Clo_2  VARCHAR2(32767);  
   INSERT_QUERRY_CHI  VARCHAR2(32767);  
   INSERT_QUERRY_THU  VARCHAR2(32767);  
   TABLE_PHA_DT_CHI  VARCHAR2(100); 
   TABLE_PHA_DT_THU  VARCHAR2(100);   
   SQL_QUERRY VARCHAR2(32767);
   N_COUNT NUMBER(17,4):=0;
   P_CT VARCHAR2(32767);
   P_SUM VARCHAR2(32767);
   P_SUM_U1 VARCHAR2(32767);
   P_SUM_U2 VARCHAR2(32767);
   P_SUM_U3 VARCHAR2(32767);
   P_SUM_U4 VARCHAR2(32767);
   P_SUM_U VARCHAR2(32767);
   P_WHERE_C_R VARCHAR2(32767);
  -- P_INSERT_C_R VARCHAR2(32767);
  P_INSERT_C_R clob;
   P_UPDATE_C_R_S1 VARCHAR2(32767);
   P_UPDATE_C_R_S2 VARCHAR2(32767);
   P_UPDATE_C_R_S3 VARCHAR2(32767);
   P_UPDATE_C_R_S4 VARCHAR2(32767);
   P_TABLENAME_TH VARCHAR2(100);
    P_CT_SUM VARCHAR2(1000);
     BEGIN
     IF(TABLENAME_TH IS NULL OR LENGTH(TABLENAME_TH)<=0) THEN P_TABLENAME_TH:='PHA_TH_MLNS'; 
     ELSE P_TABLENAME_TH:=TABLENAME_TH;
     END IF;
     -- TAO TABLE DE TONG HOP DU LIEU
        P_MA_BAOCAO:=''''||P_MABAOCAO||'''';   
        IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
            SELECT STC_PA_SYS.FNC_CONVERT_FORMULA (P_CONGTHUC) INTO P_CT FROM dual;
        END IF;        
        P_SQL_CREATE_TABLE_TH := 'CREATE TABLE '||P_TABLENAME_TH||'(
        PHA_TABLE NVARCHAR2(100),MA_TKTN NVARCHAR2(100), MA_DIABAN NVARCHAR2(100), MA_CAP NVARCHAR2(100),MA_CHUONG NVARCHAR2(100),MA_NGANHKT NVARCHAR2(100),MA_LOAI NVARCHAR2(100),
        MA_TIEUMUC NVARCHAR2(100), MA_MUC NVARCHAR2(100), MA_TIEUNHOM NVARCHAR2(100),MA_CTMTQG NVARCHAR2(100),MA_KBNN NVARCHAR2(100), 
        MA_NGUON_NSNN NVARCHAR2(100),MA_DVQHNS NVARCHAR2(100), GIA_TRI_HACH_TOAN NUMBER)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC"';            

         -- table PHA_HACHTOAN_THU              
        TABLE_PHA_DT_THU:='PHA_HACHTOAN_THU';
        SQL_QUERRY := 'SELECT '''||TABLE_PHA_DT_THU||'''  ,MA_TKTN,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS
        ,SUM (GIA_TRI_HACH_TOAN) FROM '||TABLE_PHA_DT_THU||' VC WHERE VC.NGAY_HIEU_LUC >= '''||TUNGAY_HL||''' 
              AND VC.NGAY_HIEU_LUC <= '''||DENNGAY_HL||''' AND VC.NGAY_KET_SO >= '''||TUNGAY_KS||''' AND ' ||' VC.NGAY_KET_SO <= '''||DENNGAY_KS||''' AND ' ||P_CT||
        ' GROUP BY  MA_TKTN,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS';     
        INSERT_QUERRY_THU := 'INSERT INTO '||P_TABLENAME_TH||'(PHA_TABLE,MA_TKTN ,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS,GIA_TRI_HACH_TOAN)('||SQL_QUERRY||')';

        -- table PHA_HACHTOAN_CHI
        TABLE_PHA_DT_CHI:='PHA_HACHTOAN_CHI';
        SQL_QUERRY := 'SELECT '''||TABLE_PHA_DT_CHI||'''  ,MA_TKTN ,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS
        ,SUM (GIA_TRI_HACH_TOAN) FROM '||TABLE_PHA_DT_CHI||' VC WHERE VC.NGAY_HIEU_LUC >= '''||TUNGAY_HL||''' 
              AND VC.NGAY_HIEU_LUC <= '''||DENNGAY_HL||''' AND VC.NGAY_KET_SO >= '''||TUNGAY_KS||''' AND ' ||' VC.NGAY_KET_SO <= '''||DENNGAY_KS||''' AND ' ||P_CT||
        ' GROUP BY  MA_TKTN,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS';   
        INSERT_QUERRY_CHI := 'INSERT INTO '||P_TABLENAME_TH||'(PHA_TABLE,MA_TKTN ,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS,GIA_TRI_HACH_TOAN)('||SQL_QUERRY||')';
    BEGIN
        SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = UPPER(P_TABLENAME_TH);
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
    END;

    IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
    BEGIN
        EXECUTE IMMEDIATE P_SQL_CREATE_TABLE_TH;  
        EXECUTE IMMEDIATE INSERT_QUERRY_THU;  
        EXECUTE IMMEDIATE INSERT_QUERRY_CHI;  
    END;
    END IF;


    FOR item IN (SELECT MA_COT FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO=P_MABAOCAO AND TRANG_THAI='A' ORDER BY STT ASC)
    LOOP   
        v_SQL_Clo:= v_SQL_Clo || item.MA_COT ||' NUMBER, ';
        v_SQL_Clo_2:= v_SQL_Clo_2 || item.MA_COT ||', ';
    END LOOP;
    --- table 2
    /*P_SQL_CREATE_TABLE := 'CREATE GLOBAL TEMPORARY TABLE '||P_TABLENAME||'(SAPXEP NUMBER(10,0) , CT NVARCHAR2(2000), INDAM NUMBER(10,0), INNGHIENG NUMBER(10,0), TRANG_THAI NVARCHAR2(1),MA_CHITIEU NVARCHAR2(50),TEN_CHITIEU NVARCHAR2(500),' 
                        ||v_SQL_Clo||' STT NVARCHAR2(100))ON COMMIT DELETE ROWS'; */
    P_SQL_CREATE_TABLE := 'CREATE TABLE '||P_TABLENAME||'(SAPXEP NVARCHAR2(100) , CT NVARCHAR2(2000), INDAM NUMBER(10,0), INNGHIENG NUMBER(10,0),HIENTHI NVARCHAR2(1), TRANG_THAI NVARCHAR2(10),LOAI_CHITIEU NUMBER(10,0),MA_CHITIEU NVARCHAR2(50),TEN_CHITIEU NVARCHAR2(500),' 
                        ||v_SQL_Clo||' STT NVARCHAR2(100))SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC"';
     BEGIN
          SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = UPPER(P_TABLENAME);
          EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;

      IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
      BEGIN
       DBMS_OUTPUT.put_line ('C:=' ||  P_SQL_CREATE_TABLE );
          EXECUTE IMMEDIATE P_SQL_CREATE_TABLE;  

      END;
      END IF;
      -- TAO TABLE 2
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' ||P_TABLENAME;
    FOR item_R IN (SELECT SAPXEP,STT,INDAM,INNGHIENG,HIENTHI,TRANG_THAI,LOAICHITIEU,MA_CHITIEU,TEN_CHITIEU,CONGTHUC_WHERE,ID FROM DM_CHITIEU_BAOCAO WHERE MA_BAOCAO = P_MABAOCAO ORDER BY SAPXEP ASC)
    LOOP
        IF(item_R.TRANG_THAI IS NULL OR  item_R.TRANG_THAI='C' OR  item_R.TRANG_THAI='T') THEN 
        BEGIN
                P_INSERT_C_R:= 'INSERT INTO '|| P_TABLENAME ||'(SAPXEP,STT,INDAM,INNGHIENG,HIENTHI,TRANG_THAI,LOAI_CHITIEU,MA_CHITIEU,'||v_SQL_Clo_2||'TEN_CHITIEU)';
                P_INSERT_C_R:=P_INSERT_C_R || 'VALUES('''|| item_R.SAPXEP ||''','''|| NVL(item_R.STT,'NULL') ||''','|| NVL(item_R.INDAM,0) ||','|| NVL(item_R.INNGHIENG,0) ||','|| item_R.HIENTHI ||',''C'','|| NVL(item_R.LOAICHITIEU,0) ||','|| item_R.MA_CHITIEU ||',';
                FOR item_C IN (SELECT MA_COT,CONGTHUC_WHERE,TRANG_THAI FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO=P_MABAOCAO AND TRANG_THAI='A' ORDER BY STT ASC)
                    LOOP   
                    IF(item_R.TRANG_THAI IS NULL OR  item_R.TRANG_THAI='C') THEN 
                        begin
                        
                         if(P_LOAI_DL IS NULL OR UPPER(P_LOAI_DL)='ALL')THEN P_SUM:='SELECT NVL(SUM(GIA_TRI_HACH_TOAN),0) FROM '||P_TABLENAME_TH||' WHERE '; END IF;                                    
                         if(UPPER(P_LOAI_DL)='T')THEN P_SUM:='SELECT NVL(SUM(GIA_TRI_HACH_TOAN),0) FROM '||P_TABLENAME_TH||' WHERE (PHA_TABLE='''|| TABLE_PHA_DT_THU ||  ''') AND '; END IF;                                    
                         if(UPPER(P_LOAI_DL)='C')THEN P_SUM:='SELECT NVL(SUM(GIA_TRI_HACH_TOAN),0) FROM '||P_TABLENAME_TH||' WHERE (PHA_TABLE='''|| TABLE_PHA_DT_CHI ||  ''') AND '; END IF;                                    
                         
                          -- DBMS_OUTPUT.put_line ('P_SUM:=' ||  P_SUM );
                          if(LENGTH (item_R.CONGTHUC_WHERE)>0 and LENGTH (item_C.CONGTHUC_WHERE)>0) THEN P_WHERE_C_R:= '(' || TRIM(item_R.CONGTHUC_WHERE) || ') AND (' || TRIM(item_C.CONGTHUC_WHERE) ||')'; END IF;
                          if(LENGTH (item_R.CONGTHUC_WHERE)<=0 and LENGTH (item_C.CONGTHUC_WHERE)<=0) THEN P_WHERE_C_R:='1=1'; END IF;                                    
                          if(LENGTH (item_R.CONGTHUC_WHERE)>0 and LENGTH (item_C.CONGTHUC_WHERE)<=0) THEN P_WHERE_C_R:=TRIM(item_R.CONGTHUC_WHERE); END IF;
                          if(((LENGTH (item_R.CONGTHUC_WHERE)<=0) OR item_R.CONGTHUC_WHERE IS NULL ) and LENGTH (item_C.CONGTHUC_WHERE)>0) THEN P_WHERE_C_R:=TRIM(item_C.CONGTHUC_WHERE); END IF;
                          if(LENGTH (P_WHERE_C_R)>0) THEN P_SUM:='(' || P_SUM|| TRIM(P_WHERE_C_R) || ')';
                            ELSE P_SUM:='(' || P_SUM|| ')'; 
                          END IF;
                          P_INSERT_C_R:=P_INSERT_C_R || P_SUM ||',';                        
                       end;
                    ELSIF( item_R.TRANG_THAI='T') THEN
                        BEGIN
                        -- Đ? T?M TEN_COT=M? CH? TIÊU
                          P_SUM:='(SELECT NVL(SUM(GIA_TRI),0) FROM DM_CHITIEU_BAOCAO_COL WHERE TRANG_THAI=''B'' AND MA_COT=''' || item_C.MA_COT || ''' AND TEN_COT=''' || item_R.MA_CHITIEU ||''' AND MA_BAOCAO= '''|| P_MABAOCAO ||''')';
                          P_INSERT_C_R:=P_INSERT_C_R || P_SUM ||',';
                        end;
                  END IF;
                    END LOOP;

                   IF(item_R.TRANG_THAI IS NULL OR  item_R.TRANG_THAI='C') THEN 
                    BEGIN
                        P_INSERT_C_R:=P_INSERT_C_R || '''' || item_R.TEN_CHITIEU || '''' ||')';
                        --DBMS_OUTPUT.put_line ('t5:=' ||  item_R.ID );
                        --DBMS_OUTPUT.put_line ('t4:=' ||  P_INSERT_C_R );
                      EXECUTE IMMEDIATE P_INSERT_C_R; 
                    -- DBMS_OUTPUT.put_line ('t5:=' ||  item_R.ID );
                        IF(item_R.MA_CHITIEU = '70000')then 
                          DBMS_OUTPUT.put_line ('t4:=' ||  P_INSERT_C_R );
                        end if;
                        
                    END;
                    ELSIF (item_R.TRANG_THAI='T') THEN 
                    BEGIN
                        P_INSERT_C_R:=P_INSERT_C_R || '''' || item_R.TEN_CHITIEU || '''' ||')';
                        EXECUTE IMMEDIATE P_INSERT_C_R; 
                    END;
                END IF;
        END;
        ELSE
        BEGIN
                  P_INSERT_C_R:= 'INSERT INTO '|| P_TABLENAME ||'(SAPXEP,STT,INDAM,INNGHIENG,HIENTHI,TRANG_THAI,LOAI_CHITIEU,CT,MA_CHITIEU,TEN_CHITIEU)';
                  P_INSERT_C_R:=P_INSERT_C_R || 'VALUES('''|| item_R.SAPXEP ||''','''|| NVL(item_R.STT,'NULL') ||''','|| NVL(item_R.INDAM,0) ||','|| NVL(item_R.INNGHIENG,0) ||','''|| item_R.HIENTHI ||''',''' || item_R.TRANG_THAI  ||''','|| NVL(item_R.LOAICHITIEU,0) ||','''  ||  NVL(REPLACE(item_R.CONGTHUC_WHERE,'''',''''''),'NULL') ||  ''',''' ||  item_R.MA_CHITIEU || '''' ||',';
                  P_INSERT_C_R:=P_INSERT_C_R || '''' || item_R.TEN_CHITIEU || '''' ||')';
                 -- DBMS_OUTPUT.put_line ('t5:=' || item_R.ID );
                  EXECUTE IMMEDIATE P_INSERT_C_R; 
            END;
        END IF;
        END LOOP; 
-- B2 UPDATE CONG THUC TONG TAI CAC CHI TIEU CO TRANG THAI S 
     P_UPDATE_C_R_S4:=' UPDATE ' || P_TABLENAME || ' A SET ';
     FOR item_C IN (SELECT MA_COT,CONGTHUC_WHERE FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO=P_MABAOCAO AND TRANG_THAI='A' ORDER BY STT ASC )
            LOOP   
                  P_SUM_U4:=P_SUM_U4 || 'A.'|| item_C.MA_COT || ' = (SELECT NVL(SUM('|| item_C.MA_COT ||'),0) FROM '||P_TABLENAME||' B WHERE instr(A.CT,B.MA_CHITIEU)>0),';  
            END LOOP;
       P_SUM_U4:= SUBSTR(P_SUM_U4,0,LENGTh(P_SUM_U4)-1);
       P_UPDATE_C_R_S4:=P_UPDATE_C_R_S4 || P_SUM_U4 ||' WHERE A.TRANG_THAI=''S''';
      -- DBMS_OUTPUT.put_line ('T5:=' ||  P_UPDATE_C_R_S4 );
      EXECUTE IMMEDIATE P_UPDATE_C_R_S4; 

-- B2 UPDATE CONG THUC TONG TAI CAC CHI TIEU CO TRANG THAI S 1
     P_UPDATE_C_R_S1:=' UPDATE ' || P_TABLENAME || ' A SET ';
     FOR item_C IN (SELECT MA_COT,CONGTHUC_WHERE FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO=P_MABAOCAO AND TRANG_THAI='A' ORDER BY STT ASC )
            LOOP   
                  P_SUM_U1:=P_SUM_U1 || 'A.'|| item_C.MA_COT || ' = (SELECT NVL(SUM('|| item_C.MA_COT ||'),0) FROM '||P_TABLENAME||' B WHERE instr(A.CT,B.MA_CHITIEU)>0),';  
            END LOOP;
       P_SUM_U1:= SUBSTR(P_SUM_U1,0,LENGTh(P_SUM_U1)-1);
       P_UPDATE_C_R_S1:=P_UPDATE_C_R_S1 || P_SUM_U1 ||' WHERE A.TRANG_THAI=''S1''';
     --  DBMS_OUTPUT.put_line ('T5:=' ||  P_UPDATE_C_R_S1 );
      EXECUTE IMMEDIATE P_UPDATE_C_R_S1; 

  --- B2 UPDATE CONG THUC TONG TAI CAC CHI TIEU CO TRANG THAI S 2
     P_UPDATE_C_R_S2:=' UPDATE ' || P_TABLENAME || ' A SET ';
     FOR item_C IN (SELECT MA_COT,CONGTHUC_WHERE FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO=P_MABAOCAO AND TRANG_THAI='A' ORDER BY STT ASC )
            LOOP   
                  P_SUM_U2:=P_SUM_U2 || 'A.'|| item_C.MA_COT || ' = (SELECT NVL(SUM('|| item_C.MA_COT ||'),0) FROM '||P_TABLENAME||' B WHERE instr(A.CT,B.MA_CHITIEU)>0),';                  
            END LOOP;
       P_SUM_U2:= SUBSTR(P_SUM_U2,0,LENGTh(P_SUM_U2)-1);
       P_UPDATE_C_R_S2:= P_UPDATE_C_R_S2 || P_SUM_U2 ||' WHERE A.TRANG_THAI=''S2''';
      -- DBMS_OUTPUT.put_line ('T6:=' ||  P_UPDATE_C_R_S2 );
      EXECUTE IMMEDIATE P_UPDATE_C_R_S2; 

      --- B2 UPDATE CONG THUC TONG TAI CAC CHI TIEU CO TRANG THAI S 3
     P_UPDATE_C_R_S3:=' UPDATE ' || P_TABLENAME || ' A SET ';
     FOR item_C IN (SELECT MA_COT,CONGTHUC_WHERE FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO=P_MABAOCAO AND TRANG_THAI='A' ORDER BY STT ASC )
            LOOP   
                  P_SUM_U3:=P_SUM_U3 || 'A.'|| item_C.MA_COT || ' = (SELECT NVL(SUM('|| item_C.MA_COT ||'),0) FROM '||P_TABLENAME||' B WHERE instr(A.CT,B.MA_CHITIEU)>0),';                  
            END LOOP;
       P_SUM_U3:= SUBSTR(P_SUM_U3,0,LENGTh(P_SUM_U3)-1);
       P_UPDATE_C_R_S3:=P_UPDATE_C_R_S3 || P_SUM_U3 ||' WHERE A.TRANG_THAI=''S3''';
      -- DBMS_OUTPUT.put_line ('T7:=' ||  P_UPDATE_C_R_S3 );
      EXECUTE IMMEDIATE P_UPDATE_C_R_S3; 

    -- IN RA MAM HINH  
    BEGIN
    DBMS_OUTPUT.ENABLE(1000000);
    --DBMS_OUTPUT.ENABLE (buffer_size => NULL);
     --DBMS_OUTPUT.put_line ('t:=' ||  QUERY_STR );
      QUERY_STR:='SELECT * FROM ' ||P_TABLENAME||' where 1=1 order by SAPXEP ASC';
        OPEN cur FOR QUERY_STR;
        EXCEPTION
         WHEN NO_DATA_FOUND
          THEN
            DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
          WHEN OTHERS
          THEN  DBMS_OUTPUT.put_line ('-'); 
    END;	

END PHA_BCCT_R_C_V3;