create or replace PROCEDURE PHA_BCQT_PL06_BM52(DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE, P_CONGTHUC IN VARCHAR2, P_USERID IN VARCHAR2, cur OUT SYS_REFCURSOR) AS 
    QUERY_STR  VARCHAR2(32767); 
    P_MA_BAOCAO VARCHAR2(100);
    P_MA_COT_1  VARCHAR2(100);
    P_MA_COT_2  VARCHAR2(100);
    P_MA_COT_3  VARCHAR2(100);
    P_MA_COT_4  VARCHAR2(100);
    P_MA_COT_5  VARCHAR2(100);
    P_MA_COT_6  VARCHAR2(100);
    P_WHERE_DATE_HL_TU  VARCHAR2(100);
    P_WHERE_DATE_HL_DEN VARCHAR2(100);
    P_WHERE_DATE_KS_DEN VARCHAR2(100);
    P_SUM_DT VARCHAR2(1000);
    P_SUM_HT VARCHAR2(1000);
    --P_USERID VARCHAR2(100); -- Set khi truyen tham so

BEGIN
    P_MA_BAOCAO:='''PL06-BM52''';    
    P_MA_COT_1:='DT_BS_CD';
    P_MA_COT_2:='DT_VON_TN';
    P_MA_COT_3:='DT_VON_NN';
    P_MA_COT_4:='QT_BS_CD';
    P_MA_COT_5:='QT_VON_TN';
    P_MA_COT_6:='QT_VON_NN';
    P_WHERE_DATE_HL_TU:= '||' || '''' || ' AND NGAY_HIEU_LUC >= TO_DATE ('''''||to_char(TUNGAY_HL,'ddMMyyyy')||''''', ''''ddMMyyyy'''')'' ';
    P_WHERE_DATE_HL_DEN:= '||' || '''' || ' AND NGAY_HIEU_LUC <= TO_DATE ('''''||to_char(DENNGAY_HL,'ddMMyyyy')||''''', ''''ddMMyyyy'''')'' ';
    P_WHERE_DATE_KS_DEN:= '||' || '''' || ' AND NGAY_KET_SO <= TO_DATE ('''''||to_char(DENNGAY_KS,'ddMMyyyy')||''''', ''''ddMMyyyy'''')'' ';
    P_SUM_DT:=''' SELECT SUM(GIA_TRI_HACH_TOAN) FROM PHA_MLNS WHERE USERID = '|| Chr(39)|| Chr(39) || P_USERID || Chr(39)|| Chr(39) ||' AND '' ||' ;
    --P_SUM_HT:=''' SELECT SUM(GIA_TRI_HACH_TOAN) FROM PHA_MLNS WHERE USERID = chr(39)||'|| Chr(39)|| Chr(39) || P_USERID || Chr(39)|| Chr(39) ||' ||chr(39) AND '' ||' ;
    
    -- Tong hop MLNS
    
    STC_PA_SYS.PRC_TH_MLNS_BYFOMULAR(P_BNGAY_HACHTOAN => TUNGAY_HL,
      P_ENGAY_HACHTOAN => DENNGAY_HL,
      P_BNGAY_KETSO => To_Date('01012000','ddMMyyyy'),
      P_ENGAY_KETSO => DENNGAY_KS,
      P_LOAI => 'CD',
      P_USERID => P_USERID,
      P_CONGTHUC => P_CONGTHUC);
    
    
QUERY_STR:='SELECT MA_BAOCAO,TEN_CHITIEU,CONGTHUC AS CT_ROW,
    NVL(RETURN_VALUE_TO_FORMULA('||P_SUM_DT||'(STC_PA_SYS.FNC_CONVERT_FORMULA((SELECT CONGTHUC as CT_CLO FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= '||P_MA_BAOCAO||' AND MA_COT='''|| P_MA_COT_1||''')) ||  '' AND '' || ( STC_PA_SYS.FNC_CONVERT_FORMULA(CONGTHUC)) ' || ')),0) as ' ||P_MA_COT_1||',
    NVL(RETURN_VALUE_TO_FORMULA('||P_SUM_DT||'(STC_PA_SYS.FNC_CONVERT_FORMULA((SELECT CONGTHUC as CT_CLO FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= '||P_MA_BAOCAO||' AND MA_COT='''|| P_MA_COT_2||''')) ||  '' AND '' || ( STC_PA_SYS.FNC_CONVERT_FORMULA(CONGTHUC)) ' || ')),0) as ' ||P_MA_COT_2||',
    NVL(RETURN_VALUE_TO_FORMULA('||P_SUM_DT||'(STC_PA_SYS.FNC_CONVERT_FORMULA((SELECT CONGTHUC as CT_CLO FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= '||P_MA_BAOCAO||' AND MA_COT='''|| P_MA_COT_3||''')) ||  '' AND '' || ( STC_PA_SYS.FNC_CONVERT_FORMULA(CONGTHUC)) ' || ')),0) as ' ||P_MA_COT_3||',
    NVL(RETURN_VALUE_TO_FORMULA('||P_SUM_DT||'(STC_PA_SYS.FNC_CONVERT_FORMULA((SELECT CONGTHUC as CT_CLO FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= '||P_MA_BAOCAO||' AND MA_COT='''|| P_MA_COT_4||''')) ||  '' AND '' || ( STC_PA_SYS.FNC_CONVERT_FORMULA(CONGTHUC)) ' || ')),0) as ' ||P_MA_COT_4||',
    NVL(RETURN_VALUE_TO_FORMULA('||P_SUM_DT||'(STC_PA_SYS.FNC_CONVERT_FORMULA((SELECT CONGTHUC as CT_CLO FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= '||P_MA_BAOCAO||' AND MA_COT='''|| P_MA_COT_5||''')) ||  '' AND '' || ( STC_PA_SYS.FNC_CONVERT_FORMULA(CONGTHUC)) ' || ')),0) as ' ||P_MA_COT_5||',
    NVL(RETURN_VALUE_TO_FORMULA('||P_SUM_DT||'(STC_PA_SYS.FNC_CONVERT_FORMULA((SELECT CONGTHUC as CT_CLO FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= '||P_MA_BAOCAO||' AND MA_COT='''|| P_MA_COT_6||''')) ||  '' AND '' || ( STC_PA_SYS.FNC_CONVERT_FORMULA(CONGTHUC)) ' || ')),0) as ' ||P_MA_COT_6||'
    FROM DM_CHITIEU_BAOCAO WHERE MA_BAOCAO = '||P_MA_BAOCAO||'';
DBMS_OUTPUT.ENABLE(1000000);
DBMS_OUTPUT.put_line(QUERY_STR);
BEGIN
OPEN cur FOR QUERY_STR;
EXCEPTION
 WHEN NO_DATA_FOUND
  THEN
    DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
  WHEN OTHERS
  THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END;

END PHA_BCQT_PL06_BM52;