
  CREATE TABLE "BTSTC"."TABWH_JEL_FCT" 
   (	"SEGMENT1" VARCHAR2(25 BYTE), 
	"SEGMENT2" VARCHAR2(25 BYTE), 
	"SEGMENT3" VARCHAR2(25 BYTE), 
	"SEGMENT4" VARCHAR2(25 BYTE), 
	"SEGMENT5" VARCHAR2(25 BYTE), 
	"SEGMENT6" VARCHAR2(25 BYTE), 
	"SEGMENT7" VARCHAR2(25 BYTE), 
	"SEGMENT8" VARCHAR2(25 BYTE), 
	"SEGMENT9" VARCHAR2(25 BYTE), 
	"SEGMENT10" VARCHAR2(25 BYTE), 
	"SEGMENT11" VARCHAR2(25 BYTE), 
	"SEGMENT12" VARCHAR2(25 BYTE), 
	"SET_OF_BOOKS_ID" NUMBER(15,0), 
	"SOB_NAME" VARCHAR2(30 BYTE), 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"POSTED_DATE" DATE, 
	"EFFECTIVE_DATE" DATE, 
	"ENTERED_DR" NUMBER, 
	"ENTERED_CR" NUMBER, 
	"ACCOUNTED_DR" NUMBER, 
	"ACCOUNTED_CR" NUMBER, 
	"ACTUAL_FLAG" VARCHAR2(1 BYTE), 
	"CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"TRANSFORM_DATE" DATE, 
	"VOUCHER_DATE" DATE, 
	"ATTRIBUTE8" VARCHAR2(150 BYTE)
   ) PCTFREE 0 PCTUSED 90 INITRANS 1 MAXTRANS 255 COMPRESS FOR OLTP  NOLOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC" 
  PARTITION BY RANGE ("POSTED_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) 
 (PARTITION "P130101"  VALUES LESS THAN (TO_DATE(' 2013-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 0 PCTUSED 90 INITRANS 1 MAXTRANS 255  NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC" COMPRESS FOR OLTP ) 
  PARALLEL 16  ENABLE ROW MOVEMENT ;
 

  CREATE INDEX "BTSTC"."TABWH_JEL_FCT$IDX1" ON "BTSTC"."TABWH_JEL_FCT" ("EFFECTIVE_DATE", "CURRENCY_CODE", "ACTUAL_FLAG", "SEGMENT2", "SEGMENT6", "SET_OF_BOOKS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC" ;
 

  CREATE INDEX "BTSTC"."TABWH_JEL_FCT_IDX1" ON "BTSTC"."TABWH_JEL_FCT" ("POSTED_DATE", "SET_OF_BOOKS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255  NOLOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC_IDX"  LOCAL
 (PARTITION "P130101" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255  NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC_IDX" ) COMPRESS 2 
  PARALLEL ;
 
