CREATE GLOBAL TEMPORARY TABLE temptb_dmct
( STT varchar2(10) NULL,
  SAPXEP number(10,0) NULL,
  MA_CHITIEU varchar2(50) NULL,
  NGAY_HL DATE NULL,
  TEN_CHITIEU varchar2(2000) NULL,
  TRANGTHAI varchar2(1) NULL,
  MA_DONG VARCHAR2(100) NULL,
  INDAM NUMBER(10,0) NULL,
  INNGHIENG NUMBER(10,0) NULL,
  HIENTHI VARCHAR2(1) NULL,
  LOAI NUMBER(10,0) NULL,
  DAU NUMBER(10,0) NULL,
  TW_PS NUMBER(15,0) NULL,
  TW_LK NUMBER(15,0) NULL,
  TINH_PS NUMBER(15,0) NULL,
  TINH_LK NUMBER(15,0) NULL,
  HUYEN_PS NUMBER(15,0) NULL,
  HUYEN_LK NUMBER(15,0) NULL,
  XA_PS NUMBER(15,0) NULL,
  XA_LK NUMBER(15,0) NULL
  )ON COMMIT DELETE ROWS;
  drop table temptb_ctbc; commit;
  SELECT * FROM temptb_ctbc;
  