

create or replace PROCEDURE TRACUU_DULIEU_THU_CHI
(
  MABAOCAO_PK NVARCHAR2,
  MaBaoCao NVARCHAR2,
  NamBC NVARCHAR2,
  ThangBC NVARCHAR2,
  outRef OUT SYS_REFCURSOR
)
AS 
 QUERY_STR  VARCHAR2(32767); 
BEGIN
  --FOR item IN (SELECT MA_CHITIEU FROM  DM_CHITIEU_BAOCAO WHERE MA_BAOCAO=P_MABAOCAO )
  QUERY_STR:='SELECT * FROM PHA_HACHTOAN_THU TC WHERE TC.MA_KBNN >= 1115 AND TC.MA_KBNN <= 1116 ORDER BY TC.MA_KBNN';

DBMS_OUTPUT.put_line (QUERY_STR);
BEGIN
OPEN outRef FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END; 
END TRACUU_DULIEU_THU_CHI;