create or replace PROCEDURE "PHA_DTBG_01" (P_CONGTHUC VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE, DONVI_TIEN number, cur OUT SYS_REFCURSOR) 
AS
   P_CT VARCHAR2(32767);   
   P_SQL_INSERT NVARCHAR2(32767);
   QUERY_STR VARCHAR2(32767);
   QUERY_STR1 VARCHAR2(32767);
   QUERY_STR2 VARCHAR2(32767);
   QUERY_STR3 VARCHAR2(32767);
   QUERY_STR4 VARCHAR2(32767);
   QUERY_STR5 VARCHAR2(32767);
   QUERY_STR6 VARCHAR2(32767);
   QUERY_STR7 CLOB;
   Q_INSERT CLOB;
   Q_INSERT_1 CLOB;
   Q_INSERT_2 CLOB;
   Q_INSERT_3 CLOB;
   Q_INSERT_4 CLOB;
   Q_INSERT_5 CLOB;
   Q_INSERT_6 CLOB;
   NAM_TRUOC VARCHAR2(200); 
   NAM_HIENTAI VARCHAR2(200);
   NAM_SAU VARCHAR2(200);
   BEGIN
        NAM_HIENTAI := TO_CHAR(TUNGAY_HL,'yyyy');
        NAM_TRUOC := REPLACE(TO_CHAR(TO_NUMBER(NAM_HIENTAI, '9999') - 1,'9999'),chr(32),'');
        NAM_SAU := REPLACE(TO_CHAR(TO_NUMBER(NAM_HIENTAI, '9999') + 1,'9999'),chr(32),'');
QUERY_STR:=' SELECT MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS,TEN_DVQHNS,SUM(LK_TDN) AS LK_TDN, SUM(KHN) AS KHN, SUM(HOANUNG_NT) AS HOANUNG_NT, SUM(HOANUNG) AS HOANUNG , (NVL(SUM(GNNKH),0) - NVL(SUM(HOANUNG),0)) AS GNNKH, (NVL(SUM(GNDDA),0) - NVL(SUM(HOANUNG),0)) AS GNDDA FROM 
        (SELECT COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS FROM
        (SELECT COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS FROM
        (SELECT COT123.MA_DVQHNS, COT123.MA_NGUON_NSNN, COT123.MA_CHUONG, COT123.LK_TDN, COT123.KHN, COT123.HOANUNG_NT, COT4.HOANUNG, COT123.TEN_DVQHNS FROM
        (SELECT COT12.MA_DVQHNS, COT12.MA_NGUON_NSNN, COT12.MA_CHUONG, COT12.LK_TDN, COT12.KHN, COT3.HOANUNG_NT,COT12.TEN_DVQHNS FROM
        (SELECT COT1.MA_DVQHNS, COT1.MA_NGUON_NSNN, COT1.MA_CHUONG, COT1.LK_TDN, COT2.KHN,COT1.TEN_DVQHNS FROM
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS LK_TDN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT1
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, DK1.TEN_DVQHNS) COT2
        ON COT1.MA_DVQHNS = COT2.MA_DVQHNS AND COT1.MA_NGUON_NSNN = COT2.MA_NGUON_NSNN AND COT1.MA_CHUONG = COT2.MA_CHUONG
        GROUP BY COT1.MA_DVQHNS, COT1.MA_NGUON_NSNN, COT1.MA_CHUONG, COT1.LK_TDN, COT2.KHN,COT1.TEN_DVQHNS) COT12
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_DR),0) AS HOANUNG_NT, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)CHI INNER JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_DR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT3 ON COT12.MA_DVQHNS = COT3.MA_DVQHNS AND COT12.MA_NGUON_NSNN = COT3.MA_NGUON_NSNN AND COT12.MA_CHUONG = COT3.MA_CHUONG
        GROUP BY COT12.MA_DVQHNS, COT12.MA_NGUON_NSNN, COT12.MA_CHUONG, COT12.LK_TDN, COT12.KHN, COT3.HOANUNG_NT,COT12.TEN_DVQHNS) COT123
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT4 ON COT123.MA_DVQHNS = COT4.MA_DVQHNS AND COT123.MA_NGUON_NSNN = COT4.MA_NGUON_NSNN AND COT123.MA_CHUONG = COT4.MA_CHUONG
        GROUP BY COT123.MA_DVQHNS, COT123.MA_NGUON_NSNN, COT123.MA_CHUONG, COT123.LK_TDN, COT123.KHN, COT123.HOANUNG_NT, COT4.HOANUNG, COT123.TEN_DVQHNS) COT1234
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS GNNKH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT5 
        ON COT1234.MA_DVQHNS = COT5.MA_DVQHNS AND COT1234.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT1234.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS) COT12345
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS GNDDA, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''',''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT6
        ON COT12345.MA_DVQHNS = COT6.MA_DVQHNS AND COT12345.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT12345.MA_CHUONG = COT6.MA_CHUONG 
        GROUP BY COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS)
        WHERE MA_DVQHNS LIKE ''7%'' AND MA_CHUONG BETWEEN ''405'' AND ''599'' AND NOT MA_NGUON_NSNN LIKE ''00''
        GROUP BY MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS
        ';
        QUERY_STR1:=' SELECT MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS,TEN_DVQHNS,SUM(LK_TDN) AS LK_TDN, SUM(KHN) AS KHN, SUM(HOANUNG_NT) AS HOANUNG_NT, SUM(HOANUNG) AS HOANUNG , (NVL(SUM(GNNKH),0) - NVL(SUM(HOANUNG),0)) AS GNNKH, (NVL(SUM(GNDDA),0) - NVL(SUM(HOANUNG),0)) AS GNDDA FROM 
        (SELECT COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS FROM
        (SELECT COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS FROM
        (SELECT COT123.MA_DVQHNS, COT123.MA_NGUON_NSNN, COT123.MA_CHUONG, COT123.LK_TDN, COT123.KHN, COT123.HOANUNG_NT, COT4.HOANUNG, COT123.TEN_DVQHNS FROM
        (SELECT COT12.MA_DVQHNS, COT12.MA_NGUON_NSNN, COT12.MA_CHUONG, COT12.LK_TDN, COT12.KHN, COT3.HOANUNG_NT,COT12.TEN_DVQHNS FROM
        (SELECT COT2.MA_DVQHNS, COT2.MA_NGUON_NSNN, COT2.MA_CHUONG, COT1.LK_TDN, COT2.KHN,COT2.TEN_DVQHNS FROM
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS LK_TDN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT1
        RIGHT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT2
        ON COT2.MA_DVQHNS = COT1.MA_DVQHNS AND COT2.MA_NGUON_NSNN = COT1.MA_NGUON_NSNN AND COT2.MA_CHUONG = COT1.MA_CHUONG
        GROUP BY COT2.MA_DVQHNS, COT2.MA_NGUON_NSNN, COT2.MA_CHUONG, COT1.LK_TDN, COT2.KHN,COT2.TEN_DVQHNS) COT12
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_DR),0) AS HOANUNG_NT, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)CHI INNER JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_DR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT3 ON COT12.MA_DVQHNS = COT3.MA_DVQHNS AND COT12.MA_NGUON_NSNN = COT3.MA_NGUON_NSNN AND COT12.MA_CHUONG = COT3.MA_CHUONG
        GROUP BY COT12.MA_DVQHNS, COT12.MA_NGUON_NSNN, COT12.MA_CHUONG, COT12.LK_TDN, COT12.KHN, COT3.HOANUNG_NT,COT12.TEN_DVQHNS) COT123
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT4 ON COT123.MA_DVQHNS = COT4.MA_DVQHNS AND COT123.MA_NGUON_NSNN = COT4.MA_NGUON_NSNN AND COT123.MA_CHUONG = COT4.MA_CHUONG
        GROUP BY COT123.MA_DVQHNS, COT123.MA_NGUON_NSNN, COT123.MA_CHUONG, COT123.LK_TDN, COT123.KHN, COT123.HOANUNG_NT, COT4.HOANUNG, COT123.TEN_DVQHNS) COT1234
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS GNNKH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT5 
        ON COT1234.MA_DVQHNS = COT5.MA_DVQHNS AND COT1234.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT1234.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS) COT12345
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS GNDDA, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''',''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT6
        ON COT12345.MA_DVQHNS = COT6.MA_DVQHNS AND COT12345.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT12345.MA_CHUONG = COT6.MA_CHUONG 
        GROUP BY COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS)
        WHERE MA_DVQHNS LIKE ''7%'' AND MA_CHUONG BETWEEN ''405'' AND ''599'' AND NOT MA_NGUON_NSNN LIKE ''00''
        GROUP BY MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS ';
        QUERY_STR2:=' SELECT MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS,TEN_DVQHNS,SUM(LK_TDN) AS LK_TDN, SUM(KHN) AS KHN, SUM(HOANUNG_NT) AS HOANUNG_NT, SUM(HOANUNG) AS HOANUNG , (NVL(SUM(GNNKH),0) - NVL(SUM(HOANUNG),0)) AS GNNKH, (NVL(SUM(GNDDA),0) - NVL(SUM(HOANUNG),0)) AS GNDDA FROM 
        (SELECT COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS FROM
        (SELECT COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS FROM
        (SELECT COT123.MA_DVQHNS, COT123.MA_NGUON_NSNN, COT123.MA_CHUONG, COT123.LK_TDN, COT123.KHN, COT123.HOANUNG_NT, COT4.HOANUNG, COT123.TEN_DVQHNS FROM
        (SELECT COT13.MA_DVQHNS, COT13.MA_NGUON_NSNN, COT13.MA_CHUONG, COT13.HOANUNG_NT, COT13.LK_TDN, COT2.KHN,COT13.TEN_DVQHNS FROM
        (SELECT COT3.MA_DVQHNS, COT3.MA_NGUON_NSNN, COT3.MA_CHUONG, COT3.HOANUNG_NT, COT1.LK_TDN,COT3.TEN_DVQHNS FROM 
        (SELECT NVL(SUM(CHI.ACCOUNTED_DR),0) AS HOANUNG_NT, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)CHI INNER JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_DR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT3 
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS LK_TDN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, DK1.TEN_DVQHNS) COT1
        ON COT3.MA_DVQHNS = COT1.MA_DVQHNS AND COT3.MA_NGUON_NSNN = COT1.MA_NGUON_NSNN AND COT3.MA_CHUONG = COT1.MA_CHUONG
        GROUP BY COT3.MA_DVQHNS, COT3.MA_NGUON_NSNN, COT3.MA_CHUONG, COT3.HOANUNG_NT, COT1.LK_TDN,COT3.TEN_DVQHNS) COT13
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, DK1.TEN_DVQHNS) COT2
        ON COT13.MA_DVQHNS = COT2.MA_DVQHNS AND COT13.MA_NGUON_NSNN = COT2.MA_NGUON_NSNN AND COT13.MA_CHUONG = COT2.MA_CHUONG
        GROUP BY COT13.MA_DVQHNS, COT13.MA_NGUON_NSNN, COT13.MA_CHUONG, COT13.HOANUNG_NT, COT13.LK_TDN, COT2.KHN,COT13.TEN_DVQHNS) COT123
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT4 ON COT123.MA_DVQHNS = COT4.MA_DVQHNS AND COT123.MA_NGUON_NSNN = COT4.MA_NGUON_NSNN AND COT123.MA_CHUONG = COT4.MA_CHUONG
        GROUP BY COT123.MA_DVQHNS, COT123.MA_NGUON_NSNN, COT123.MA_CHUONG, COT123.LK_TDN, COT123.KHN, COT123.HOANUNG_NT, COT4.HOANUNG, COT123.TEN_DVQHNS) COT1234
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS GNNKH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT5 
        ON COT1234.MA_DVQHNS = COT5.MA_DVQHNS AND COT1234.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT1234.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS) COT12345
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS GNDDA, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''',''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT6
        ON COT12345.MA_DVQHNS = COT6.MA_DVQHNS AND COT12345.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT12345.MA_CHUONG = COT6.MA_CHUONG 
        GROUP BY COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS)
        WHERE MA_DVQHNS LIKE ''7%'' AND MA_CHUONG BETWEEN ''405'' AND ''599'' AND NOT MA_NGUON_NSNN LIKE ''00''
        GROUP BY MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS ';
        QUERY_STR3:=' SELECT MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS,TEN_DVQHNS,SUM(LK_TDN) AS LK_TDN, SUM(KHN) AS KHN, SUM(HOANUNG_NT) AS HOANUNG_NT, SUM(HOANUNG) AS HOANUNG , (NVL(SUM(GNNKH),0) - NVL(SUM(HOANUNG),0)) AS GNNKH, (NVL(SUM(GNDDA),0) - NVL(SUM(HOANUNG),0)) AS GNDDA FROM 
        (SELECT COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS FROM
        (SELECT COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS FROM
        (SELECT COT124.MA_DVQHNS, COT124.MA_NGUON_NSNN, COT124.MA_CHUONG, COT124.HOANUNG ,COT124.LK_TDN, COT124.KHN, COT3.HOANUNG_NT,COT124.TEN_DVQHNS FROM
        (SELECT COT14.MA_DVQHNS, COT14.MA_NGUON_NSNN, COT14.MA_CHUONG, COT14.HOANUNG, COT14.LK_TDN, COT2.KHN,COT14.TEN_DVQHNS FROM
        (SELECT COT4.MA_DVQHNS, COT4.MA_NGUON_NSNN, COT4.MA_CHUONG, COT4.HOANUNG, COT1.LK_TDN,COT4.TEN_DVQHNS FROM 
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT4
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS LK_TDN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT1
        ON COT4.MA_DVQHNS = COT1.MA_DVQHNS AND COT4.MA_NGUON_NSNN = COT1.MA_NGUON_NSNN AND COT4.MA_CHUONG = COT1.MA_CHUONG
        GROUP BY COT4.MA_DVQHNS, COT4.MA_NGUON_NSNN, COT4.MA_CHUONG, COT4.HOANUNG, COT1.LK_TDN,COT4.TEN_DVQHNS) COT14
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT2
        ON COT14.MA_DVQHNS = COT2.MA_DVQHNS AND COT14.MA_NGUON_NSNN = COT2.MA_NGUON_NSNN AND COT14.MA_CHUONG = COT2.MA_CHUONG
        GROUP BY COT14.MA_DVQHNS, COT14.MA_NGUON_NSNN, COT14.MA_CHUONG, COT14.HOANUNG, COT14.LK_TDN, COT2.KHN,COT14.TEN_DVQHNS) COT124
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_DR),0) AS HOANUNG_NT, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)CHI INNER JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_DR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT3 ON COT124.MA_DVQHNS = COT3.MA_DVQHNS AND COT124.MA_NGUON_NSNN = COT3.MA_NGUON_NSNN AND COT124.MA_CHUONG = COT3.MA_CHUONG
        GROUP BY COT124.MA_DVQHNS, COT124.MA_NGUON_NSNN, COT124.MA_CHUONG, COT124.HOANUNG ,COT124.LK_TDN, COT124.KHN, COT3.HOANUNG_NT,COT124.TEN_DVQHNS) COT1234
        LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS GNNKH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT5 
        ON COT1234.MA_DVQHNS = COT5.MA_DVQHNS AND COT1234.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT1234.MA_CHUONG = COT5.MA_CHUONG
        GROUP BY COT1234.MA_DVQHNS, COT1234.MA_NGUON_NSNN, COT1234.MA_CHUONG, COT1234.LK_TDN, COT1234.KHN,COT1234.HOANUNG_NT, COT1234.HOANUNG, COT5.GNNKH,COT1234.TEN_DVQHNS) COT12345
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS GNDDA, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''',''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT6
        ON COT12345.MA_DVQHNS = COT6.MA_DVQHNS AND COT12345.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT12345.MA_CHUONG = COT6.MA_CHUONG 
        GROUP BY COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS)
        WHERE MA_DVQHNS LIKE ''7%'' AND MA_CHUONG BETWEEN ''405'' AND ''599'' AND NOT MA_NGUON_NSNN LIKE ''00''
        GROUP BY MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS ';
        QUERY_STR4:=' SELECT MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS,TEN_DVQHNS,SUM(LK_TDN) AS LK_TDN, SUM(KHN) AS KHN, SUM(HOANUNG_NT) AS HOANUNG_NT, SUM(HOANUNG) AS HOANUNG , (NVL(SUM(GNNKH),0) - NVL(SUM(HOANUNG),0)) AS GNNKH, (NVL(SUM(GNDDA),0) - NVL(SUM(HOANUNG),0)) AS GNDDA FROM 
        (SELECT COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS FROM
        (SELECT COT1235.MA_DVQHNS, COT1235.MA_NGUON_NSNN, COT1235.MA_CHUONG, COT1235.GNNKH ,COT1235.LK_TDN, COT1235.KHN, COT1235.HOANUNG_NT,COT4.HOANUNG,COT1235.TEN_DVQHNS FROM
        (SELECT COT125.MA_DVQHNS, COT125.MA_NGUON_NSNN, COT125.MA_CHUONG, COT125.GNNKH ,COT125.LK_TDN, COT125.KHN, COT3.HOANUNG_NT,COT125.TEN_DVQHNS FROM
        (SELECT COT15.MA_DVQHNS, COT15.MA_NGUON_NSNN, COT15.MA_CHUONG, COT15.GNNKH, COT15.LK_TDN, COT2.KHN,COT15.TEN_DVQHNS FROM
        (SELECT COT5.MA_DVQHNS, COT5.MA_NGUON_NSNN, COT5.MA_CHUONG, COT5.GNNKH, COT1.LK_TDN,COT5.TEN_DVQHNS FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS GNNKH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT5 
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS LK_TDN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT1
        ON COT5.MA_DVQHNS = COT1.MA_DVQHNS AND COT5.MA_NGUON_NSNN = COT1.MA_NGUON_NSNN AND COT5.MA_CHUONG = COT1.MA_CHUONG
        GROUP BY COT5.MA_DVQHNS, COT5.MA_NGUON_NSNN, COT5.MA_CHUONG, COT5.GNNKH, COT1.LK_TDN,COT5.TEN_DVQHNS) COT15
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT2
        ON COT15.MA_DVQHNS = COT2.MA_DVQHNS AND COT15.MA_NGUON_NSNN = COT2.MA_NGUON_NSNN AND COT15.MA_CHUONG = COT2.MA_CHUONG
        GROUP BY COT15.MA_DVQHNS, COT15.MA_NGUON_NSNN, COT15.MA_CHUONG, COT15.GNNKH, COT15.LK_TDN, COT2.KHN,COT15.TEN_DVQHNS) COT125
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_DR),0) AS HOANUNG_NT, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)CHI INNER JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_DR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT3 ON COT125.MA_DVQHNS = COT3.MA_DVQHNS AND COT125.MA_NGUON_NSNN = COT3.MA_NGUON_NSNN AND COT125.MA_CHUONG = COT3.MA_CHUONG
        GROUP BY COT125.MA_DVQHNS, COT125.MA_NGUON_NSNN, COT125.MA_CHUONG, COT125.GNNKH ,COT125.LK_TDN, COT125.KHN, COT3.HOANUNG_NT,COT125.TEN_DVQHNS) COT1235
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT4 ON COT1235.MA_DVQHNS = COT4.MA_DVQHNS AND COT1235.MA_NGUON_NSNN = COT4.MA_NGUON_NSNN AND COT1235.MA_CHUONG = COT4.MA_CHUONG
        GROUP BY COT1235.MA_DVQHNS, COT1235.MA_NGUON_NSNN, COT1235.MA_CHUONG, COT1235.GNNKH ,COT1235.LK_TDN, COT1235.KHN, COT1235.HOANUNG_NT,COT4.HOANUNG,COT1235.TEN_DVQHNS) COT12345
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS GNDDA, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''',''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT6
        ON COT12345.MA_DVQHNS = COT6.MA_DVQHNS AND COT12345.MA_NGUON_NSNN = COT6.MA_NGUON_NSNN AND COT12345.MA_CHUONG = COT6.MA_CHUONG 
        GROUP BY COT12345.MA_DVQHNS, COT12345.MA_NGUON_NSNN, COT12345.MA_CHUONG, COT12345.LK_TDN, COT12345.KHN,COT12345.HOANUNG_NT, COT12345.HOANUNG, COT12345.GNNKH, COT6.GNDDA, COT12345.TEN_DVQHNS)
        WHERE MA_DVQHNS LIKE ''7%'' AND MA_CHUONG BETWEEN ''405'' AND ''599'' AND NOT MA_NGUON_NSNN LIKE ''00''
        GROUP BY MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS ';
        QUERY_STR5:=' SELECT MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS,TEN_DVQHNS,SUM(LK_TDN) AS LK_TDN, SUM(KHN) AS KHN, SUM(HOANUNG_NT) AS HOANUNG_NT, SUM(HOANUNG) AS HOANUNG , (NVL(SUM(GNNKH),0) - NVL(SUM(HOANUNG),0)) AS GNNKH, (NVL(SUM(GNDDA),0) - NVL(SUM(HOANUNG),0)) AS GNDDA FROM 
        (SELECT COT12346.MA_DVQHNS, COT12346.MA_NGUON_NSNN, COT12346.MA_CHUONG, COT12346.LK_TDN, COT12346.KHN,COT12346.HOANUNG_NT, COT12346.HOANUNG, COT5.GNNKH, COT12346.GNDDA, COT12346.TEN_DVQHNS FROM
        (SELECT COT1236.MA_DVQHNS, COT1236.MA_NGUON_NSNN, COT1236.MA_CHUONG, COT1236.GNDDA ,COT1236.LK_TDN, COT1236.KHN, COT1236.HOANUNG_NT,COT4.HOANUNG,COT1236.TEN_DVQHNS FROM
        (SELECT COT126.MA_DVQHNS, COT126.MA_NGUON_NSNN, COT126.MA_CHUONG, COT126.GNDDA ,COT126.LK_TDN, COT126.KHN, COT3.HOANUNG_NT,COT126.TEN_DVQHNS FROM
        (SELECT COT16.MA_DVQHNS, COT16.MA_NGUON_NSNN, COT16.MA_CHUONG, COT16.GNDDA, COT16.LK_TDN, COT2.KHN,COT16.TEN_DVQHNS FROM
        (SELECT COT6.MA_DVQHNS, COT6.MA_NGUON_NSNN, COT6.MA_CHUONG, COT6.GNDDA, COT1.LK_TDN,COT6.TEN_DVQHNS FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS GNDDA, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'',''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''',''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''',''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT6
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS LK_TDN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT1
        ON COT6.MA_DVQHNS = COT1.MA_DVQHNS AND COT6.MA_NGUON_NSNN = COT1.MA_NGUON_NSNN AND COT6.MA_CHUONG = COT1.MA_CHUONG
        GROUP BY COT6.MA_DVQHNS, COT6.MA_NGUON_NSNN, COT6.MA_CHUONG, COT6.GNDDA, COT1.LK_TDN,COT6.TEN_DVQHNS) COT16
        LEFT JOIN
        (SELECT DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG, (NVL(SUM(DK1.T1),0) + NVL(SUM(DK2.T2),0)) AS KHN,DK1.TEN_DVQHNS FROM
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR - ACCOUNTED_CR),0) AS T1, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''01''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK1 FULL JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,NVL(SUM(ACCOUNTED_DR),0) AS T2, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE (''01012016'', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''02''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) DK2 ON DK1.MA_DVQHNS = DK2.MA_DVQHNS AND DK1.MA_CHUONG = DK2.MA_CHUONG AND DK1.MA_NGUON_NSNN = DK2.MA_NGUON_NSNN
        GROUP BY DK1.MA_DVQHNS, DK1.MA_NGUON_NSNN, DK1.MA_CHUONG,DK1.TEN_DVQHNS) COT2
        ON COT16.MA_DVQHNS = COT2.MA_DVQHNS AND COT16.MA_NGUON_NSNN = COT2.MA_NGUON_NSNN AND COT16.MA_CHUONG = COT2.MA_CHUONG
        GROUP BY COT16.MA_DVQHNS, COT16.MA_NGUON_NSNN, COT16.MA_CHUONG, COT16.GNDDA, COT16.LK_TDN, COT2.KHN,COT16.TEN_DVQHNS) COT126
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_DR),0) AS HOANUNG_NT, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)CHI INNER JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_DUTOAN WHERE NGAY_HIEU_LUC >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''|| '3112'||NAM_TRUOC ||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''|| '0101'||NAM_TRUOC ||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''95%'' AND ATTRIBUTE8 LIKE ''04''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_DR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT3 ON COT126.MA_DVQHNS = COT3.MA_DVQHNS AND COT126.MA_NGUON_NSNN = COT3.MA_NGUON_NSNN AND COT126.MA_CHUONG = COT3.MA_CHUONG
        GROUP BY COT126.MA_DVQHNS, COT126.MA_NGUON_NSNN, COT126.MA_CHUONG, COT126.GNDDA ,COT126.LK_TDN, COT126.KHN, COT3.HOANUNG_NT,COT126.TEN_DVQHNS) COT1236
        LEFT JOIN
        (SELECT NVL(SUM(CHI.ACCOUNTED_CR),0) AS HOANUNG, CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS FROM  
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN ,ACCOUNTED_CR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''1713''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS,ACCOUNTED_CR)CHI INNER JOIN 
        (SELECT AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR FROM (SELECT A.MA_DVQHNS, A.MA_CHUONG, A.MA_NGUON_NSNN, A.TEN_DVQHNS, (CASE WHEN B.ACCOUNTED_DR < 0 THEN 0 ELSE A.ACCOUNTED_DR END) AS ACCOUNTED_DR FROM 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR > 0)A LEFT JOIN
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, ACCOUNTED_DR, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%'' AND ACCOUNTED_DR < 0)B
        ON A.MA_DVQHNS = B.MA_DVQHNS AND A.MA_CHUONG = B.MA_CHUONG AND A.MA_NGUON_NSNN = B.MA_NGUON_NSNN AND A.TEN_DVQHNS = B.TEN_DVQHNS AND ABS(A.ACCOUNTED_DR) = ABS(B.ACCOUNTED_DR))AB
        GROUP BY AB.MA_DVQHNS, AB.MA_CHUONG, AB.MA_NGUON_NSNN, AB.TEN_DVQHNS, AB.ACCOUNTED_DR)DT ON 
        CHI.MA_DVQHNS = DT.MA_DVQHNS AND CHI.ACCOUNTED_CR = DT.ACCOUNTED_DR AND CHI.MA_CHUONG = DT.MA_CHUONG
        GROUP BY CHI.MA_DVQHNS, CHI.MA_NGUON_NSNN, CHI.MA_CHUONG, CHI.TEN_DVQHNS) COT4 ON COT1236.MA_DVQHNS = COT4.MA_DVQHNS AND COT1236.MA_NGUON_NSNN = COT4.MA_NGUON_NSNN AND COT1236.MA_CHUONG = COT4.MA_CHUONG
        GROUP BY COT1236.MA_DVQHNS, COT1236.MA_NGUON_NSNN, COT1236.MA_CHUONG, COT1236.GNDDA ,COT1236.LK_TDN, COT1236.KHN, COT1236.HOANUNG_NT,COT4.HOANUNG,COT1236.TEN_DVQHNS) COT12346
        LEFT JOIN 
        (SELECT MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN, NVL(SUM(ACCOUNTED_DR),0) AS GNNKH, TEN_DVQHNS
        FROM PHA_HACHTOAN_CHI WHERE NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'') AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND
        NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') AND MA_TKTN LIKE ''8%''
        GROUP BY MA_DVQHNS, MA_CHUONG, MA_NGUON_NSNN,TEN_DVQHNS) COT5 
        ON COT12346.MA_DVQHNS = COT5.MA_DVQHNS AND COT12346.MA_NGUON_NSNN = COT5.MA_NGUON_NSNN AND COT12346.MA_CHUONG = COT5.MA_CHUONG 
        GROUP BY COT12346.MA_DVQHNS, COT12346.MA_NGUON_NSNN, COT12346.MA_CHUONG, COT12346.LK_TDN, COT12346.KHN,COT12346.HOANUNG_NT, COT12346.HOANUNG, COT5.GNNKH, COT12346.GNDDA, COT12346.TEN_DVQHNS)
        WHERE MA_DVQHNS LIKE ''7%'' AND MA_CHUONG BETWEEN ''405'' AND ''599'' AND NOT MA_NGUON_NSNN LIKE ''00''
        GROUP BY MA_CHUONG,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS ';
       DBMS_OUTPUT.ENABLE (buffer_size => NULL);
      DBMS_OUTPUT.put_line (QUERY_STR1); 
    QUERY_STR7:= ' SELECT * FROM ('||QUERY_STR||')
    UNION 
    SELECT * FROM ('||QUERY_STR1||')
    UNION 
    SELECT * FROM ('||QUERY_STR2||')
    UNION 
    SELECT * FROM ('||QUERY_STR3||')
    UNION 
    SELECT * FROM ('||QUERY_STR4||')
    UNION 
    SELECT * FROM ('||QUERY_STR5||')
   
    ';
    
BEGIN


OPEN cur FOR QUERY_STR7;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
    DBMS_OUTPUT.ENABLE (buffer_size => NULL);
      DBMS_OUTPUT.put_line (SQLERRM); 
END;    
END PHA_DTBG_01;