// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _17122018_Add2ColumnInPHF_TTB_NHATKY_ThanhND : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17122018_Add2ColumnInPHF_TTB_NHATKY_ThanhND));
        
        string IMigrationMetadata.Id
        {
            get { return "201812170757389_17122018_Add2ColumnInPHF_TTB_NHATKY_ThanhND"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
