// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _23122018_Add_TieuChiDanhGiaRuiRo_dvc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23122018_Add_TieuChiDanhGiaRuiRo_dvc));
        
        string IMigrationMetadata.Id
        {
            get { return "201812230946555_23122018_Add_TieuChiDanhGiaRuiRo_dvc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
