// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12122018_AddColumn_PHF_NhatKy_ThanhND : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12122018_AddColumn_PHF_NhatKy_ThanhND));
        
        string IMigrationMetadata.Id
        {
            get { return "201812120349357_12122018_AddColumn_PHF_NhatKy_ThanhND"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
