// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12122018_updateDVSN_HT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12122018_updateDVSN_HT));
        
        string IMigrationMetadata.Id
        {
            get { return "201812120252078_12122018_updateDVSN_HT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
