// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _08122018_update_tbl_PHA_KBQT82_KBQT01_add_COLUMN_NAM_hungvv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08122018_update_tbl_PHA_KBQT82_KBQT01_add_COLUMN_NAM_hungvv));
        
        string IMigrationMetadata.Id
        {
            get { return "201812080258239_08122018_update_tbl_PHA_KBQT82_KBQT01_add_COLUMN_NAM_hungvv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
