// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _15122018_add_column_MA_DBHC_dm_TKKHOBAC_hungvv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15122018_add_column_MA_DBHC_dm_TKKHOBAC_hungvv));
        
        string IMigrationMetadata.Id
        {
            get { return "201812150209447_15122018_add_column_MA_DBHC_dm_TKKHOBAC_hungvv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
