create or replace PROCEDURE "PHA_THQTNSX_TT_BG" (P_MA_DBHC IN NVARCHAR2, P_CONGTHUC VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE, DONVI_TIEN number, cur OUT SYS_REFCURSOR) as
  QUERY_STR  CLOB; 
   P_CT VARCHAR2(32767);   
    P_SELECT_DBHC VARCHAR2(32767);

   --CHI 
   CT_46000_NSNN VARCHAR2(32767);   CT_46000_NSX VARCHAR2(32767);   CT_71000_NSNN VARCHAR2(32767);   CT_71000_NSX VARCHAR2(32767); CT_47010_NSNN VARCHAR2(32767); CT_47010_NSX VARCHAR2(32767);
   CT_33000_NSNN VARCHAR2(32767);   CT_33000_NSX VARCHAR2(32767);   CT_38000_NSNN VARCHAR2(32767);   CT_38000_NSX VARCHAR2(32767);
   CT_58000_NSNN VARCHAR2(32767);   CT_58000_NSX VARCHAR2(32767);   CT_39000_NSNN VARCHAR2(32767);   CT_39000_NSX VARCHAR2(32767);
   CT_80000_NSNN VARCHAR2(32767);   CT_80000_NSX VARCHAR2(32767);    CT_45000_NSNN VARCHAR2(32767);   CT_45000_NSX VARCHAR2(32767);    CT_65110_NSNN VARCHAR2(32767);
   CT_65110_NSX VARCHAR2(32767);   CT_65120_NSNN VARCHAR2(32767);    CT_65120_NSX VARCHAR2(32767);   CT_40000_NSNN VARCHAR2(32767);    CT_40000_NSX VARCHAR2(32767);
   CT_32110_NSNN VARCHAR2(32767);   CT_32110_NSX VARCHAR2(32767);    CT_35000_NSNN VARCHAR2(32767);
   CT_35000_NSX VARCHAR2(32767);   CT_32150_NSNN VARCHAR2(32767);   CT_32150_NSX VARCHAR2(32767);   CT_32130_NSNN VARCHAR2(32767);CT_32130_NSX VARCHAR2(32767);CT_36000_NSNN VARCHAR2(32767);
   CT_36000_NSX VARCHAR2(32767);   
   BEGIN
    IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
        select STC_PA_SYS.FNC_CONVERT_FORMULA_HCSN(P_CONGTHUC) INTO P_CT from dual;       
        P_CT:= ' AND ' || P_CT;
    END IF;

    --Gán công thức 
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_46000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='46000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_46000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='46000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_71000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='71000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_71000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='71000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_47010_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='47010_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_47010_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='47010_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_33000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='33000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_33000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='33000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_38000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='38000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_38000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='38000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_58000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='58000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_58000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='58000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_39000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='39000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_39000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='39000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_80000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='80000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_80000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='80000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_45000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='45000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_45000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='45000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_65110_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='65110_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_65110_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='65110_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_65120_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='65120_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_65120_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='65120_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_40000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='40000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_40000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='40000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_32110_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='32110_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_32110_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='32110_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_35000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='35000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_35000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='35000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_32150_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='32150_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_32150_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='32150_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_32130_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='32130_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_32130_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='32130_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_36000_NSNN from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='36000_NSNN' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_36000_NSX from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='THQTNSX_TT' AND MA_COT='36000_NSX' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');

        P_SELECT_DBHC:= ' AND A.MA_DIABAN IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||''') OR MA_DBHC_CHA IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||'''))';

        IF(P_SELECT_DBHC IS NOT NULL) THEN
        P_CT:=P_CT || P_SELECT_DBHC;
        ELSE
        P_CT:=P_CT;
        END IF;
           QUERY_STR:=' SELECT QT.MA_DIABAN, QT.TEN_DIABAN
                                , NVL(QT.CT_46000_NSNN,0) as CT_46000_NSNN, NVL(QT.CT_46000_NSX,0) as CT_46000_NSX, NVL(QT.CT_71000_NSNN,0) as CT_71000_NSNN, NVL(QT.CT_71000_NSX,0) as CT_71000_NSX
                                , NVL(QT.CT_47010_NSNN,0) as CT_47010_NSNN, NVL(QT.CT_47010_NSX,0) as CT_47010_NSX, NVL(QT.CT_33000_NSNN,0) as CT_33000_NSNN, NVL(QT.CT_33000_NSX,0) as CT_33000_NSX
                                , NVL(QT.CT_38000_NSNN,0) as CT_38000_NSNN, NVL(QT.CT_38000_NSX,0) as CT_38000_NSX, NVL(QT.CT_58000_NSNN,0) as CT_58000_NSNN, NVL(QT.CT_58000_NSX,0) as CT_58000_NSX
                                , NVL(QT.CT_39000_NSNN,0) as CT_39000_NSNN, NVL(QT.CT_39000_NSX,0) as CT_39000_NSX, NVL(QT.CT_80000_NSNN,0) as CT_80000_NSNN, NVL(QT.CT_80000_NSX,0) as CT_80000_NSX
                                , NVL(QT.CT_45000_NSNN,0) as CT_45000_NSNN, NVL(QT.CT_45000_NSX,0) as CT_45000_NSX, NVL(QT.CT_65110_NSNN,0) as CT_65110_NSNN, NVL(QT.CT_65110_NSX,0) as CT_65110_NSX
                                , NVL(QT.CT_65120_NSNN,0) as CT_65120_NSNN, NVL(QT.CT_65120_NSX,0) as CT_65120_NSX, NVL(QT.CT_40000_NSNN,0) as CT_40000_NSNN, NVL(QT.CT_40000_NSX,0) as CT_40000_NSX
                                , NVL(QT.CT_32110_NSNN,0) as CT_32110_NSNN, NVL(QT.CT_32110_NSX,0) as CT_32110_NSX, NVL(QT.CT_35000_NSNN,0) as CT_35000_NSNN, NVL(QT.CT_35000_NSX,0) as CT_35000_NSX
                                , NVL(QT.CT_32150_NSNN,0) as CT_32150_NSNN, NVL(QT.CT_32150_NSX,0) as CT_32150_NSX, NVL(QT.CT_32130_NSNN,0) as CT_32130_NSNN, NVL(QT.CT_32130_NSX,0) as CT_32130_NSX
                                , NVL(QT.CT_36000_NSNN,0) as CT_36000_NSNN, NVL(QT.CT_36000_NSX,0) as CT_36000_NSX
                                FROM
                        (SELECT A.MA_DIABAN, A.TEN_DIABAN
                                ,NVL(SUM (CASE WHEN ('|| CT_46000_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_46000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_46000_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_46000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_71000_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_71000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_71000_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_71000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_47010_NSNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_47010_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_47010_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_47010_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_33000_NSNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_33000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_33000_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_33000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_38000_NSNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_38000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_38000_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_38000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_58000_NSNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_58000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_58000_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_58000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_39000_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_39000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_39000_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_39000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_80000_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_80000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_80000_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_80000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_45000_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_45000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_45000_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_45000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_65110_NSNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_65110_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_65110_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_65110_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_65120_NSNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_65120_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_65120_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_65120_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_40000_NSNN ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_40000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_40000_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_40000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_32110_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_32110_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_32110_NSX ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_32110_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_35000_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_35000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_35000_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_35000_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_32150_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_32150_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_32150_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_32150_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_32130_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_32130_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_32130_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_32130_NSX
                                ,NVL(SUM (CASE WHEN ('|| CT_36000_NSNN ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_36000_NSNN
                                ,NVL(SUM (CASE WHEN ('|| CT_36000_NSX ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CT_36000_NSX
                         FROM PHA_HACHTOAN_THU A
                        WHERE A.NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')
                        AND A.NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')     
                        and A.NGAY_KET_SO <=TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                        and A.NGAY_KET_SO >=TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') '|| P_CT ||' 
                        GROUP BY A.MA_DIABAN, A.TEN_DIABAN
                        ) QT 

                        WHERE 1=1 AND (QT.CT_46000_NSNN <> 0 OR QT.CT_46000_NSX <> 0 OR QT.CT_71000_NSNN <> 0 OR QT.CT_71000_NSX <> 0 OR QT.CT_47010_NSNN<> 0 OR QT.CT_47010_NSX <> 0
                            OR QT.CT_33000_NSNN <> 0 OR QT.CT_33000_NSX <> 0 OR QT.CT_38000_NSNN <> 0 OR QT.CT_38000_NSX <>0 OR QT.CT_58000_NSNN <> 0 OR QT.CT_58000_NSX <> 0 OR QT.CT_39000_NSNN <> 0
                            OR QT.CT_39000_NSX <>0 OR QT.CT_80000_NSNN <> 0 OR QT.CT_80000_NSX <> 0 OR QT.CT_45000_NSNN <> 0 OR QT.CT_45000_NSX <> 0 OR QT.CT_65110_NSNN <> 0 OR QT.CT_65110_NSX<> 0
                            OR QT.CT_65120_NSNN <> 0 OR QT.CT_65120_NSX <> 0 OR QT.CT_40000_NSNN <> 0 OR QT.CT_40000_NSX <> 0 OR QT.CT_32110_NSNN <>0 OR QT.CT_32110_NSX <> 0 OR QT.CT_35000_NSNN <> 0 
                            OR QT.CT_35000_NSX <> 0 OR QT.CT_32150_NSNN <> 0 OR QT.CT_32150_NSX <> 0 OR QT.CT_32130_NSNN <> 0 OR QT.CT_32130_NSX <>0 OR QT.CT_36000_NSNN <> 0 OR QT.CT_36000_NSX <> 0 
                            ) ORDER BY QT.MA_DIABAN';
  DBMS_OUTPUT.put_line (QUERY_STR); 
BEGIN
EXECUTE IMMEDIATE QUERY_STR;
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      --DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
END;    
END PHA_THQTNSX_TT_BG;