create or replace PROCEDURE PHA_BCCT_R_C_DVQHNS_V1(P_MABAOCAO IN VARCHAR2,TABLENAME_TH IN VARCHAR2, P_TABLENAME IN VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE, MaDVNSThap IN NVARCHAR2, P_CONGTHUC IN NVARCHAR2, DONVI_TIEN NUMBER, cur OUT SYS_REFCURSOR)IS
QUERY_STR  VARCHAR2(32767);
SQL_QUERRY_DUTOAN VARCHAR2(32767);
P_MA_BAOCAO VARCHAR2(100);
P_SQL_CREATE_TABLE_TH VARCHAR2(32767);
P_SQL_CREATE_TABLE VARCHAR2(32767);
v_SQL_Clo VARCHAR2(32767);
v_SQL_Clo_2 VARCHAR2(32767);
INSERT_QUERRY_CHI VARCHAR2(32767);
INSERT_QUERRY_THU VARCHAR2(32767);
TABLE_PHA_DT_CHI VARCHAR2(100);
TABLE_PHA_DT_THU VARCHAR2(100);
SQL_QUERRY VARCHAR2(32767);
P_SQL_DELETE VARCHAR2(32767);
N_COUNT NUMBER(17,4):=0;
P_DONVI_TIEN NUMBER(17,4):=1;
P_CT VARCHAR2(32767); 
--P_SUM VARCHAR2(32767);
P_SUM clob;
--P_SUM_U VARCHAR2(32767);
P_WHERE_C_R VARCHAR2(32767);
--P_INSERT_C_R VARCHAR2(32767);
P_INSERT_C_R clob;
--P_UPDATE_C_R VARCHAR2(32767);
P_TABLENAME_TH VARCHAR2(100);
P_CT_SUM VARCHAR2(1000);

--P_SQL_INSERT VARCHAR2(32767);

P_WHERE_DATE_HL_TU VARCHAR2(100); P_WHERE_DATE_HL_DEN VARCHAR2(100); P_WHERE_DATE_KS_TU VARCHAR2(100); P_WHERE_DATE_KS_DEN VARCHAR2(100);
BEGIN

IF(TABLENAME_TH IS NULL OR LENGTH(TABLENAME_TH)<=0) THEN P_TABLENAME_TH:='PHA_TH_MLNS'; 
     ELSE P_TABLENAME_TH:=TABLENAME_TH;
     END IF;
    
    IF(DONVI_TIEN IS NULL OR DONVI_TIEN=0) THEN P_DONVI_TIEN:=1; 
     ELSE P_DONVI_TIEN:=DONVI_TIEN;
     END IF;
     -- TAO TABLE DE TONG HOP DU LIEU
        P_MA_BAOCAO:=''''||P_MABAOCAO||'''';   
        IF TRIM(P_CONGTHUC) IS NOT NULL THEN
            SELECT STC_PA_SYS.FNC_CONVERT_FORMULA(P_CONGTHUC) INTO P_CT FROM dual;
            --P_SQL_INSERT:= ' '||P_SQL_INSERT ||' and '||P_CT;

        END IF;
  P_SQL_CREATE_TABLE_TH := 'CREATE TABLE '||P_TABLENAME_TH||'(
        PHA_TABLE NVARCHAR2(100),MA_TKTN NVARCHAR2(100), MA_DIABAN NVARCHAR2(100), MA_CAP NVARCHAR2(100),MA_CHUONG NVARCHAR2(100),MA_NGANHKT NVARCHAR2(100),MA_LOAI NVARCHAR2(100),
        MA_TIEUMUC NVARCHAR2(100), MA_MUC NVARCHAR2(100), MA_TIEUNHOM NVARCHAR2(100),MA_CTMTQG NVARCHAR2(100),MA_KBNN NVARCHAR2(100), NGAY_HIEU_LUC DATE, NGAY_KET_SO DATE, LOAI_DU_TOAN NVARCHAR2(100),
        MA_NGUON_NSNN NVARCHAR2(100),MA_DVQHNS NVARCHAR2(100), MA_NVC NVARCHAR2(100), GIA_TRI_HACH_TOAN NUMBER)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC"';                      

       -- table PHA_HACHTOAN_THU              
        TABLE_PHA_DT_THU:='PHA_HACHTOAN_THU';
        SQL_QUERRY := 'SELECT '''||TABLE_PHA_DT_THU||'''  ,MA_TKTN,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS,MA_NVC
        ,TO_DATE(to_char(NGAY_HIEU_LUC,''ddMMyyyy''), ''ddMMyyyy''),TO_DATE (to_char(NGAY_KET_SO,''ddMMyyyy''), ''ddMMyyyy''),ATTRIBUTE8
        ,SUM (GIA_TRI_HACH_TOAN) FROM '||TABLE_PHA_DT_THU||' VC WHERE VC.NGAY_HIEU_LUC >= '''||TUNGAY_HL||''' 
              AND VC.NGAY_HIEU_LUC <= '''||DENNGAY_HL||''' AND VC.NGAY_KET_SO >= '''||TUNGAY_KS||''' AND ' ||' VC.NGAY_KET_SO <= '''||DENNGAY_KS||'''
         GROUP BY  MA_TKTN,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN, MA_NGUON_NSNN,MA_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,ATTRIBUTE8';   
        INSERT_QUERRY_THU := 'INSERT INTO '||P_TABLENAME_TH||'(PHA_TABLE,MA_TKTN ,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,LOAI_DU_TOAN,GIA_TRI_HACH_TOAN)('||SQL_QUERRY||')';
        
        
        -- table PHA_HACHTOAN_CHI
        TABLE_PHA_DT_CHI:='PHA_HACHTOAN_CHI';
        SQL_QUERRY := 'SELECT '''||TABLE_PHA_DT_CHI||'''  ,MA_TKTN ,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS,MA_NVC
        ,TO_DATE(to_char(NGAY_HIEU_LUC,''ddMMyyyy''), ''ddMMyyyy''),TO_DATE (to_char(NGAY_KET_SO,''ddMMyyyy''), ''ddMMyyyy''), ATTRIBUTE8
        ,SUM (GIA_TRI_HACH_TOAN) FROM '||TABLE_PHA_DT_CHI||' VC WHERE VC.NGAY_HIEU_LUC >= '''||TUNGAY_HL||''' 
              AND VC.NGAY_HIEU_LUC <= '''||DENNGAY_HL||''' AND VC.NGAY_KET_SO >= '''||TUNGAY_KS||''' AND ' ||' VC.NGAY_KET_SO <= '''||DENNGAY_KS||'''
         GROUP BY  MA_TKTN,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,ATTRIBUTE8';   
         --DBMS_OUTPUT.put_line ('INSERT_QUERRY_CHI:=' ||  SQL_QUERRY );
        INSERT_QUERRY_CHI := 'INSERT INTO '||P_TABLENAME_TH||'(PHA_TABLE,MA_TKTN ,MA_DIABAN,MA_CAP,MA_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,LOAI_DU_TOAN,GIA_TRI_HACH_TOAN)('||SQL_QUERRY||')';
    BEGIN
        SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = UPPER(P_TABLENAME_TH);
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
    END;

    IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
    BEGIN

        EXECUTE IMMEDIATE P_SQL_CREATE_TABLE_TH;  
       -- DBMS_OUTPUT.put_line ('INSERT_QUERRY_THU:=' ||  INSERT_QUERRY_THU );
        EXECUTE IMMEDIATE INSERT_QUERRY_THU;  
        --DBMS_OUTPUT.put_line ('INSERT_QUERRY_CHI:=' ||  INSERT_QUERRY_CHI );
        EXECUTE IMMEDIATE INSERT_QUERRY_CHI;  
    END;
    END IF;


FOR item IN(SELECT MA_COT FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO = P_MABAOCAO ORDER BY STT ASC)
    LOOP
        v_SQL_Clo:= v_SQL_Clo || item.MA_COT ||' NUMBER, ';
        v_SQL_Clo_2:= v_SQL_Clo_2 || item.MA_COT ||', ';
        
    END LOOP;
    --- table 2
    P_SQL_CREATE_TABLE := 'CREATE  TABLE '||P_TABLENAME||'(MA_CHUONG NVARCHAR2(100), MA_XA NVARCHAR2(50),MA_DVQHNS NVARCHAR2(50), TEN_DVQHNS NVARCHAR2(500),' 
                        ||v_SQL_Clo||' MA_HUYEN NVARCHAR2(50))SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BTSTC"'; 
     BEGIN
        SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = UPPER(P_TABLENAME);
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
      END;
      IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
      BEGIN
          EXECUTE IMMEDIATE P_SQL_CREATE_TABLE;  
      END;
      END IF;
      -- TAO TABLE 2
        P_WHERE_DATE_HL_TU:= ' AND NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')';
        P_WHERE_DATE_HL_DEN:= ' AND NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')';        
        P_WHERE_DATE_KS_TU:= ' AND NGAY_KET_SO >= TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')';
        P_WHERE_DATE_KS_DEN:= ' AND NGAY_KET_SO <= TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' ||P_TABLENAME;
    FOR item_R IN(SELECT MA_CHUONG,MA_HUYEN,MA_XA,MA_DVQHNS,TEN_DVQHNS, ('MA_DVQHNS= ''' || MA_DVQHNS ||'''' )AS CONGTHUC_WHERE FROM SYS_DVQHNS
    WHERE (MA_DVQHNS='' || MaDVNSThap || '' OR MA_DVQHNS_CHA='' || MaDVNSThap || ''))
    LOOP

         BEGIN
                P_INSERT_C_R:= 'INSERT INTO '|| P_TABLENAME ||'(MA_CHUONG,MA_HUYEN,MA_XA,MA_DVQHNS,'||v_SQL_Clo_2||'TEN_DVQHNS)';
                P_INSERT_C_R:=P_INSERT_C_R || 'VALUES('''|| item_R.MA_CHUONG ||''','''|| item_R.MA_HUYEN ||''','''|| item_R.MA_XA ||''','''|| item_R.MA_DVQHNS ||''',';
                FOR item_C IN(SELECT MA_COT, CONGTHUC_WHERE FROM DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO= P_MABAOCAO)
                    LOOP
                          P_SUM:='SELECT NVL(SUM(GIA_TRI_HACH_TOAN),0) FROM '||P_TABLENAME_TH||' WHERE ' || P_CT || P_WHERE_DATE_HL_TU ||  P_WHERE_DATE_HL_DEN || P_WHERE_DATE_KS_TU ||  P_WHERE_DATE_KS_DEN || ' AND ';
                          if(LENGTH(item_C.CONGTHUC_WHERE)>0) THEN P_WHERE_C_R:=TRIM(item_R.CONGTHUC_WHERE) || ' AND ' || TRIM(item_C.CONGTHUC_WHERE); END IF;                          
                          if(LENGTH(item_C.CONGTHUC_WHERE)<=0) THEN P_WHERE_C_R:=TRIM(item_R.CONGTHUC_WHERE); END IF;
                          if(LENGTH(P_WHERE_C_R)>0) THEN P_SUM:='(' || P_SUM|| TRIM(P_WHERE_C_R) || ')';
                            ELSE P_SUM:='(' || P_SUM|| ')'; 
                          END IF;
                            P_INSERT_C_R:=P_INSERT_C_R || P_SUM ||',';
                    END LOOP;
                     --DBMS_OUTPUT.put_line ('t3:=' ||  P_INSERT_C_R );
                P_INSERT_C_R:=P_INSERT_C_R || '''' || item_R.TEN_DVQHNS || '''' ||')';
               
                EXECUTE IMMEDIATE P_INSERT_C_R; 

            END;      
END LOOP; 

    -- IN RA MAM HINH
    BEGIN
      QUERY_STR:='SELECT TH.*, CH.TEN_CHUONG FROM ' ||P_TABLENAME||' TH LEFT JOIN DM_CHUONG CH ON TH.MA_CHUONG = CH.MA_CHUONG where 1=1 order by TH.MA_DVQHNS ASC';
      OPEN cur FOR QUERY_STR;
EXCEPTION
 WHEN NO_DATA_FOUND
  THEN
          DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
          WHEN OTHERS
          THEN DBMS_OUTPUT.put_line('-');
END;	

END PHA_BCCT_R_C_DVQHNS_V1;