CREATE GLOBAL TEMPORARY TABLE "BTSTC"."PHC_TEMP_NHATKY_SOCAI"
   (	"TAIKHOAN_NO" NVARCHAR2(10), 
	"TAIKHOAN_CO" NVARCHAR2(10), 
	"THANG" NUMBER(18,2), 
	"NGAY_HT" DATE, 
	"NGAY_CT" DATE, 
	"SO_CHUNGTU" NVARCHAR2(50), 
	"MA_CHUNGTU" NVARCHAR2(50), 
	"SO_CHUNGTU_DETAIL" NVARCHAR2(50), 
	"DIENGIAI" NVARCHAR2(500), 
	"SOTIEN_NO" NUMBER(18,2), 
	"SOTIEN_CO" NUMBER(18,2), 
	"SODU_DAUKY_NO" NUMBER(18,2), 
	"SODU_DAUKY_CO" NUMBER(18,2), 
	"SO_PHATSINH_NO" NUMBER(18,2), 
	"SO_PHATSINH_CO" NUMBER(18,2), 
	"SODU_CUOIKY_NO" NUMBER(18,2), 
	"SODU_CUOIKY_CO" NUMBER(18,2), 
	"LUYKE_NO" NUMBER(18,2), 
	"LUYKE_CO" NUMBER(18,2), 
	"USER_NAME" NVARCHAR2(50)
   ) ON COMMIT PRESERVE ROWS;
/ 
