create or replace PROCEDURE "PHB_B02BCQT_SUMREPORT" 
(
  MACHUONG IN NVARCHAR2,
  NAMBC IN NUMBER,
  KYBC IN NUMBER,
  DSDVQHNS IN NVARCHAR2,
  CUR OUT SYS_REFCURSOR
)IS
P_QUERY VARCHAR2(32767);
TEMP_DVQHNS  VARCHAR2(32767);
TEMP_CHUONG  VARCHAR2(32767);
BEGIN
    IF DSDVQHNS IS NOT NULL THEN TEMP_DVQHNS:= ' AND TH.MA_QHNS IN('||DSDVQHNS||')';
    ELSE TEMP_DVQHNS:= '';
    END IF;
    IF MACHUONG IS NOT NULL THEN TEMP_CHUONG:= ' AND TH.MA_CHUONG='''||MACHUONG||'''';
    ELSE TEMP_CHUONG:= '';
    END IF;

    P_QUERY:='
    SELECT * FROM (
        select Cast(''I'' as nvarchar2(15)) as STT_CHI_TIEU,Cast(''Ki?n ngh? c?a ki?m toán, thanh tra, co quan tài chính các nam tru?c còn t?n t?i chua x? lý'' as nvarchar2(255)) as TEN_CHI_TIEU
                    ,Cast('''' as nvarchar2(50)) as MA_CHI_TIEU_CHA, Cast('''' as nvarchar2(50)) as MA_CHI_TIEU, Cast('''' as nvarchar2(20)) as PHAN
                    ,Cast(NULL as NUMBER(10,0)) as SKN_TONGSO, Cast(NULL as NUMBER(10,0)) as SKN_THANHTRA, Cast(NULL as NUMBER(10,0)) as SKN_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SKN_TAICHINH
                    ,Cast(NULL as NUMBER(10,0)) as SDXL_TONGSO, Cast(NULL as NUMBER(10,0)) as SDXL_THANHTRA, Cast(NULL as NUMBER(10,0)) as SDXL_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SDXL_TAICHINH
                    ,Cast(NULL as NUMBER(10,0)) as SCXL_TONGSO, Cast(NULL as NUMBER(10,0)) as SCXL_THANHTRA, Cast(NULL as NUMBER(10,0)) as SCXL_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SCXL_TAICHINH
            from dual 
        )
    union all
    SELECT * FROM (        
        SELECT CT.STT_CHI_TIEU, CT.TEN_CHI_TIEU, CT.MA_CHI_TIEU_CHA, CT.MA_CHI_TIEU, CT.PHAN
            ,SUM(CT.SKN_TONGSO) AS SKN_TONGSO,SUM(CT.SKN_THANHTRA) AS SKN_THANHTRA,SUM(CT.SKN_KIEMTOAN) AS SKN_KIEMTOAN, SUM(CT.SKN_TAICHINH) AS SKN_TAICHINH
            ,SUM(CT.SDXL_TONGSO) AS SDXL_TONGSO,SUM(CT.SDXL_THANHTRA) AS SDXL_THANHTRA,SUM(CT.SDXL_KIEMTOAN) AS SDXL_KIEMTOAN, SUM(CT.SDXL_TAICHINH) AS SDXL_TAICHINH
            ,SUM(CT.SCXL_TONGSO) AS SCXL_TONGSO,SUM(CT.SCXL_THANHTRA) AS SCXL_THANHTRA,SUM(CT.SCXL_KIEMTOAN) AS SCXL_KIEMTOAN, SUM(CT.SCXL_TAICHINH) AS SCXL_TAICHINH
        FROM PHB_B02BCQT TH INNER JOIN SYS_DVQHNS DVQHNS ON TH.MA_QHNS=DVQHNS.MA_DVQHNS INNER JOIN PHB_B02BCQT_DETAIL CT ON CT.PHB_B02BCQT_REFID = TH.REFID
        WHERE (TH.NAM_BC=CASE '||NAMBC||' WHEN -1 THEN TH.NAM_BC ELSE '||NAMBC||' END) AND (TH.KY_BC=CASE '||KYBC||' WHEN -1 THEN TH.KY_BC ELSE '||KYBC||' END) AND DVQHNS.TRANG_THAI=''A'' AND CT.PHAN IN (''11'',''12'',''13'',''14'')'
            || TEMP_DVQHNS
            || TEMP_CHUONG
            || ' GROUP BY CT.STT_CHI_TIEU, CT.TEN_CHI_TIEU, CT.MA_CHI_TIEU_CHA, CT.MA_CHI_TIEU, CT.PHAN
                ORDER BY CT.PHAN, CT.STT_CHI_TIEU, CT.MA_CHI_TIEU
        )
    union all
    SELECT * FROM (
        select Cast(''II'' as nvarchar2(15)) as STT_CHI_TIEU,Cast(''Ki?n ngh? c?a ki?m toán, thanh tra, co quan quan tài chính nam nay'' as nvarchar2(255)) as TEN_CHI_TIEU
                    ,Cast('''' as nvarchar2(50)) as MA_CHI_TIEU_CHA, Cast('''' as nvarchar2(50)) as MA_CHI_TIEU, Cast('''' as nvarchar2(20)) as PHAN
                    ,Cast(NULL as NUMBER(10,0)) as SKN_TONGSO, Cast(NULL as NUMBER(10,0)) as SKN_THANHTRA, Cast(NULL as NUMBER(10,0)) as SKN_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SKN_TAICHINH
                    ,Cast(NULL as NUMBER(10,0)) as SDXL_TONGSO, Cast(NULL as NUMBER(10,0)) as SDXL_THANHTRA, Cast(NULL as NUMBER(10,0)) as SDXL_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SDXL_TAICHINH
                    ,Cast(NULL as NUMBER(10,0)) as SCXL_TONGSO, Cast(NULL as NUMBER(10,0)) as SCXL_THANHTRA, Cast(NULL as NUMBER(10,0)) as SCXL_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SCXL_TAICHINH
            from dual 
        )
    union all
    SELECT * FROM (        
        SELECT CT.STT_CHI_TIEU, CT.TEN_CHI_TIEU, CT.MA_CHI_TIEU_CHA, CT.MA_CHI_TIEU, CT.PHAN
            ,SUM(CT.SKN_TONGSO) AS SKN_TONGSO,SUM(CT.SKN_THANHTRA) AS SKN_THANHTRA,SUM(CT.SKN_KIEMTOAN) AS SKN_KIEMTOAN, SUM(CT.SKN_TAICHINH) AS SKN_TAICHINH
            ,SUM(CT.SDXL_TONGSO) AS SDXL_TONGSO,SUM(CT.SDXL_THANHTRA) AS SDXL_THANHTRA,SUM(CT.SDXL_KIEMTOAN) AS SDXL_KIEMTOAN, SUM(CT.SDXL_TAICHINH) AS SDXL_TAICHINH
            ,SUM(CT.SCXL_TONGSO) AS SCXL_TONGSO,SUM(CT.SCXL_THANHTRA) AS SCXL_THANHTRA,SUM(CT.SCXL_KIEMTOAN) AS SCXL_KIEMTOAN, SUM(CT.SCXL_TAICHINH) AS SCXL_TAICHINH
        FROM PHB_B02BCQT TH INNER JOIN SYS_DVQHNS DVQHNS ON TH.MA_QHNS=DVQHNS.MA_DVQHNS INNER JOIN PHB_B02BCQT_DETAIL CT ON CT.PHB_B02BCQT_REFID = TH.REFID
        WHERE (TH.NAM_BC=CASE '||NAMBC||' WHEN -1 THEN TH.NAM_BC ELSE '||NAMBC||' END) AND (TH.KY_BC=CASE '||KYBC||' WHEN -1 THEN TH.KY_BC ELSE '||KYBC||' END) AND DVQHNS.TRANG_THAI=''A'' AND CT.PHAN IN (''21'',''22'',''23'',''24'')'
            || TEMP_DVQHNS
            || TEMP_CHUONG
            || ' GROUP BY CT.STT_CHI_TIEU, CT.TEN_CHI_TIEU, CT.MA_CHI_TIEU_CHA, CT.MA_CHI_TIEU, CT.PHAN
                ORDER BY CT.PHAN, CT.STT_CHI_TIEU, CT.MA_CHI_TIEU
        )
    union all
    SELECT * FROM (
        select Cast(''III'' as nvarchar2(15)) as STT_CHI_TIEU,Cast(''Các v?n d? khác liên quan c?n gi?i trình'' as nvarchar2(255)) as TEN_CHI_TIEU
                    ,Cast('''' as nvarchar2(50)) as MA_CHI_TIEU_CHA, Cast('''' as nvarchar2(50)) as MA_CHI_TIEU, Cast('''' as nvarchar2(20)) as PHAN
                    ,Cast(NULL as NUMBER(10,0)) as SKN_TONGSO, Cast(NULL as NUMBER(10,0)) as SKN_THANHTRA, Cast(NULL as NUMBER(10,0)) as SKN_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SKN_TAICHINH
                    ,Cast(NULL as NUMBER(10,0)) as SDXL_TONGSO, Cast(NULL as NUMBER(10,0)) as SDXL_THANHTRA, Cast(NULL as NUMBER(10,0)) as SDXL_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SDXL_TAICHINH
                    ,Cast(NULL as NUMBER(10,0)) as SCXL_TONGSO, Cast(NULL as NUMBER(10,0)) as SCXL_THANHTRA, Cast(NULL as NUMBER(10,0)) as SCXL_KIEMTOAN, Cast(NULL as NUMBER(10,0)) as SCXL_TAICHINH
            from dual 
        )
        '; 

    DBMS_OUTPUT.put_line(P_QUERY); 

    OPEN cur FOR P_QUERY;
END "PHB_B02BCQT_SUMREPORT";