create or replace PROCEDURE PHA_B11_DADTTP (P_MA_DBHC IN NVARCHAR2,P_CONGTHUC VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE,DONVI_TIEN number, cur OUT SYS_REFCURSOR) as
   QUERY_STR  VARCHAR2(32767); 
   P_SQL_INSERT VARCHAR2(32767);
   P_CT VARCHAR2(32767);
   V_TU_NAM VARCHAR(4):= to_char(TUNGAY_HL,'yyyy');
   P_SELECT_DBHC VARCHAR2(32767);
   BEGIN
   IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
        select STC_PA_SYS.FNC_CONVERT_FORMULA (P_CONGTHUC) INTO P_CT from dual;
        P_SQL_INSERT:= ' '||P_SQL_INSERT ||' and '||P_CT;
        END IF;
        P_SELECT_DBHC:= ' AND A.MA_DIABAN IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||''') OR MA_DBHC_CHA IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||'''))';
        IF(P_SELECT_DBHC IS NOT NULL) THEN
        P_SQL_INSERT:=P_SQL_INSERT || P_SELECT_DBHC;
        ELSE
        P_SQL_INSERT:=P_SQL_INSERT;
        END IF;

QUERY_STR:=' SELECT DBHC.MA_DBHC_CHA, CT.MA_DIABAN,CT.MA_DVQHNS,CT.TEN_DVQHNS, CT.MA_CHUONG, CT.TEN_CHUONG,CT.DUTOAN, CT.CHI, CT.UNG, CASE LENGTH(CT.MA_DIABAN) WHEN 3 THEN DBHC.TEN_DBHC
WHEN 2 THEN DBHC.TEN_DBHC ELSE (SELECT TEN_DBHC FROM DM_DBHC WHERE MA_DBHC = DBHC.MA_DBHC_CHA) END AS TEN FROM 
(SELECT HT.MA_DVQHNS, HT.TEN_DVQHNS, HT.MA_DIABAN, HT.MA_CHUONG, HT.TEN_CHUONG
                , NVL(HT.CHI,0) as CHI, NVL(HT.UNG,0) as UNG       
                ,NVL(SUM (CASE WHEN (B.MA_TKTN LIKE ''9%'' AND NOT B.MA_TKTN IN (''9557'',''9567'') 
                AND B.NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')
                AND B.NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')     
                and B.NGAY_KET_SO <=TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                and B.NGAY_KET_SO >=TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'') ) THEN B.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DUTOAN
                FROM
                ( 
                 SELECT A.MA_DVQHNS, A.TEN_DVQHNS, A.MA_DIABAN, A.MA_CHUONG, A.TEN_CHUONG
                        
                        ,NVL(SUM (CASE WHEN (A.MA_TKTN IN(''8211'',''8261'',''8941'',''8951''))     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS CHI
                        ,NVL(SUM (CASE WHEN (A.MA_TKTN IN(''1713'',''1717''))     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS UNG

                FROM PHA_HACHTOAN_CHI A 
                WHERE A.NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')
                AND A.NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')     
                and A.NGAY_KET_SO <=TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                and A.NGAY_KET_SO >=TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')  
                AND (A.MA_CHUONG LIKE ''412'' OR A.MA_CHUONG LIKE ''419'' OR A.MA_CHUONG LIKE ''160'') AND A.MA_NGUON_NSNN LIKE ''41''
                AND A.MA_DVQHNS LIKE ''7%''
                '|| P_SQL_INSERT|| ' GROUP BY A.MA_DVQHNS, A.TEN_DVQHNS, A.MA_DIABAN, A.MA_CHUONG, A.TEN_CHUONG
                ) HT LEFT JOIN PHA_DUTOAN B ON HT.MA_DVQHNS = B.MA_DVQHNS AND HT.MA_CHUONG = B.MA_CHUONG
                WHERE 1=1 AND (HT.CHI <> 0 OR HT.UNG <> 0) 
                GROUP BY HT.MA_DVQHNS, HT.TEN_DVQHNS, HT.MA_DIABAN, HT.MA_CHUONG, HT.TEN_CHUONG, HT.CHI, HT.UNG) CT 
                INNER JOIN DM_DBHC DBHC ON CT.MA_DIABAN = DBHC.MA_DBHC 
                GROUP BY DBHC.MA_DBHC_CHA, CT.MA_DIABAN,CT.MA_DVQHNS,CT.TEN_DVQHNS, CT.MA_CHUONG, CT.TEN_CHUONG,CT.DUTOAN, CT.CHI, CT.UNG, DBHC.TEN_DBHC
                ORDER BY CT.MA_CHUONG ASC, TEN DESC ,DBHC.MA_DBHC_CHA ,CT.TEN_DVQHNS ASC';
DBMS_OUTPUT.put_line (QUERY_STR);
BEGIN
OPEN cur FOR QUERY_STR;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
END;
END PHA_B11_DADTTP;