create or replace FUNCTION "PHC_FCN_ACCOUNT_BY_MER" (P_TUNGAYHL IN DATE,P_DENNGAYHL IN DATE,P_LOAICHUNGTU IN VARCHAR, P_MAVATTU IN VARCHAR,P_MAKHO IN VARCHAR,P_USERNAME IN VARCHAR,P_FIELD IN VARCHAR)
RETURN NUMBER
IS 
    V_NGAY_HT DATE;
    V_SQLQUERRY VARCHAR2(32767);
    V_SQLDELETE VARCHAR2(500);
    P_CONGTHUC VARCHAR2(5000);
    RESULT_NUMBER  NUMBER;
    CURSOR_RESULT SYS_REFCURSOR;
    LOAI_TK VARCHAR2(2);
    U_SODU_DAUKY VARCHAR2(500);
    U_SODU_PS  VARCHAR2(500);
    U_CUOIKY  VARCHAR2(500);
    U_LK  VARCHAR2(500);
    T_TONDAU_SL NUMBER;
    T_PHATSINH_SL NUMBER;
    T_CUOIKY_SL NUMBER;
    V_COUNT  NUMBER;
    V_MAX_DATE DATE;
    V_RETURN VARCHAR2(32767);
    T_THANG NUMBER;
    T_NAM NUMBER;
    T_DAUTHANG VARCHAR2(20);
BEGIN
      P_CONGTHUC := '';
      RESULT_NUMBER := 0;
      --V_SQLDELETE := 'DELETE PHC_TEMP_SOKHO WHERE USER_NAME = '''||P_USERNAME||'''';
      --EXECUTE IMMEDIATE V_SQLDELETE;
      
      IF P_MAVATTU IS NULL OR P_MAVATTU = '' THEN P_CONGTHUC := P_CONGTHUC || ' 1 = 1 ';
      ELSE P_CONGTHUC := P_CONGTHUC || ' LOAIHINH_DOITUONG = '''||P_MAVATTU||''' ';
      END IF;
      
      IF P_MAKHO IS NULL OR P_MAKHO = '' THEN P_CONGTHUC := P_CONGTHUC || ' AND 1 = 1 ';
      ELSE P_CONGTHUC := P_CONGTHUC || ' AND MA_KHO = '''||P_MAKHO||''' ';
      END IF;
      IF P_FIELD = 'TONDAU_SL' THEN
        --V_RETURN := 'SELECT NVL(SUM(SOLUONG),0) FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU IN ('''||P_LOAICHUNGTU||''')';
        V_RETURN := 'SELECT ((SELECT NVL(SUM(SOLUONG),0) AS SOLUONG_NHAP FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU IN (''PNK'',''GTCC''))
                    -
                   (SELECT NVL(SUM(SOLUONG),0) AS SOLUONG_XUAT FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU IN (''PXK'',''GGCC'')) ) AS TONDAU_SL
                    FROM DUAL';        
      ELSIF P_FIELD = 'TONDAU_THANG_SL' THEN
        V_RETURN := 'SELECT ((SELECT NVL(SUM(SOLUONG),0) AS SOLUONG_NHAP FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU IN (''PNK'',''GTCC''))
                    -
                   (SELECT NVL(SUM(SOLUONG),0) AS SOLUONG_XUAT FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU IN (''PXK'',''GGCC'')) ) AS SODU_DAUKY
                    FROM DUAL';      
      ELSIF P_FIELD = 'TONCUOI_THANG_SL' THEN
        V_RETURN := 'SELECT ((SELECT NVL(SUM(SOLUONG),0) AS SOLUONG_NHAP FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU IN (''PNK'',''GTCC''))
                    -
                   (SELECT NVL(SUM(SOLUONG),0) AS SOLUONG_XUAT FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU IN (''PXK'',''GGCC'')) ) AS SODU_CUOIKY
                    FROM DUAL';
      DBMS_OUTPUT.put_line ('<V_RETURN V_RETURN>' || V_RETURN);
      ELSIF P_FIELD = 'PHATSINH_SL' THEN
        V_RETURN := 'SELECT NVL(SUM(SOLUONG),0) FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') >= TO_DATE('''||P_TUNGAYHL||''',''DD-MM-YYYY'')  AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') <= TO_DATE('''||P_DENNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU = '''||P_LOAICHUNGTU||'''';
      ELSE 
        V_RETURN := 'SELECT NVL(SUM(SOLUONG),0) FROM V_PHC_TH_CHUNGTU WHERE '||P_CONGTHUC||' AND TO_DATE(NGAY_HT,''DD-MM-YYYY'') < TO_DATE('''||P_DENNGAYHL||''',''DD-MM-YYYY'') AND MA_CHUNGTU = '''||P_LOAICHUNGTU||'''';
      END IF;
      
     OPEN CURSOR_RESULT FOR V_RETURN;
     LOOP
        FETCH CURSOR_RESULT INTO RESULT_NUMBER;
        EXIT WHEN CURSOR_RESULT%NOTFOUND;
        RETURN RESULT_NUMBER;
     END LOOP;
       EXCEPTION
       WHEN NO_DATA_FOUND
       THEN
          DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
       WHEN OTHERS
       THEN
          DBMS_OUTPUT.put_line ('ERROR'  || SQLERRM);
END PHC_FCN_ACCOUNT_BY_MER;