create or replace PROCEDURE "PHB_BIEU09TT344_SUMREPORT" 
(
  MACHUONG IN NVARCHAR2,
  NAMBC IN NUMBER,
  KYBC IN NUMBER,
  DSDVQHNS IN NVARCHAR2,
  CUR OUT SYS_REFCURSOR
)IS
P_QUERY VARCHAR2(32767);
BEGIN
    P_QUERY:='SELECT CT.ID, CT.TEN_CHI_TIEU, CT.IN_DAM,SUM(CT.DT_TONGSO) AS DT_TONGSO,SUM(CT.DT_DTPT) AS DT_DTPT,SUM(CT.DT_TX) AS DT_TX
        ,SUM(CT.QT_TONGSO) AS QT_TONGSO,SUM(CT.QT_DTPT) AS QT_DTPT,SUM(CT.QT_TX) AS QT_TX
        ,SUM(CT.SS_TONGSO) AS SS_TONGSO,SUM(CT.SS_DTPT) AS SS_DTPT,SUM(CT.SS_TX) AS SS_TX
    FROM PHB_BIEU09TT344 TH INNER JOIN SYS_DVQHNS DVQHNS ON TH.MA_QHNS=DVQHNS.MA_DVQHNS INNER JOIN PHB_BIEU09TT344_DETAIL CT ON CT.PHB_BIEU09TT344_REFID = TH.REFID
    WHERE (TH.NAM_BC=CASE '||NAMBC||' WHEN -1 THEN TH.NAM_BC ELSE '||NAMBC||' END) AND (TH.KY_BC=CASE '||KYBC||' WHEN -1 THEN TH.KY_BC ELSE '||KYBC||' END) AND DVQHNS.TRANG_THAI=''A''';    
    IF DSDVQHNS IS NOT NULL THEN
        P_QUERY:=P_QUERY||' AND TH.MA_QHNS IN('||DSDVQHNS||')';
    END IF;
    IF MACHUONG IS NOT NULL THEN
        P_QUERY:=P_QUERY||' AND TH.MA_CHUONG='''||MACHUONG||'''';
    END IF;
    P_QUERY:=P_QUERY||' GROUP BY CT.ID,CT.TEN_CHI_TIEU, CT.IN_DAM';
    P_QUERY:=P_QUERY||' ORDER BY CT.ID';
    DBMS_OUTPUT.put_line(P_QUERY); 

    OPEN cur FOR P_QUERY;
END "PHB_BIEU09TT344_SUMREPORT";