create or replace PROCEDURE "PHA_CHI2_BG" (P_MA_DBHC IN NVARCHAR2, P_CONGTHUC VARCHAR2, TUNGAY_KS IN DATE, DENNGAY_KS IN DATE, TUNGAY_HL IN DATE, DENNGAY_HL IN DATE, DONVI_TIEN number, cur OUT SYS_REFCURSOR) as
  QUERY_STR  CLOB; 
  QUERY_STR1  CLOB; 
   INSERT_STR  CLOB; 
   INSERT_STR1  CLOB;
   QUERY_STR_CHI CLOB;
   QUERY_STR_DUTOAN CLOB;
   P_CT VARCHAR2(32767);   
   P_SQL_INSERT VARCHAR2(32767); 
   P_SQL_CREATE_TABLE_TH  VARCHAR2(32767);  
    N_COUNT NUMBER(17,4):=0;
    P_SELECT_DBHC VARCHAR2(32767);

   --CHI 
   CT_30110 VARCHAR2(32767);   CT_30120 VARCHAR2(32767);   CT_30130 VARCHAR2(32767);   CT_30140 VARCHAR2(32767); CT_30150 VARCHAR2(32767); CT_30160 VARCHAR2(32767);
   CT_30170 VARCHAR2(32767);   CT_30180 VARCHAR2(32767);   CT_30190 VARCHAR2(32767);   CT_30200 VARCHAR2(32767);
   CT_30210 VARCHAR2(32767);   CT_30220 VARCHAR2(32767);   CT_34020 VARCHAR2(32767);   CT_34030 VARCHAR2(32767);
   CT_34040 VARCHAR2(32767);   CT_34080 VARCHAR2(32767);    CT_34090 VARCHAR2(32767);   CT_34300 VARCHAR2(32767);    CT_34400 VARCHAR2(32767);
   CT_34500 VARCHAR2(32767);   CT_34600 VARCHAR2(32767);    CT_34700 VARCHAR2(32767);   CT_34800 VARCHAR2(32767);    CT_34900 VARCHAR2(32767);
   CT_43000 VARCHAR2(32767);   CT_47000 VARCHAR2(32767);    CT_48000 VARCHAR2(32767);
   --DU TOAN 
   CT_DT_30110 VARCHAR2(32767);   CT_DT_30120 VARCHAR2(32767);   CT_DT_30130 VARCHAR2(32767);   CT_DT_30140 VARCHAR2(32767);CT_DT_30150 VARCHAR2(32767);CT_DT_30160 VARCHAR2(32767);
   CT_DT_30170 VARCHAR2(32767);   CT_DT_30180 VARCHAR2(32767);   CT_DT_30190 VARCHAR2(32767);   CT_DT_30200 VARCHAR2(32767);
   CT_DT_30210 VARCHAR2(32767);   CT_DT_30220 VARCHAR2(32767);   CT_DT_34020 VARCHAR2(32767);   CT_DT_34030 VARCHAR2(32767);
   CT_DT_34040 VARCHAR2(32767);   CT_DT_34080 VARCHAR2(32767);    CT_DT_34090 VARCHAR2(32767);   CT_DT_34300 VARCHAR2(32767);    CT_DT_34400 VARCHAR2(32767);
   CT_DT_34500 VARCHAR2(32767);   CT_DT_34600 VARCHAR2(32767);    CT_DT_34700 VARCHAR2(32767);   CT_DT_34800 VARCHAR2(32767);    CT_DT_34900 VARCHAR2(32767);
   
   BEGIN
    IF TRIM(P_CONGTHUC) IS NOT NULL THEN 
        select STC_PA_SYS.FNC_CONVERT_FORMULA_HCSN(P_CONGTHUC) INTO P_CT from dual;       
        P_CT:= ' AND ' || P_CT;
    END IF;

    --Gán công thức 
    -------Chi đầu tư    
    
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30110 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30110' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30120 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30120' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30130 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30130' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30140 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30140' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30150 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30150' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30160 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30160' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30170 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30170' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30180 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30180' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30190 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30190' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30200 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30200' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30210 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30210' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_30220 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='30220' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34020 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34020' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34030 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34030' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34040 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34040' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34080 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34080' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34090 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34090' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34300 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34300' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34400 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34400' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34500 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34500' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34600 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34600' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34700 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34700' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34800 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34800' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_34900 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='34900' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');

         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30110 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30110' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30120 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30120' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30130 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30130' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30140 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30140' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30150 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30150' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30160 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30160' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30170 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30170' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30180 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30180' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30190 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30190' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30200 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30200' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30210 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30210' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_30220 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_30220' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34020 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34020' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34030 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34030' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34040 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34040' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34080 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34080' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34090 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34090' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34300 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34300' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34400 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34400' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34500 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34500' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34600 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34600' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34700 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34700' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34800 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34800' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_DT_34900 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='DT_34900' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_43000 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='43000' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_47000 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='47000' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');
         select REPLACE(CONGTHUC_DH_WHERE, '''', '''') INTO CT_48000 from DM_CHITIEU_BAOCAO_COL WHERE MA_BAOCAO='CHI2' AND MA_COT='48000' AND NGAY_HL <= TO_DATE (''||to_char(TUNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND NGAY_HET_HL >= TO_DATE (''||to_char(DENNGAY_HL,'ddMMyyyy')||'', 'ddMMyyyy') AND MA_DBHC LIKE (SELECT MA_T FROM DM_DBHC WHERE MA_DBHC LIKE ''||P_MA_DBHC||'');


    P_SQL_CREATE_TABLE_TH := 'CREATE TABLE CHI2_BG(
        LOAI_CHITIEU NUMBER,MA_TKTN NVARCHAR2(100), MA_DIABAN NVARCHAR2(100),TEN_DIABAN NVARCHAR2(2000),MA_CAP NVARCHAR2(100),MA_CAPMLNS NVARCHAR2(100),MA_CHUONG NVARCHAR2(100),TEN_CHUONG NVARCHAR2(2000),MA_NGANHKT NVARCHAR2(100),MA_LOAI NVARCHAR2(100),
        MA_TIEUMUC NVARCHAR2(100), MA_MUC NVARCHAR2(100), MA_TIEUNHOM NVARCHAR2(100),MA_NHOM NVARCHAR2(100),MA_CTMTQG NVARCHAR2(100),MA_KBNN NVARCHAR2(100), NGAY_HIEU_LUC DATE, NGAY_KET_SO DATE,LOAI_DU_TOAN NVARCHAR2(100),
        MA_NGUON_NSNN NVARCHAR2(100),MA_DVQHNS NVARCHAR2(100),TEN_DVQHNS NVARCHAR2(2000), MA_NVC NVARCHAR2(100), GIA_TRI_HACH_TOAN NUMBER)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ';         

     QUERY_STR_CHI := 'SELECT 2,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,TO_DATE(to_char(NGAY_HIEU_LUC,''ddMMyyyy''), ''ddMMyyyy''),TO_DATE (to_char(NGAY_KET_SO,''ddMMyyyy''), ''ddMMyyyy''),ATTRIBUTE8
        ,SUM (GIA_TRI_HACH_TOAN) FROM PHA_HACHTOAN_CHI VC 
         GROUP BY  MA_TKTN,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,ATTRIBUTE8';   
        INSERT_STR := 'INSERT INTO CHI2_BG(LOAI_CHITIEU,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,LOAI_DU_TOAN,GIA_TRI_HACH_TOAN)('||QUERY_STR_CHI||')';

   QUERY_STR_DUTOAN := 'SELECT 3,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,TO_DATE(to_char(NGAY_HIEU_LUC,''ddMMyyyy''), ''ddMMyyyy''),TO_DATE (to_char(NGAY_KET_SO,''ddMMyyyy''), ''ddMMyyyy''),ATTRIBUTE8
        ,SUM (GIA_TRI_HACH_TOAN) FROM PHA_DUTOAN VC 
         GROUP BY  MA_TKTN,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI,MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,ATTRIBUTE8';   
        INSERT_STR1 := 'INSERT INTO CHI2_BG(LOAI_CHITIEU,MA_TKTN ,MA_DIABAN, TEN_DIABAN,MA_CAP,MA_CAPMLNS,MA_CHUONG,TEN_CHUONG,MA_NGANHKT,MA_LOAI, MA_TIEUMUC,MA_MUC,MA_TIEUNHOM,MA_NHOM,MA_CTMTQG,MA_KBNN,MA_NGUON_NSNN,MA_DVQHNS, TEN_DVQHNS,MA_NVC,NGAY_HIEU_LUC,NGAY_KET_SO,LOAI_DU_TOAN,GIA_TRI_HACH_TOAN)('||QUERY_STR_DUTOAN||')';
  BEGIN
        SELECT COUNT(*)  INTO N_COUNT  FROM ALL_TAB_COLUMNS  WHERE TABLE_NAME = 'CHI2_BG';
        EXCEPTION WHEN OTHERS THEN N_COUNT:=0;
    END;
  IF(N_COUNT IS NULL OR N_COUNT<=0) THEN
    BEGIN
        EXECUTE IMMEDIATE P_SQL_CREATE_TABLE_TH;  
        EXECUTE IMMEDIATE INSERT_STR; 
        EXECUTE IMMEDIATE INSERT_STR1;  
    END;
    END IF;

        P_SELECT_DBHC:= ' AND A.MA_DIABAN IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||''') OR MA_DBHC_CHA IN (SELECT MA_DBHC FROM DM_DBHC WHERE MA_DBHC = '''||P_MA_DBHC||''' OR MA_DBHC_CHA = '''||P_MA_DBHC||'''))';

        IF(P_SELECT_DBHC IS NOT NULL) THEN
        P_CT:=P_CT || P_SELECT_DBHC;
        ELSE
        P_CT:=P_CT;
        END IF;
           QUERY_STR:='SELECT HT.MA_DIABAN, HT.TEN_DIABAN
                                , NVL(HT.QT_30110,0) as QT_30110, NVL(HT.QT_30120,0) as QT_30120, NVL(HT.QT_30130,0) as QT_30130, NVL(HT.QT_30140,0) as QT_30140, NVL(HT.QT_30150,0) as QT_30150, NVL(HT.QT_30160,0) as QT_30160, NVL(HT.QT_30170,0) as QT_30170
                                , NVL(HT.QT_30180,0) as QT_30180, NVL(HT.QT_30190,0) as QT_30190, NVL(HT.QT_30200,0) as QT_30200, NVL(HT.QT_30210,0) as QT_30210
                                , NVL(HT.QT_30220,0) as QT_30220, NVL(HT.QT_34020,0) as QT_34020, NVL(HT.QT_34030,0) as QT_34030, NVL(HT.QT_34040,0) as QT_34040
                                , NVL(HT.QT_34080,0) as QT_34080, NVL(HT.QT_34090,0) as QT_34090, NVL(HT.QT_34300,0) as QT_34300, NVL(HT.QT_34400,0) as QT_34400, NVL(HT.QT_34500,0) as QT_34500
                                , NVL(HT.QT_34600,0) as QT_34600, NVL(HT.QT_34700,0) as QT_34700, NVL(HT.QT_34800,0) as QT_34800, NVL(HT.QT_34900,0) as QT_34900
                                , NVL(HT.DT_30110,0) as DT_30110, NVL(HT.DT_30120,0) as DT_30120, NVL(HT.DT_30130,0) as DT_30130, NVL(HT.DT_30140,0) as DT_30140
                                , NVL(HT.DT_30150,0) as DT_30150, NVL(HT.DT_30160,0) as DT_30160, NVL(HT.DT_30170,0) as DT_30170
                                , NVL(HT.DT_30180,0) as DT_30180, NVL(HT.DT_30190,0) as DT_30190, NVL(HT.DT_30200,0) as DT_30200, NVL(HT.DT_30210,0) as DT_30210
                                , NVL(HT.DT_30220,0) as DT_30220, NVL(HT.DT_34020,0) as DT_34020, NVL(HT.DT_34030,0) as DT_34030, NVL(HT.DT_34040,0) as DT_34040
                                , NVL(HT.DT_34080,0) as DT_34080, NVL(HT.DT_34090,0) as DT_34090, NVL(HT.DT_34300,0) as DT_34300, NVL(HT.DT_34400,0) as DT_34400, NVL(HT.DT_34500,0) as DT_34500
                                , NVL(HT.DT_34600,0) as DT_34600, NVL(HT.DT_34700,0) as DT_34700, NVL(HT.DT_34800,0) as DT_34800, NVL(HT.DT_34900,0) as DT_34900
                                , NVL(HT.QT_43000,0) as QT_43000, NVL(HT.QT_47000,0) as QT_47000, NVL(HT.QT_48000,0) as QT_48000
                        FROM
                        ( SELECT QT.MA_CHUONG, QT.TEN_CHUONG, QT.MA_DVQHNS, QT.TEN_DVQHNS, QT.MA_DIABAN, QT.TEN_DIABAN
                                , NVL(QT.QT_30110,0) as QT_30110, NVL(QT.QT_30120,0) as QT_30120, NVL(QT.QT_30130,0) as QT_30130, NVL(QT.QT_30140,0) as QT_30140, NVL(QT.QT_30150,0) as QT_30150
                                , NVL(QT.QT_30160,0) as QT_30160, NVL(QT.QT_30170,0) as QT_30170
                                , NVL(QT.QT_30180,0) as QT_30180, NVL(QT.QT_30190,0) as QT_30190, NVL(QT.QT_30200,0) as QT_30200, NVL(QT.QT_30210,0) as QT_30210
                                , NVL(QT.QT_30220,0) as QT_30220, NVL(QT.QT_34020,0) as QT_34020, NVL(QT.QT_34030,0) as QT_34030, NVL(QT.QT_34040,0) as QT_34040
                                , NVL(QT.QT_34080,0) as QT_34080, NVL(QT.QT_34090,0) as QT_34090, NVL(QT.QT_34300,0) as QT_34300, NVL(QT.QT_34400,0) as QT_34400, NVL(QT.QT_34500,0) as QT_34500
                                , NVL(QT.QT_34600,0) as QT_34600, NVL(QT.QT_34700,0) as QT_34700, NVL(QT.QT_34800,0) as QT_34800, NVL(QT.QT_34900,0) as QT_34900
                                , NVL(DT.DT_30110,0) as DT_30110, NVL(DT.DT_30120,0) as DT_30120, NVL(DT.DT_30130,0) as DT_30130, NVL(DT.DT_30140,0) as DT_30140, NVL(DT.DT_30150,0) as DT_30150
                                , NVL(DT.DT_30160,0) as DT_30160, NVL(DT.DT_30170,0) as DT_30170, NVL(DT.DT_30180,0) as DT_30180, NVL(DT.DT_30190,0) as DT_30190, NVL(DT.DT_30200,0) as DT_30200
                                , NVL(DT.DT_30210,0) as DT_30210, NVL(DT.DT_30220,0) as DT_30220, NVL(DT.DT_34020,0) as DT_34020, NVL(DT.DT_34030,0) as DT_34030, NVL(DT.DT_34040,0) as DT_34040
                                , NVL(DT.DT_34080,0) as DT_34080, NVL(DT.DT_34090,0) as DT_34090, NVL(DT.DT_34300,0) as DT_34300, NVL(DT.DT_34400,0) as DT_34400, NVL(DT.DT_34500,0) as DT_34500
                                , NVL(DT.DT_34600,0) as DT_34600, NVL(DT.DT_34700,0) as DT_34700, NVL(DT.DT_34800,0) as DT_34800, NVL(DT.DT_34900,0) as DT_34900
                                , NVL(QT.QT_43000,0) as QT_43000, NVL(QT.QT_47000,0) as QT_47000, NVL(QT.QT_48000,0) as QT_48000
                                FROM
                        (SELECT A.MA_CHUONG AS MA_CHUONG, A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS, A.MA_DIABAN, A.TEN_DIABAN
                                ,NVL(SUM (CASE WHEN ('|| CT_30110 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30110
                                ,NVL(SUM (CASE WHEN ('|| CT_30120 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30120
                                ,NVL(SUM (CASE WHEN ('|| CT_30130 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30130
                                ,NVL(SUM (CASE WHEN ('|| CT_30140 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30140
                                ,NVL(SUM (CASE WHEN ('|| CT_30150 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30150
                                ,NVL(SUM (CASE WHEN ('|| CT_30160 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30160
                                ,NVL(SUM (CASE WHEN ('|| CT_30170 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30170
                                ,NVL(SUM (CASE WHEN ('|| CT_30180 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30180
                                ,NVL(SUM (CASE WHEN ('|| CT_30190 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30190
                                ,NVL(SUM (CASE WHEN ('|| CT_30200 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30200
                                ,NVL(SUM (CASE WHEN ('|| CT_30210 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30210
                                ,NVL(SUM (CASE WHEN ('|| CT_30220 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_30220
                                ,NVL(SUM (CASE WHEN ('|| CT_34020 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34020
                                ,NVL(SUM (CASE WHEN ('|| CT_34030 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34030
                                ,NVL(SUM (CASE WHEN ('|| CT_34040 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34040
                                ,NVL(SUM (CASE WHEN ('|| CT_34080 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34080
                                ,NVL(SUM (CASE WHEN ('|| CT_34090 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34090
                                ,NVL(SUM (CASE WHEN ('|| CT_34300 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34300
                                ,NVL(SUM (CASE WHEN ('|| CT_34400 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34400
                                ,NVL(SUM (CASE WHEN ('|| CT_34500 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34500
                                ,NVL(SUM (CASE WHEN ('|| CT_34600 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34600
                                ,NVL(SUM (CASE WHEN ('|| CT_34700 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34700
                                ,NVL(SUM (CASE WHEN ('|| CT_34800 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34800
                                ,NVL(SUM (CASE WHEN ('|| CT_34900 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_34900
                                ,NVL(SUM (CASE WHEN ('|| CT_43000 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_43000
                                ,NVL(SUM (CASE WHEN ('|| CT_47000 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_47000
                                ,NVL(SUM (CASE WHEN ('|| CT_48000 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS QT_48000
                         FROM CHI2_BG A
                        WHERE A.NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')
                        AND A.NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')     
                        and A.NGAY_KET_SO <=TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                        and A.NGAY_KET_SO >=TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                         ' || P_CT ||' GROUP BY A.MA_CHUONG,A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS, A.MA_DIABAN, A.TEN_DIABAN) QT ';
                           QUERY_STR1:=' LEFT JOIN        
                          (SELECT A.MA_CHUONG AS MA_CHUONG, A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS      
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30110 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30110
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30120 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30120
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30130 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30130
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30140 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30140
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30150 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30150
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30160 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30160
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30170 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30170
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30180 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30180
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30190 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30190
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30200 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30200
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30210 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30210
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_30220 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_30220
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34020 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34020
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34030 ||')   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34030
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34040 ||')     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34040  
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34080 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34080
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34090 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34090
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34300 ||' )     THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34300
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34400 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34400
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34500 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34500
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34600 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34600
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34700 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34700
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34800 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34800
                                ,NVL(SUM (CASE WHEN ('|| CT_DT_34900 ||' )   THEN A.GIA_TRI_HACH_TOAN/NVL('|| DONVI_TIEN ||',1) ELSE 0 END),0) AS DT_34900

                        FROM CHI2_BG A
                        WHERE A.NGAY_HIEU_LUC >= TO_DATE ('''||to_char(TUNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')
                        AND A.NGAY_HIEU_LUC <= TO_DATE ('''||to_char(DENNGAY_HL,'ddMMyyyy')||''', ''ddMMyyyy'')     
                        and A.NGAY_KET_SO <=TO_DATE ('''||to_char(DENNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                        and A.NGAY_KET_SO >=TO_DATE ('''||to_char(TUNGAY_KS,'ddMMyyyy')||''', ''ddMMyyyy'')
                         GROUP BY A.MA_CHUONG,A.TEN_CHUONG, A.MA_DVQHNS, A.TEN_DVQHNS) DT ON QT.MA_CHUONG = DT.MA_CHUONG AND QT.MA_DVQHNS = DT.MA_DVQHNS
                            GROUP BY QT.MA_CHUONG, QT.TEN_CHUONG, QT.MA_DVQHNS, QT.TEN_DVQHNS, QT.MA_DIABAN, QT.TEN_DIABAN
                                , QT.QT_30110,QT.QT_30120, QT.QT_30130, QT.QT_30140, QT.QT_30150
                                , QT.QT_30160, QT.QT_30170, QT.QT_30180, QT.QT_30190, QT.QT_30200, QT.QT_30210
                                , QT.QT_30220, QT.QT_34020, QT.QT_34030, QT.QT_34040, QT.QT_34080, QT.QT_34090, QT.QT_34300, QT.QT_34400, QT.QT_34500
                                , QT.QT_34600, QT.QT_34700, QT.QT_34800, QT.QT_34900
                                , DT.DT_30110, DT.DT_30120, DT.DT_30130, DT.DT_30140, DT.DT_30150, DT.DT_30160
                                , DT.DT_30170, DT.DT_30180, DT.DT_30190, DT.DT_30200
                                , DT.DT_30210, DT.DT_30220, DT.DT_34020, DT.DT_34030
                                , DT.DT_34040, DT.DT_34080, DT.DT_34090, DT.DT_34300, DT.DT_34400, DT.DT_34500
                                , DT.DT_34600, DT.DT_34700, DT.DT_34800, DT.DT_34900
                                , QT.QT_43000, QT.QT_47000, QT.QT_48000
                        ) HT 
                        WHERE 1=1 AND (HT.QT_30110 <> 0 OR HT.QT_30120 <> 0 OR HT.QT_30130 <> 0 OR HT.QT_30140 <> 0 OR HT.QT_30150<> 0 OR HT.QT_30160 <> 0
                            OR HT.QT_30170 <> 0 OR HT.QT_30180 <> 0 OR HT.QT_30190 <> 0 OR HT.QT_30200 <>0 OR HT.QT_30210 <> 0 OR HT.QT_30220 <> 0 OR HT.QT_34020 <> 0 OR HT.QT_34030 <>0 OR HT.QT_34040 <> 0
                            OR HT.QT_34080 <> 0 OR HT.QT_34090 <> 0 OR HT.QT_34300 <> 0 OR HT.QT_34400 <> 0 OR HT.QT_34500<> 0 OR HT.QT_34600 <> 0
                            OR HT.QT_34700 <> 0 OR HT.QT_34800 <> 0 OR HT.QT_34900 <> 0 OR HT.QT_43000 <>0 OR HT.QT_47000 <> 0 OR HT.QT_48000 <> 0 
                            ) ORDER BY HT.MA_DIABAN';
  DBMS_OUTPUT.put_line (QUERY_STR1); 
BEGIN
EXECUTE IMMEDIATE QUERY_STR||QUERY_STR1;
OPEN cur FOR QUERY_STR||QUERY_STR1;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
   WHEN OTHERS
   THEN
      --DBMS_OUTPUT.put_line (QUERY_STR  || SQLERRM); 
      DBMS_OUTPUT.put_line ('<your message>' || SQLERRM);
END;    
END PHA_CHI2_BG;